/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class Avataring : AvataringBase)
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Avataring.def
	// Please inherit and implement "class Avataring : AvataringBase"
	public abstract class AvataringBase : ModelEntity
	{
		public EntityBaseEntityCall_AvataringBase baseEntityCall = null;
		public EntityCellEntityCall_AvataringBase cellEntityCall = null;

		
		
		
		
		
		
		
		
		


		public AvataringBase()
		{
		}

		public override void onComponentsEnterworld()
		{
		}

		public override void onComponentsLeaveworld()
		{
		}

		public override void onGetBase()
		{
			baseEntityCall = new EntityBaseEntityCall_AvataringBase(id, className);
		}

		public override void onGetCell()
		{
			cellEntityCall = new EntityCellEntityCall_AvataringBase(id, className);
		}

		public override void onLoseCell()
		{
			cellEntityCall = null;
		}

		public override EntityCall getBaseEntityCall()
		{
			return baseEntityCall;
		}

		public override EntityCall getCellEntityCall()
		{
			return cellEntityCall;
		}

		public override void attachComponents()
		{
		}

		public override void detachComponents()
		{
		}

		public override void onRemoteMethodCall(MemoryStream stream)
		{
			ScriptModule sm = EntityDef.moduledefs["Avataring"];

			UInt16 methodUtype = 0;
			UInt16 componentPropertyUType = 0;

			if(sm.usePropertyDescrAlias)
			{
				componentPropertyUType = stream.readUint8();
			}
			else
			{
				componentPropertyUType = stream.readUint16();
			}

			if(sm.useMethodDescrAlias)
			{
				methodUtype = stream.readUint8();
			}
			else
			{
				methodUtype = stream.readUint16();
			}

			Method method = null;

			if(componentPropertyUType == 0)
			{
				method = sm.idmethods[methodUtype];
			}
			else
			{
				Property pComponentPropertyDescription = sm.idpropertys[componentPropertyUType];
				switch(pComponentPropertyDescription.properUtype)
				{
					default:
						break;
				}

				return;
			}

			switch(method.methodUtype)
			{
				case 1173:
					onClientDataSyncFinished();
					break;
				case 1194:
					UInt32 onRecvAvatarChannelMsg_arg1 = stream.readUint32();
					CHAT_CHANNEL_AVATAR_INFO onRecvAvatarChannelMsg_arg2 = ((DATATYPE_CHAT_CHANNEL_AVATAR_INFO)method.args[1]).createFromStreamEx(stream);
					CHAT_MSG_DATA onRecvAvatarChannelMsg_arg3 = ((DATATYPE_CHAT_MSG_DATA)method.args[2]).createFromStreamEx(stream);
					onRecvAvatarChannelMsg(onRecvAvatarChannelMsg_arg1, onRecvAvatarChannelMsg_arg2, onRecvAvatarChannelMsg_arg3);
					break;
				case 1156:
					Int32 popDialog_arg1 = stream.readInt32();
					popDialog(popDialog_arg1);
					break;
				case 1157:
					UInt32 showPopoverMsg_arg1 = stream.readUint32();
					showPopoverMsg(showPopoverMsg_arg1);
					break;
				case 1158:
					UInt32 showPopoverMsgWithArg_arg1 = stream.readUint32();
					List<string> showPopoverMsgWithArg_arg2 = ((DATATYPE_AnonymousArray_10001)method.args[1]).createFromStreamEx(stream);
					showPopoverMsgWithArg(showPopoverMsgWithArg_arg1, showPopoverMsgWithArg_arg2);
					break;
				default:
					break;
			};
		}

		public override void onUpdatePropertys(MemoryStream stream)
		{
			ScriptModule sm = EntityDef.moduledefs["Avataring"];
			Dictionary<UInt16, Property> pdatas = sm.idpropertys;

			while(stream.length() > 0)
			{
				UInt16 _t_utype = 0;
				{
					if(sm.usePropertyDescrAlias)
					{
						_t_utype = stream.readUint8();
					}
					else
					{
						_t_utype = stream.readUint16();
					}
				}

				Property prop = null;

				if(_t_utype != 0)
				{
					prop = pdatas[_t_utype];
				}
				else
				{
					Property pComponentPropertyDescription = pdatas[_t_utype];
					switch(pComponentPropertyDescription.properUtype)
					{
						default:
							break;
					}

					return;
				}

				switch(prop.properUtype)
				{
					case 593:
						APPEARANCE_INFO oldval_appearance = appearance;
						appearance = ((DATATYPE_APPEARANCE_INFO)EntityDef.id2datatypes[33]).createFromStreamEx(stream);

						if(prop.isBase())
						{
							if(inited)
								onAppearanceChanged(oldval_appearance);
						}
						else
						{
							if(inWorld)
								onAppearanceChanged(oldval_appearance);
						}

						break;
					case 40001:
						Vector3 oldval_direction = direction;
						direction = stream.readVector3();

						if(prop.isBase())
						{
							if(inited)
								onDirectionChanged(oldval_direction);
						}
						else
						{
							if(inWorld)
								onDirectionChanged(oldval_direction);
						}

						break;
					case 578:
						UInt64 oldval_gbId = gbId;
						gbId = stream.readUint64();

						if(prop.isBase())
						{
							if(inited)
								onGbIdChanged(oldval_gbId);
						}
						else
						{
							if(inWorld)
								onGbIdChanged(oldval_gbId);
						}

						break;
					case 600:
						string oldval_name = name;
						name = stream.readUnicode();

						if(prop.isBase())
						{
							if(inited)
								onNameChanged(oldval_name);
						}
						else
						{
							if(inWorld)
								onNameChanged(oldval_name);
						}

						break;
					case 40000:
						Vector3 oldval_position = position;
						position = stream.readVector3();

						if(prop.isBase())
						{
							if(inited)
								onPositionChanged(oldval_position);
						}
						else
						{
							if(inWorld)
								onPositionChanged(oldval_position);
						}

						break;
					case 610:
						UInt16 oldval_school = school;
						school = stream.readUint16();

						if(prop.isBase())
						{
							if(inited)
								onSchoolChanged(oldval_school);
						}
						else
						{
							if(inWorld)
								onSchoolChanged(oldval_school);
						}

						break;
					case 613:
						Byte oldval_sex = sex;
						sex = stream.readUint8();

						if(prop.isBase())
						{
							if(inited)
								onSexChanged(oldval_sex);
						}
						else
						{
							if(inWorld)
								onSexChanged(oldval_sex);
						}

						break;
					case 40002:
						stream.readUint32();
						break;
					case 280:
						UInt32 oldval_spaceNo = spaceNo;
						oldSpaceNo = oldval_spaceNo;
						spaceNo = stream.readUint32();

						if(prop.isBase())
						{
							if(inited)
								onSpaceNoChanged(oldval_spaceNo);
						}
						else
						{
							if(inWorld)
								onSpaceNoChanged(oldval_spaceNo);
						}

						break;
					case 631:
						float oldval_speed = speed;
						speed = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onSpeedChanged(oldval_speed);
						}
						else
						{
							if(inWorld)
								onSpeedChanged(oldval_speed);
						}

						break;
					case 614:
						Int64 oldval_state = state;
						state = stream.readInt64();

						if(prop.isBase())
						{
							if(inited)
								onStateChanged(oldval_state);
						}
						else
						{
							if(inWorld)
								onStateChanged(oldval_state);
						}

						break;
					case 630:
						Int64 oldval_state2 = state2;
						state2 = stream.readInt64();

						if(prop.isBase())
						{
							if(inited)
								onState2Changed(oldval_state2);
						}
						else
						{
							if(inWorld)
								onState2Changed(oldval_state2);
						}

						break;
					default:
						break;
				};
			}
		}

		public override void callPropertysSetMethods()
		{
			ScriptModule sm = EntityDef.moduledefs["Avataring"];
			Dictionary<UInt16, Property> pdatas = sm.idpropertys;

			APPEARANCE_INFO oldval_appearance = appearance;
			Property prop_appearance = pdatas[4];
			if(prop_appearance.isBase())
			{
				if(inited && !inWorld)
					onAppearanceChanged(oldval_appearance);
			}
			else
			{
				if(inWorld)
				{
					if(prop_appearance.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onAppearanceChanged(oldval_appearance);
					}
				}
			}

			Vector3 oldval_direction = direction;
			Property prop_direction = pdatas[2];
			if(prop_direction.isBase())
			{
				if(inited && !inWorld)
					onDirectionChanged(oldval_direction);
			}
			else
			{
				if(inWorld)
				{
					if(prop_direction.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onDirectionChanged(oldval_direction);
					}
				}
			}

			UInt64 oldval_gbId = gbId;
			Property prop_gbId = pdatas[6];
			if(prop_gbId.isBase())
			{
				if(inited && !inWorld)
					onGbIdChanged(oldval_gbId);
			}
			else
			{
				if(inWorld)
				{
					if(prop_gbId.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onGbIdChanged(oldval_gbId);
					}
				}
			}

			string oldval_name = name;
			Property prop_name = pdatas[5];
			if(prop_name.isBase())
			{
				if(inited && !inWorld)
					onNameChanged(oldval_name);
			}
			else
			{
				if(inWorld)
				{
					if(prop_name.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onNameChanged(oldval_name);
					}
				}
			}

			Vector3 oldval_position = position;
			Property prop_position = pdatas[1];
			if(prop_position.isBase())
			{
				if(inited && !inWorld)
					onPositionChanged(oldval_position);
			}
			else
			{
				if(inWorld)
				{
					if(prop_position.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onPositionChanged(oldval_position);
					}
				}
			}

			UInt16 oldval_school = school;
			Property prop_school = pdatas[7];
			if(prop_school.isBase())
			{
				if(inited && !inWorld)
					onSchoolChanged(oldval_school);
			}
			else
			{
				if(inWorld)
				{
					if(prop_school.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onSchoolChanged(oldval_school);
					}
				}
			}

			Byte oldval_sex = sex;
			Property prop_sex = pdatas[8];
			if(prop_sex.isBase())
			{
				if(inited && !inWorld)
					onSexChanged(oldval_sex);
			}
			else
			{
				if(inWorld)
				{
					if(prop_sex.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onSexChanged(oldval_sex);
					}
				}
			}

			UInt32 oldval_spaceNo = spaceNo;
			Property prop_spaceNo = pdatas[9];
			if(prop_spaceNo.isBase())
			{
				if(inited && !inWorld)
					onSpaceNoChanged(oldval_spaceNo);
			}
			else
			{
				if(inWorld)
				{
					if(prop_spaceNo.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onSpaceNoChanged(oldval_spaceNo);
					}
				}
			}

			float oldval_speed = speed;
			Property prop_speed = pdatas[12];
			if(prop_speed.isBase())
			{
				if(inited && !inWorld)
					onSpeedChanged(oldval_speed);
			}
			else
			{
				if(inWorld)
				{
					if(prop_speed.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onSpeedChanged(oldval_speed);
					}
				}
			}

			Int64 oldval_state = state;
			Property prop_state = pdatas[10];
			if(prop_state.isBase())
			{
				if(inited && !inWorld)
					onStateChanged(oldval_state);
			}
			else
			{
				if(inWorld)
				{
					if(prop_state.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onStateChanged(oldval_state);
					}
				}
			}

			Int64 oldval_state2 = state2;
			Property prop_state2 = pdatas[11];
			if(prop_state2.isBase())
			{
				if(inited && !inWorld)
					onState2Changed(oldval_state2);
			}
			else
			{
				if(inWorld)
				{
					if(prop_state2.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onState2Changed(oldval_state2);
					}
				}
			}

		}
	}
}