/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class AvatarReplica : AvatarReplicaBase)
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/AvatarReplica.def
	// Please inherit and implement "class AvatarReplica : AvatarReplicaBase"
	public abstract class AvatarReplicaBase : ModelEntity
	{
		public EntityBaseEntityCall_AvatarReplicaBase baseEntityCall = null;
		public EntityCellEntityCall_AvatarReplicaBase cellEntityCall = null;

		
		public Int32 antiFatal = 0;
		
		public Byte arType = 0;
		public virtual void onArTypeChanged(Byte oldValue) {}
		public Int32 avatarId = 0;
		public virtual void onAvatarIdChanged(Int32 oldValue) {}
		public float bePushedSpeed = 0f;
		
		public float copper = 0f;
		public float dmgArmor = 0f;
		public float expGrow = 0f;
		public Int32 firstHateTargetId = 0;
		
		
		
		
		public float gatherRate = 0f;
		public Byte healHpRatio = 80;
		public Byte healMpRatio = 80;
		
		public float ignoreArmor = 0f;
		
		
		
		public float medicineRate = 0f;
		public float miningRate = 0f;
		
		
		public float mulSpeed = 0f;
		
		public Int32 replicaId = 0;
		public virtual void onReplicaIdChanged(Int32 oldValue) {}
		
		
		
		public Int32 siegeWarCamp = 0;
		
		
		
		
		public Byte summonSlotIdx = 0;
		public Byte ultraSkillPower = 0;


		public AvatarReplicaBase()
		{
		}

		public override void onComponentsEnterworld()
		{
		}

		public override void onComponentsLeaveworld()
		{
		}

		public override void onGetBase()
		{
			baseEntityCall = new EntityBaseEntityCall_AvatarReplicaBase(id, className);
		}

		public override void onGetCell()
		{
			cellEntityCall = new EntityCellEntityCall_AvatarReplicaBase(id, className);
		}

		public override void onLoseCell()
		{
			cellEntityCall = null;
		}

		public override EntityCall getBaseEntityCall()
		{
			return baseEntityCall;
		}

		public override EntityCall getCellEntityCall()
		{
			return cellEntityCall;
		}

		public override void attachComponents()
		{
		}

		public override void detachComponents()
		{
		}

		public override void onRemoteMethodCall(MemoryStream stream)
		{
			ScriptModule sm = EntityDef.moduledefs["AvatarReplica"];

			UInt16 methodUtype = 0;
			UInt16 componentPropertyUType = 0;

			if(sm.usePropertyDescrAlias)
			{
				componentPropertyUType = stream.readUint8();
			}
			else
			{
				componentPropertyUType = stream.readUint16();
			}

			if(sm.useMethodDescrAlias)
			{
				methodUtype = stream.readUint8();
			}
			else
			{
				methodUtype = stream.readUint16();
			}

			Method method = null;

			if(componentPropertyUType == 0)
			{
				method = sm.idmethods[methodUtype];
			}
			else
			{
				Property pComponentPropertyDescription = sm.idpropertys[componentPropertyUType];
				switch(pComponentPropertyDescription.properUtype)
				{
					default:
						break;
				}

				return;
			}

			switch(method.methodUtype)
			{
				case 1099:
					UInt32 aiChatToPlayer_arg1 = stream.readUint32();
					UInt32 aiChatToPlayer_arg2 = stream.readUint32();
					aiChatToPlayer(aiChatToPlayer_arg1, aiChatToPlayer_arg2);
					break;
				case 1149:
					Vector3 drawCube_arg1 = stream.readVector3();
					Vector3 drawCube_arg2 = stream.readVector3();
					float drawCube_arg3 = stream.readFloat();
					float drawCube_arg4 = stream.readFloat();
					drawCube(drawCube_arg1, drawCube_arg2, drawCube_arg3, drawCube_arg4);
					break;
				case 1126:
					UInt32 notifyCastingSkill_arg1 = stream.readUint32();
					double notifyCastingSkill_arg2 = stream.readDouble();
					notifyCastingSkill(notifyCastingSkill_arg1, notifyCastingSkill_arg2);
					break;
				case 1110:
					CLIENT_AUREOLE_VAL onAddAureole_arg1 = ((DATATYPE_CLIENT_AUREOLE_VAL)method.args[0]).createFromStreamEx(stream);
					onAddAureole(onAddAureole_arg1);
					break;
				case 1113:
					CLIENT_AUREOLE_VAL onAddAureoleFromOthers_arg1 = ((DATATYPE_CLIENT_AUREOLE_VAL)method.args[0]).createFromStreamEx(stream);
					onAddAureoleFromOthers(onAddAureoleFromOthers_arg1);
					break;
				case 1120:
					CLIENT_BUFF_VAL onAddBuff_arg1 = ((DATATYPE_CLIENT_BUFF_VAL)method.args[0]).createFromStreamEx(stream);
					onAddBuff(onAddBuff_arg1);
					break;
				case 1104:
					UInt32 onAddPassiveSkill_arg1 = stream.readUint32();
					UInt32 onAddPassiveSkill_arg2 = stream.readUint32();
					onAddPassiveSkill(onAddPassiveSkill_arg1, onAddPassiveSkill_arg2);
					break;
				case 1103:
					UInt32 onAddSkill_arg1 = stream.readUint32();
					UInt32 onAddSkill_arg2 = stream.readUint32();
					Byte onAddSkill_arg3 = stream.readUint8();
					double onAddSkill_arg4 = stream.readDouble();
					float onAddSkill_arg5 = stream.readFloat();
					Byte onAddSkill_arg6 = stream.readUint8();
					onAddSkill(onAddSkill_arg1, onAddSkill_arg2, onAddSkill_arg3, onAddSkill_arg4, onAddSkill_arg5, onAddSkill_arg6);
					break;
				case 1165:
					onBornAction();
					break;
				case 1117:
					Int32 onBreakCastingSkill_arg1 = stream.readInt32();
					UInt32 onBreakCastingSkill_arg2 = stream.readUint32();
					Int32 onBreakCastingSkill_arg3 = stream.readInt32();
					onBreakCastingSkill(onBreakCastingSkill_arg1, onBreakCastingSkill_arg2, onBreakCastingSkill_arg3);
					break;
				case 1118:
					Int32 onBreakChannelingSkill_arg1 = stream.readInt32();
					UInt32 onBreakChannelingSkill_arg2 = stream.readUint32();
					Int32 onBreakChannelingSkill_arg3 = stream.readInt32();
					onBreakChannelingSkill(onBreakChannelingSkill_arg1, onBreakChannelingSkill_arg2, onBreakChannelingSkill_arg3);
					break;
				case 1098:
					Int32 onDead_arg1 = stream.readInt32();
					onDead(onDead_arg1);
					break;
				case 1128:
					Vector3 onExitShiftByConflict_arg1 = stream.readVector3();
					onExitShiftByConflict(onExitShiftByConflict_arg1);
					break;
				case 1124:
					Int32 onGetAureoleInfo_arg1 = stream.readInt32();
					CLIENT_AUREOLES onGetAureoleInfo_arg2 = ((DATATYPE_CLIENT_AUREOLES)method.args[1]).createFromStreamEx(stream);
					onGetAureoleInfo(onGetAureoleInfo_arg1, onGetAureoleInfo_arg2);
					break;
				case 1123:
					Int32 onGetBuffInfo_arg1 = stream.readInt32();
					CLIENT_BUFFS onGetBuffInfo_arg2 = ((DATATYPE_CLIENT_BUFFS)method.args[1]).createFromStreamEx(stream);
					onGetBuffInfo(onGetBuffInfo_arg1, onGetBuffInfo_arg2);
					break;
				case 1116:
					Int32 onMessage_arg1 = stream.readInt32();
					List<string> onMessage_arg2 = ((DATATYPE_AnonymousArray_10001)method.args[1]).createFromStreamEx(stream);
					onMessage(onMessage_arg1, onMessage_arg2);
					break;
				case 1109:
					Int32 onOthersSkillDamage_arg1 = stream.readInt32();
					List<Int32> onOthersSkillDamage_arg2 = ((DATATYPE_AnonymousArray_10004)method.args[1]).createFromStreamEx(stream);
					onOthersSkillDamage(onOthersSkillDamage_arg1, onOthersSkillDamage_arg2);
					break;
				case 1111:
					Int32 onRemoveAureole_arg1 = stream.readInt32();
					onRemoveAureole(onRemoveAureole_arg1);
					break;
				case 1114:
					Int32 onRemoveAureoleFromOthers_arg1 = stream.readInt32();
					onRemoveAureoleFromOthers(onRemoveAureoleFromOthers_arg1);
					break;
				case 1121:
					Int32 onRemoveBuff_arg1 = stream.readInt32();
					List<UInt64> onRemoveBuff_arg2 = ((DATATYPE_AnonymousArray_10006)method.args[1]).createFromStreamEx(stream);
					onRemoveBuff(onRemoveBuff_arg1, onRemoveBuff_arg2);
					break;
				case 1125:
					UInt32 onSetAddSkillCd_arg1 = stream.readUint32();
					float onSetAddSkillCd_arg2 = stream.readFloat();
					double onSetAddSkillCd_arg3 = stream.readDouble();
					Byte onSetAddSkillCd_arg4 = stream.readUint8();
					double onSetAddSkillCd_arg5 = stream.readDouble();
					SByte onSetAddSkillCd_arg6 = stream.readInt8();
					SByte onSetAddSkillCd_arg7 = stream.readInt8();
					Byte onSetAddSkillCd_arg8 = stream.readUint8();
					onSetAddSkillCd(onSetAddSkillCd_arg1, onSetAddSkillCd_arg2, onSetAddSkillCd_arg3, onSetAddSkillCd_arg4, onSetAddSkillCd_arg5, onSetAddSkillCd_arg6, onSetAddSkillCd_arg7, onSetAddSkillCd_arg8);
					break;
				case 1127:
					UInt32 onShooterSkillCanUse_arg1 = stream.readUint32();
					double onShooterSkillCanUse_arg2 = stream.readDouble();
					Byte onShooterSkillCanUse_arg3 = stream.readUint8();
					onShooterSkillCanUse(onShooterSkillCanUse_arg1, onShooterSkillCanUse_arg2, onShooterSkillCanUse_arg3);
					break;
				case 1108:
					SKILL_DAMAGE_INFO onSkillDamage_arg1 = ((DATATYPE_SKILL_DAMAGE_INFO)method.args[0]).createFromStreamEx(stream);
					onSkillDamage(onSkillDamage_arg1);
					break;
				case 1129:
					Byte onStateChangedForce_arg1 = stream.readUint8();
					onStateChangedForce(onStateChangedForce_arg1);
					break;
				case 1112:
					CLIENT_AUREOLES onUpdateAureoles_arg1 = ((DATATYPE_CLIENT_AUREOLES)method.args[0]).createFromStreamEx(stream);
					onUpdateAureoles(onUpdateAureoles_arg1);
					break;
				case 1115:
					AUREOLE_FROM_OTHERS onUpdateAureolesFromOthers_arg1 = ((DATATYPE_AUREOLE_FROM_OTHERS)method.args[0]).createFromStreamEx(stream);
					onUpdateAureolesFromOthers(onUpdateAureolesFromOthers_arg1);
					break;
				case 1122:
					CLIENT_BUFF_VAL onUpdateBuff_arg1 = ((DATATYPE_CLIENT_BUFF_VAL)method.args[0]).createFromStreamEx(stream);
					onUpdateBuff(onUpdateBuff_arg1);
					break;
				case 1119:
					CLIENT_BUFFS onUpdateBuffs_arg1 = ((DATATYPE_CLIENT_BUFFS)method.args[0]).createFromStreamEx(stream);
					onUpdateBuffs(onUpdateBuffs_arg1);
					break;
				case 1106:
					Int32 onUseCasting_arg1 = stream.readInt32();
					UInt32 onUseCasting_arg2 = stream.readUint32();
					Int32 onUseCasting_arg3 = stream.readInt32();
					List<float> onUseCasting_arg4 = ((DATATYPE_AnonymousArray_10009)method.args[3]).createFromStreamEx(stream);
					List<Int32> onUseCasting_arg5 = ((DATATYPE_AnonymousArray_10004)method.args[4]).createFromStreamEx(stream);
					List<float> onUseCasting_arg6 = ((DATATYPE_AnonymousArray_10009)method.args[5]).createFromStreamEx(stream);
					onUseCasting(onUseCasting_arg1, onUseCasting_arg2, onUseCasting_arg3, onUseCasting_arg4, onUseCasting_arg5, onUseCasting_arg6);
					break;
				case 1107:
					Int32 onUseChanneling_arg1 = stream.readInt32();
					UInt32 onUseChanneling_arg2 = stream.readUint32();
					Int32 onUseChanneling_arg3 = stream.readInt32();
					List<float> onUseChanneling_arg4 = ((DATATYPE_AnonymousArray_10009)method.args[3]).createFromStreamEx(stream);
					List<Int32> onUseChanneling_arg5 = ((DATATYPE_AnonymousArray_10004)method.args[4]).createFromStreamEx(stream);
					Int32 onUseChanneling_arg6 = stream.readInt32();
					List<float> onUseChanneling_arg7 = ((DATATYPE_AnonymousArray_10009)method.args[6]).createFromStreamEx(stream);
					onUseChanneling(onUseChanneling_arg1, onUseChanneling_arg2, onUseChanneling_arg3, onUseChanneling_arg4, onUseChanneling_arg5, onUseChanneling_arg6, onUseChanneling_arg7);
					break;
				case 1105:
					Byte onUseSkill_arg1 = stream.readUint8();
					UInt32 onUseSkill_arg2 = stream.readUint32();
					Int32 onUseSkill_arg3 = stream.readInt32();
					List<float> onUseSkill_arg4 = ((DATATYPE_AnonymousArray_10009)method.args[3]).createFromStreamEx(stream);
					List<Int32> onUseSkill_arg5 = ((DATATYPE_AnonymousArray_10004)method.args[4]).createFromStreamEx(stream);
					List<float> onUseSkill_arg6 = ((DATATYPE_AnonymousArray_10009)method.args[5]).createFromStreamEx(stream);
					onUseSkill(onUseSkill_arg1, onUseSkill_arg2, onUseSkill_arg3, onUseSkill_arg4, onUseSkill_arg5, onUseSkill_arg6);
					break;
				case 1155:
					List<UInt16> updateForbidSkillTags_arg1 = ((DATATYPE_AnonymousArray_10005)method.args[0]).createFromStreamEx(stream);
					updateForbidSkillTags(updateForbidSkillTags_arg1);
					break;
				default:
					break;
			};
		}

		public override void onUpdatePropertys(MemoryStream stream)
		{
			ScriptModule sm = EntityDef.moduledefs["AvatarReplica"];
			Dictionary<UInt16, Property> pdatas = sm.idpropertys;

			while(stream.length() > 0)
			{
				UInt16 _t_utype = 0;
				{
					if(sm.usePropertyDescrAlias)
					{
						_t_utype = stream.readUint8();
					}
					else
					{
						_t_utype = stream.readUint16();
					}
				}

				Property prop = null;

				if(_t_utype != 0)
				{
					prop = pdatas[_t_utype];
				}
				else
				{
					Property pComponentPropertyDescription = pdatas[_t_utype];
					switch(pComponentPropertyDescription.properUtype)
					{
						default:
							break;
					}

					return;
				}

				switch(prop.properUtype)
				{
					case 461:
						float oldval_adjCD = adjCD;
						adjCD = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onAdjCDChanged(oldval_adjCD);
						}
						else
						{
							if(inWorld)
								onAdjCDChanged(oldval_adjCD);
						}

						break;
					case 493:
						Int32 oldval_antiFatal = antiFatal;
						antiFatal = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onAntiFatalChanged(oldval_antiFatal);
						}
						else
						{
							if(inWorld)
								onAntiFatalChanged(oldval_antiFatal);
						}

						break;
					case 366:
						APPEARANCE_INFO oldval_appearance = appearance;
						appearance = ((DATATYPE_APPEARANCE_INFO)EntityDef.id2datatypes[35]).createFromStreamEx(stream);

						if(prop.isBase())
						{
							if(inited)
								onAppearanceChanged(oldval_appearance);
						}
						else
						{
							if(inWorld)
								onAppearanceChanged(oldval_appearance);
						}

						break;
					case 358:
						Byte oldval_arType = arType;
						arType = stream.readUint8();

						if(prop.isBase())
						{
							if(inited)
								onArTypeChanged(oldval_arType);
						}
						else
						{
							if(inWorld)
								onArTypeChanged(oldval_arType);
						}

						break;
					case 347:
						Int32 oldval_avatarId = avatarId;
						avatarId = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onAvatarIdChanged(oldval_avatarId);
						}
						else
						{
							if(inWorld)
								onAvatarIdChanged(oldval_avatarId);
						}

						break;
					case 504:
						float oldval_bePushedSpeed = bePushedSpeed;
						bePushedSpeed = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onBePushedSpeedChanged(oldval_bePushedSpeed);
						}
						else
						{
							if(inWorld)
								onBePushedSpeedChanged(oldval_bePushedSpeed);
						}

						break;
					case 386:
						Byte oldval_bornState = bornState;
						bornState = stream.readUint8();

						if(prop.isBase())
						{
							if(inited)
								onBornStateChanged(oldval_bornState);
						}
						else
						{
							if(inWorld)
								onBornStateChanged(oldval_bornState);
						}

						break;
					case 643:
						float oldval_copper = copper;
						copper = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onCopperChanged(oldval_copper);
						}
						else
						{
							if(inWorld)
								onCopperChanged(oldval_copper);
						}

						break;
					case 40001:
						Vector3 oldval_direction = direction;
						direction = stream.readVector3();

						if(prop.isBase())
						{
							if(inited)
								onDirectionChanged(oldval_direction);
						}
						else
						{
							if(inWorld)
								onDirectionChanged(oldval_direction);
						}

						break;
					case 502:
						float oldval_dmgArmor = dmgArmor;
						dmgArmor = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onDmgArmorChanged(oldval_dmgArmor);
						}
						else
						{
							if(inWorld)
								onDmgArmorChanged(oldval_dmgArmor);
						}

						break;
					case 642:
						float oldval_expGrow = expGrow;
						expGrow = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onExpGrowChanged(oldval_expGrow);
						}
						else
						{
							if(inWorld)
								onExpGrowChanged(oldval_expGrow);
						}

						break;
					case 388:
						Int32 oldval_firstHateTargetId = firstHateTargetId;
						firstHateTargetId = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onFirstHateTargetIdChanged(oldval_firstHateTargetId);
						}
						else
						{
							if(inWorld)
								onFirstHateTargetIdChanged(oldval_firstHateTargetId);
						}

						break;
					case 547:
						Int32 oldval_force = force;
						force = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onForceChanged(oldval_force);
						}
						else
						{
							if(inWorld)
								onForceChanged(oldval_force);
						}

						break;
					case 433:
						Int32 oldval_fullHp = fullHp;
						fullHp = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onFullHpChanged(oldval_fullHp);
						}
						else
						{
							if(inWorld)
								onFullHpChanged(oldval_fullHp);
						}

						break;
					case 458:
						Int32 oldval_fullMp = fullMp;
						fullMp = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onFullMpChanged(oldval_fullMp);
						}
						else
						{
							if(inWorld)
								onFullMpChanged(oldval_fullMp);
						}

						break;
					case 551:
						Int64 oldval_gameEntityId = gameEntityId;
						gameEntityId = stream.readInt64();

						if(prop.isBase())
						{
							if(inited)
								onGameEntityIdChanged(oldval_gameEntityId);
						}
						else
						{
							if(inWorld)
								onGameEntityIdChanged(oldval_gameEntityId);
						}

						break;
					case 646:
						float oldval_gatherRate = gatherRate;
						gatherRate = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onGatherRateChanged(oldval_gatherRate);
						}
						else
						{
							if(inWorld)
								onGatherRateChanged(oldval_gatherRate);
						}

						break;
					case 635:
						Byte oldval_healHpRatio = healHpRatio;
						healHpRatio = stream.readUint8();

						if(prop.isBase())
						{
							if(inited)
								onHealHpRatioChanged(oldval_healHpRatio);
						}
						else
						{
							if(inWorld)
								onHealHpRatioChanged(oldval_healHpRatio);
						}

						break;
					case 641:
						Byte oldval_healMpRatio = healMpRatio;
						healMpRatio = stream.readUint8();

						if(prop.isBase())
						{
							if(inited)
								onHealMpRatioChanged(oldval_healMpRatio);
						}
						else
						{
							if(inWorld)
								onHealMpRatioChanged(oldval_healMpRatio);
						}

						break;
					case 440:
						Int32 oldval_hp = hp;
						hp = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onHpChanged(oldval_hp);
						}
						else
						{
							if(inWorld)
								onHpChanged(oldval_hp);
						}

						break;
					case 501:
						float oldval_ignoreArmor = ignoreArmor;
						ignoreArmor = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onIgnoreArmorChanged(oldval_ignoreArmor);
						}
						else
						{
							if(inWorld)
								onIgnoreArmorChanged(oldval_ignoreArmor);
						}

						break;
					case 377:
						Byte oldval_isBoss = isBoss;
						isBoss = stream.readUint8();

						if(prop.isBase())
						{
							if(inited)
								onIsBossChanged(oldval_isBoss);
						}
						else
						{
							if(inWorld)
								onIsBossChanged(oldval_isBoss);
						}

						break;
					case 392:
						Byte oldval_isWitnessComplete = isWitnessComplete;
						isWitnessComplete = stream.readUint8();

						if(prop.isBase())
						{
							if(inited)
								onIsWitnessCompleteChanged(oldval_isWitnessComplete);
						}
						else
						{
							if(inWorld)
								onIsWitnessCompleteChanged(oldval_isWitnessComplete);
						}

						break;
					case 406:
						UInt32 oldval_level = level;
						level = stream.readUint32();

						if(prop.isBase())
						{
							if(inited)
								onLevelChanged(oldval_level);
						}
						else
						{
							if(inWorld)
								onLevelChanged(oldval_level);
						}

						break;
					case 644:
						float oldval_medicineRate = medicineRate;
						medicineRate = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onMedicineRateChanged(oldval_medicineRate);
						}
						else
						{
							if(inWorld)
								onMedicineRateChanged(oldval_medicineRate);
						}

						break;
					case 645:
						float oldval_miningRate = miningRate;
						miningRate = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onMiningRateChanged(oldval_miningRate);
						}
						else
						{
							if(inWorld)
								onMiningRateChanged(oldval_miningRate);
						}

						break;
					case 634:
						Int32 oldval_mp = mp;
						mp = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onMpChanged(oldval_mp);
						}
						else
						{
							if(inWorld)
								onMpChanged(oldval_mp);
						}

						break;
					case 462:
						float oldval_mulCD = mulCD;
						mulCD = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onMulCDChanged(oldval_mulCD);
						}
						else
						{
							if(inWorld)
								onMulCDChanged(oldval_mulCD);
						}

						break;
					case 525:
						float oldval_mulSpeed = mulSpeed;
						mulSpeed = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onMulSpeedChanged(oldval_mulSpeed);
						}
						else
						{
							if(inWorld)
								onMulSpeedChanged(oldval_mulSpeed);
						}

						break;
					case 361:
						string oldval_name = name;
						name = stream.readUnicode();

						if(prop.isBase())
						{
							if(inited)
								onNameChanged(oldval_name);
						}
						else
						{
							if(inWorld)
								onNameChanged(oldval_name);
						}

						break;
					case 40000:
						Vector3 oldval_position = position;
						position = stream.readVector3();

						if(prop.isBase())
						{
							if(inited)
								onPositionChanged(oldval_position);
						}
						else
						{
							if(inWorld)
								onPositionChanged(oldval_position);
						}

						break;
					case 357:
						Int32 oldval_replicaId = replicaId;
						replicaId = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onReplicaIdChanged(oldval_replicaId);
						}
						else
						{
							if(inWorld)
								onReplicaIdChanged(oldval_replicaId);
						}

						break;
					case 362:
						UInt16 oldval_school = school;
						school = stream.readUint16();

						if(prop.isBase())
						{
							if(inited)
								onSchoolChanged(oldval_school);
						}
						else
						{
							if(inWorld)
								onSchoolChanged(oldval_school);
						}

						break;
					case 528:
						Int32 oldval_selectedTargetId = selectedTargetId;
						selectedTargetId = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onSelectedTargetIdChanged(oldval_selectedTargetId);
						}
						else
						{
							if(inWorld)
								onSelectedTargetIdChanged(oldval_selectedTargetId);
						}

						break;
					case 364:
						Byte oldval_sex = sex;
						sex = stream.readUint8();

						if(prop.isBase())
						{
							if(inited)
								onSexChanged(oldval_sex);
						}
						else
						{
							if(inWorld)
								onSexChanged(oldval_sex);
						}

						break;
					case 562:
						Int32 oldval_siegeWarCamp = siegeWarCamp;
						siegeWarCamp = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onSiegeWarCampChanged(oldval_siegeWarCamp);
						}
						else
						{
							if(inWorld)
								onSiegeWarCampChanged(oldval_siegeWarCamp);
						}

						break;
					case 40002:
						stream.readUint32();
						break;
					case 529:
						UInt32 oldval_spaceNo = spaceNo;
						oldSpaceNo = oldval_spaceNo;
						spaceNo = stream.readUint32();

						if(prop.isBase())
						{
							if(inited)
								onSpaceNoChanged(oldval_spaceNo);
						}
						else
						{
							if(inWorld)
								onSpaceNoChanged(oldval_spaceNo);
						}

						break;
					case 505:
						float oldval_speed = speed;
						speed = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onSpeedChanged(oldval_speed);
						}
						else
						{
							if(inWorld)
								onSpeedChanged(oldval_speed);
						}

						break;
					case 407:
						Int64 oldval_state = state;
						state = stream.readInt64();

						if(prop.isBase())
						{
							if(inited)
								onStateChanged(oldval_state);
						}
						else
						{
							if(inWorld)
								onStateChanged(oldval_state);
						}

						break;
					case 412:
						Int64 oldval_state2 = state2;
						state2 = stream.readInt64();

						if(prop.isBase())
						{
							if(inited)
								onState2Changed(oldval_state2);
						}
						else
						{
							if(inWorld)
								onState2Changed(oldval_state2);
						}

						break;
					case 31364:
						Byte oldval_summonSlotIdx = summonSlotIdx;
						summonSlotIdx = stream.readUint8();

						if(prop.isBase())
						{
							if(inited)
								onSummonSlotIdxChanged(oldval_summonSlotIdx);
						}
						else
						{
							if(inWorld)
								onSummonSlotIdxChanged(oldval_summonSlotIdx);
						}

						break;
					case 31729:
						Byte oldval_ultraSkillPower = ultraSkillPower;
						ultraSkillPower = stream.readUint8();

						if(prop.isBase())
						{
							if(inited)
								onUltraSkillPowerChanged(oldval_ultraSkillPower);
						}
						else
						{
							if(inWorld)
								onUltraSkillPowerChanged(oldval_ultraSkillPower);
						}

						break;
					default:
						break;
				};
			}
		}

		public override void callPropertysSetMethods()
		{
			ScriptModule sm = EntityDef.moduledefs["AvatarReplica"];
			Dictionary<UInt16, Property> pdatas = sm.idpropertys;

			float oldval_adjCD = adjCD;
			Property prop_adjCD = pdatas[4];
			if(prop_adjCD.isBase())
			{
				if(inited && !inWorld)
					onAdjCDChanged(oldval_adjCD);
			}
			else
			{
				if(inWorld)
				{
					if(prop_adjCD.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onAdjCDChanged(oldval_adjCD);
					}
				}
			}

			Int32 oldval_antiFatal = antiFatal;
			Property prop_antiFatal = pdatas[5];
			if(prop_antiFatal.isBase())
			{
				if(inited && !inWorld)
					onAntiFatalChanged(oldval_antiFatal);
			}
			else
			{
				if(inWorld)
				{
					if(prop_antiFatal.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onAntiFatalChanged(oldval_antiFatal);
					}
				}
			}

			APPEARANCE_INFO oldval_appearance = appearance;
			Property prop_appearance = pdatas[6];
			if(prop_appearance.isBase())
			{
				if(inited && !inWorld)
					onAppearanceChanged(oldval_appearance);
			}
			else
			{
				if(inWorld)
				{
					if(prop_appearance.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onAppearanceChanged(oldval_appearance);
					}
				}
			}

			Byte oldval_arType = arType;
			Property prop_arType = pdatas[7];
			if(prop_arType.isBase())
			{
				if(inited && !inWorld)
					onArTypeChanged(oldval_arType);
			}
			else
			{
				if(inWorld)
				{
					if(prop_arType.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onArTypeChanged(oldval_arType);
					}
				}
			}

			Int32 oldval_avatarId = avatarId;
			Property prop_avatarId = pdatas[8];
			if(prop_avatarId.isBase())
			{
				if(inited && !inWorld)
					onAvatarIdChanged(oldval_avatarId);
			}
			else
			{
				if(inWorld)
				{
					if(prop_avatarId.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onAvatarIdChanged(oldval_avatarId);
					}
				}
			}

			float oldval_bePushedSpeed = bePushedSpeed;
			Property prop_bePushedSpeed = pdatas[9];
			if(prop_bePushedSpeed.isBase())
			{
				if(inited && !inWorld)
					onBePushedSpeedChanged(oldval_bePushedSpeed);
			}
			else
			{
				if(inWorld)
				{
					if(prop_bePushedSpeed.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onBePushedSpeedChanged(oldval_bePushedSpeed);
					}
				}
			}

			Byte oldval_bornState = bornState;
			Property prop_bornState = pdatas[10];
			if(prop_bornState.isBase())
			{
				if(inited && !inWorld)
					onBornStateChanged(oldval_bornState);
			}
			else
			{
				if(inWorld)
				{
					if(prop_bornState.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onBornStateChanged(oldval_bornState);
					}
				}
			}

			float oldval_copper = copper;
			Property prop_copper = pdatas[34];
			if(prop_copper.isBase())
			{
				if(inited && !inWorld)
					onCopperChanged(oldval_copper);
			}
			else
			{
				if(inWorld)
				{
					if(prop_copper.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onCopperChanged(oldval_copper);
					}
				}
			}

			Vector3 oldval_direction = direction;
			Property prop_direction = pdatas[2];
			if(prop_direction.isBase())
			{
				if(inited && !inWorld)
					onDirectionChanged(oldval_direction);
			}
			else
			{
				if(inWorld)
				{
					if(prop_direction.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onDirectionChanged(oldval_direction);
					}
				}
			}

			float oldval_dmgArmor = dmgArmor;
			Property prop_dmgArmor = pdatas[11];
			if(prop_dmgArmor.isBase())
			{
				if(inited && !inWorld)
					onDmgArmorChanged(oldval_dmgArmor);
			}
			else
			{
				if(inWorld)
				{
					if(prop_dmgArmor.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onDmgArmorChanged(oldval_dmgArmor);
					}
				}
			}

			float oldval_expGrow = expGrow;
			Property prop_expGrow = pdatas[35];
			if(prop_expGrow.isBase())
			{
				if(inited && !inWorld)
					onExpGrowChanged(oldval_expGrow);
			}
			else
			{
				if(inWorld)
				{
					if(prop_expGrow.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onExpGrowChanged(oldval_expGrow);
					}
				}
			}

			Int32 oldval_firstHateTargetId = firstHateTargetId;
			Property prop_firstHateTargetId = pdatas[12];
			if(prop_firstHateTargetId.isBase())
			{
				if(inited && !inWorld)
					onFirstHateTargetIdChanged(oldval_firstHateTargetId);
			}
			else
			{
				if(inWorld)
				{
					if(prop_firstHateTargetId.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onFirstHateTargetIdChanged(oldval_firstHateTargetId);
					}
				}
			}

			Int32 oldval_force = force;
			Property prop_force = pdatas[13];
			if(prop_force.isBase())
			{
				if(inited && !inWorld)
					onForceChanged(oldval_force);
			}
			else
			{
				if(inWorld)
				{
					if(prop_force.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onForceChanged(oldval_force);
					}
				}
			}

			Int32 oldval_fullHp = fullHp;
			Property prop_fullHp = pdatas[14];
			if(prop_fullHp.isBase())
			{
				if(inited && !inWorld)
					onFullHpChanged(oldval_fullHp);
			}
			else
			{
				if(inWorld)
				{
					if(prop_fullHp.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onFullHpChanged(oldval_fullHp);
					}
				}
			}

			Int32 oldval_fullMp = fullMp;
			Property prop_fullMp = pdatas[15];
			if(prop_fullMp.isBase())
			{
				if(inited && !inWorld)
					onFullMpChanged(oldval_fullMp);
			}
			else
			{
				if(inWorld)
				{
					if(prop_fullMp.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onFullMpChanged(oldval_fullMp);
					}
				}
			}

			Int64 oldval_gameEntityId = gameEntityId;
			Property prop_gameEntityId = pdatas[16];
			if(prop_gameEntityId.isBase())
			{
				if(inited && !inWorld)
					onGameEntityIdChanged(oldval_gameEntityId);
			}
			else
			{
				if(inWorld)
				{
					if(prop_gameEntityId.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onGameEntityIdChanged(oldval_gameEntityId);
					}
				}
			}

			float oldval_gatherRate = gatherRate;
			Property prop_gatherRate = pdatas[36];
			if(prop_gatherRate.isBase())
			{
				if(inited && !inWorld)
					onGatherRateChanged(oldval_gatherRate);
			}
			else
			{
				if(inWorld)
				{
					if(prop_gatherRate.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onGatherRateChanged(oldval_gatherRate);
					}
				}
			}

			Byte oldval_healHpRatio = healHpRatio;
			Property prop_healHpRatio = pdatas[37];
			if(prop_healHpRatio.isBase())
			{
				if(inited && !inWorld)
					onHealHpRatioChanged(oldval_healHpRatio);
			}
			else
			{
				if(inWorld)
				{
					if(prop_healHpRatio.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onHealHpRatioChanged(oldval_healHpRatio);
					}
				}
			}

			Byte oldval_healMpRatio = healMpRatio;
			Property prop_healMpRatio = pdatas[38];
			if(prop_healMpRatio.isBase())
			{
				if(inited && !inWorld)
					onHealMpRatioChanged(oldval_healMpRatio);
			}
			else
			{
				if(inWorld)
				{
					if(prop_healMpRatio.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onHealMpRatioChanged(oldval_healMpRatio);
					}
				}
			}

			Int32 oldval_hp = hp;
			Property prop_hp = pdatas[17];
			if(prop_hp.isBase())
			{
				if(inited && !inWorld)
					onHpChanged(oldval_hp);
			}
			else
			{
				if(inWorld)
				{
					if(prop_hp.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onHpChanged(oldval_hp);
					}
				}
			}

			float oldval_ignoreArmor = ignoreArmor;
			Property prop_ignoreArmor = pdatas[18];
			if(prop_ignoreArmor.isBase())
			{
				if(inited && !inWorld)
					onIgnoreArmorChanged(oldval_ignoreArmor);
			}
			else
			{
				if(inWorld)
				{
					if(prop_ignoreArmor.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onIgnoreArmorChanged(oldval_ignoreArmor);
					}
				}
			}

			Byte oldval_isBoss = isBoss;
			Property prop_isBoss = pdatas[19];
			if(prop_isBoss.isBase())
			{
				if(inited && !inWorld)
					onIsBossChanged(oldval_isBoss);
			}
			else
			{
				if(inWorld)
				{
					if(prop_isBoss.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onIsBossChanged(oldval_isBoss);
					}
				}
			}

			Byte oldval_isWitnessComplete = isWitnessComplete;
			Property prop_isWitnessComplete = pdatas[20];
			if(prop_isWitnessComplete.isBase())
			{
				if(inited && !inWorld)
					onIsWitnessCompleteChanged(oldval_isWitnessComplete);
			}
			else
			{
				if(inWorld)
				{
					if(prop_isWitnessComplete.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onIsWitnessCompleteChanged(oldval_isWitnessComplete);
					}
				}
			}

			UInt32 oldval_level = level;
			Property prop_level = pdatas[21];
			if(prop_level.isBase())
			{
				if(inited && !inWorld)
					onLevelChanged(oldval_level);
			}
			else
			{
				if(inWorld)
				{
					if(prop_level.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onLevelChanged(oldval_level);
					}
				}
			}

			float oldval_medicineRate = medicineRate;
			Property prop_medicineRate = pdatas[39];
			if(prop_medicineRate.isBase())
			{
				if(inited && !inWorld)
					onMedicineRateChanged(oldval_medicineRate);
			}
			else
			{
				if(inWorld)
				{
					if(prop_medicineRate.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onMedicineRateChanged(oldval_medicineRate);
					}
				}
			}

			float oldval_miningRate = miningRate;
			Property prop_miningRate = pdatas[40];
			if(prop_miningRate.isBase())
			{
				if(inited && !inWorld)
					onMiningRateChanged(oldval_miningRate);
			}
			else
			{
				if(inWorld)
				{
					if(prop_miningRate.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onMiningRateChanged(oldval_miningRate);
					}
				}
			}

			Int32 oldval_mp = mp;
			Property prop_mp = pdatas[41];
			if(prop_mp.isBase())
			{
				if(inited && !inWorld)
					onMpChanged(oldval_mp);
			}
			else
			{
				if(inWorld)
				{
					if(prop_mp.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onMpChanged(oldval_mp);
					}
				}
			}

			float oldval_mulCD = mulCD;
			Property prop_mulCD = pdatas[22];
			if(prop_mulCD.isBase())
			{
				if(inited && !inWorld)
					onMulCDChanged(oldval_mulCD);
			}
			else
			{
				if(inWorld)
				{
					if(prop_mulCD.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onMulCDChanged(oldval_mulCD);
					}
				}
			}

			float oldval_mulSpeed = mulSpeed;
			Property prop_mulSpeed = pdatas[23];
			if(prop_mulSpeed.isBase())
			{
				if(inited && !inWorld)
					onMulSpeedChanged(oldval_mulSpeed);
			}
			else
			{
				if(inWorld)
				{
					if(prop_mulSpeed.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onMulSpeedChanged(oldval_mulSpeed);
					}
				}
			}

			string oldval_name = name;
			Property prop_name = pdatas[24];
			if(prop_name.isBase())
			{
				if(inited && !inWorld)
					onNameChanged(oldval_name);
			}
			else
			{
				if(inWorld)
				{
					if(prop_name.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onNameChanged(oldval_name);
					}
				}
			}

			Vector3 oldval_position = position;
			Property prop_position = pdatas[1];
			if(prop_position.isBase())
			{
				if(inited && !inWorld)
					onPositionChanged(oldval_position);
			}
			else
			{
				if(inWorld)
				{
					if(prop_position.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onPositionChanged(oldval_position);
					}
				}
			}

			Int32 oldval_replicaId = replicaId;
			Property prop_replicaId = pdatas[25];
			if(prop_replicaId.isBase())
			{
				if(inited && !inWorld)
					onReplicaIdChanged(oldval_replicaId);
			}
			else
			{
				if(inWorld)
				{
					if(prop_replicaId.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onReplicaIdChanged(oldval_replicaId);
					}
				}
			}

			UInt16 oldval_school = school;
			Property prop_school = pdatas[26];
			if(prop_school.isBase())
			{
				if(inited && !inWorld)
					onSchoolChanged(oldval_school);
			}
			else
			{
				if(inWorld)
				{
					if(prop_school.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onSchoolChanged(oldval_school);
					}
				}
			}

			Int32 oldval_selectedTargetId = selectedTargetId;
			Property prop_selectedTargetId = pdatas[27];
			if(prop_selectedTargetId.isBase())
			{
				if(inited && !inWorld)
					onSelectedTargetIdChanged(oldval_selectedTargetId);
			}
			else
			{
				if(inWorld)
				{
					if(prop_selectedTargetId.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onSelectedTargetIdChanged(oldval_selectedTargetId);
					}
				}
			}

			Byte oldval_sex = sex;
			Property prop_sex = pdatas[28];
			if(prop_sex.isBase())
			{
				if(inited && !inWorld)
					onSexChanged(oldval_sex);
			}
			else
			{
				if(inWorld)
				{
					if(prop_sex.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onSexChanged(oldval_sex);
					}
				}
			}

			Int32 oldval_siegeWarCamp = siegeWarCamp;
			Property prop_siegeWarCamp = pdatas[33];
			if(prop_siegeWarCamp.isBase())
			{
				if(inited && !inWorld)
					onSiegeWarCampChanged(oldval_siegeWarCamp);
			}
			else
			{
				if(inWorld)
				{
					if(prop_siegeWarCamp.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onSiegeWarCampChanged(oldval_siegeWarCamp);
					}
				}
			}

			UInt32 oldval_spaceNo = spaceNo;
			Property prop_spaceNo = pdatas[29];
			if(prop_spaceNo.isBase())
			{
				if(inited && !inWorld)
					onSpaceNoChanged(oldval_spaceNo);
			}
			else
			{
				if(inWorld)
				{
					if(prop_spaceNo.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onSpaceNoChanged(oldval_spaceNo);
					}
				}
			}

			float oldval_speed = speed;
			Property prop_speed = pdatas[30];
			if(prop_speed.isBase())
			{
				if(inited && !inWorld)
					onSpeedChanged(oldval_speed);
			}
			else
			{
				if(inWorld)
				{
					if(prop_speed.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onSpeedChanged(oldval_speed);
					}
				}
			}

			Int64 oldval_state = state;
			Property prop_state = pdatas[31];
			if(prop_state.isBase())
			{
				if(inited && !inWorld)
					onStateChanged(oldval_state);
			}
			else
			{
				if(inWorld)
				{
					if(prop_state.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onStateChanged(oldval_state);
					}
				}
			}

			Int64 oldval_state2 = state2;
			Property prop_state2 = pdatas[32];
			if(prop_state2.isBase())
			{
				if(inited && !inWorld)
					onState2Changed(oldval_state2);
			}
			else
			{
				if(inWorld)
				{
					if(prop_state2.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onState2Changed(oldval_state2);
					}
				}
			}

			Byte oldval_summonSlotIdx = summonSlotIdx;
			Property prop_summonSlotIdx = pdatas[42];
			if(prop_summonSlotIdx.isBase())
			{
				if(inited && !inWorld)
					onSummonSlotIdxChanged(oldval_summonSlotIdx);
			}
			else
			{
				if(inWorld)
				{
					if(prop_summonSlotIdx.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onSummonSlotIdxChanged(oldval_summonSlotIdx);
					}
				}
			}

			Byte oldval_ultraSkillPower = ultraSkillPower;
			Property prop_ultraSkillPower = pdatas[43];
			if(prop_ultraSkillPower.isBase())
			{
				if(inited && !inWorld)
					onUltraSkillPowerChanged(oldval_ultraSkillPower);
			}
			else
			{
				if(inWorld)
				{
					if(prop_ultraSkillPower.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onUltraSkillPowerChanged(oldval_ultraSkillPower);
					}
				}
			}

		}
	}
}