/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class CityBattleTeleporter : CityBattleTeleporterBase)
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/CityBattleTeleporter.def
	// Please inherit and implement "class CityBattleTeleporter : CityBattleTeleporterBase"
	public abstract class CityBattleTeleporterBase : ModelEntity
	{
		public EntityBaseEntityCall_CityBattleTeleporterBase baseEntityCall = null;
		public EntityCellEntityCall_CityBattleTeleporterBase cellEntityCall = null;

		public Int32 CBTimes = 0;
		public virtual void onCBTimesChanged(Int32 oldValue) {}
		
		
		
		
		


		public CityBattleTeleporterBase()
		{
		}

		public override void onComponentsEnterworld()
		{
		}

		public override void onComponentsLeaveworld()
		{
		}

		public override void onGetBase()
		{
			baseEntityCall = new EntityBaseEntityCall_CityBattleTeleporterBase(id, className);
		}

		public override void onGetCell()
		{
			cellEntityCall = new EntityCellEntityCall_CityBattleTeleporterBase(id, className);
		}

		public override void onLoseCell()
		{
			cellEntityCall = null;
		}

		public override EntityCall getBaseEntityCall()
		{
			return baseEntityCall;
		}

		public override EntityCall getCellEntityCall()
		{
			return cellEntityCall;
		}

		public override void attachComponents()
		{
		}

		public override void detachComponents()
		{
		}

		public override void onRemoteMethodCall(MemoryStream stream)
		{
			ScriptModule sm = EntityDef.moduledefs["CityBattleTeleporter"];

			UInt16 methodUtype = 0;
			UInt16 componentPropertyUType = 0;

			if(sm.usePropertyDescrAlias)
			{
				componentPropertyUType = stream.readUint8();
			}
			else
			{
				componentPropertyUType = stream.readUint16();
			}

			if(sm.useMethodDescrAlias)
			{
				methodUtype = stream.readUint8();
			}
			else
			{
				methodUtype = stream.readUint16();
			}

			Method method = null;

			if(componentPropertyUType == 0)
			{
				method = sm.idmethods[methodUtype];
			}
			else
			{
				Property pComponentPropertyDescription = sm.idpropertys[componentPropertyUType];
				switch(pComponentPropertyDescription.properUtype)
				{
					default:
						break;
				}

				return;
			}

			switch(method.methodUtype)
			{
				default:
					break;
			};
		}

		public override void onUpdatePropertys(MemoryStream stream)
		{
			ScriptModule sm = EntityDef.moduledefs["CityBattleTeleporter"];
			Dictionary<UInt16, Property> pdatas = sm.idpropertys;

			while(stream.length() > 0)
			{
				UInt16 _t_utype = 0;
				{
					if(sm.usePropertyDescrAlias)
					{
						_t_utype = stream.readUint8();
					}
					else
					{
						_t_utype = stream.readUint16();
					}
				}

				Property prop = null;

				if(_t_utype != 0)
				{
					prop = pdatas[_t_utype];
				}
				else
				{
					Property pComponentPropertyDescription = pdatas[_t_utype];
					switch(pComponentPropertyDescription.properUtype)
					{
						default:
							break;
					}

					return;
				}

				switch(prop.properUtype)
				{
					case 230:
						Int32 oldval_CBTimes = CBTimes;
						CBTimes = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onCBTimesChanged(oldval_CBTimes);
						}
						else
						{
							if(inWorld)
								onCBTimesChanged(oldval_CBTimes);
						}

						break;
					case 40001:
						Vector3 oldval_direction = direction;
						direction = stream.readVector3();

						if(prop.isBase())
						{
							if(inited)
								onDirectionChanged(oldval_direction);
						}
						else
						{
							if(inWorld)
								onDirectionChanged(oldval_direction);
						}

						break;
					case 156:
						Byte oldval_dunTimeFreezeFlag = dunTimeFreezeFlag;
						dunTimeFreezeFlag = stream.readUint8();

						if(prop.isBase())
						{
							if(inited)
								onDunTimeFreezeFlagChanged(oldval_dunTimeFreezeFlag);
						}
						else
						{
							if(inWorld)
								onDunTimeFreezeFlagChanged(oldval_dunTimeFreezeFlag);
						}

						break;
					case 152:
						Int32 oldval_force = force;
						force = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onForceChanged(oldval_force);
						}
						else
						{
							if(inWorld)
								onForceChanged(oldval_force);
						}

						break;
					case 153:
						Int64 oldval_gameEntityId = gameEntityId;
						gameEntityId = stream.readInt64();

						if(prop.isBase())
						{
							if(inited)
								onGameEntityIdChanged(oldval_gameEntityId);
						}
						else
						{
							if(inWorld)
								onGameEntityIdChanged(oldval_gameEntityId);
						}

						break;
					case 40000:
						Vector3 oldval_position = position;
						position = stream.readVector3();

						if(prop.isBase())
						{
							if(inited)
								onPositionChanged(oldval_position);
						}
						else
						{
							if(inWorld)
								onPositionChanged(oldval_position);
						}

						break;
					case 40002:
						stream.readUint32();
						break;
					case 151:
						UInt32 oldval_spaceNo = spaceNo;
						oldSpaceNo = oldval_spaceNo;
						spaceNo = stream.readUint32();

						if(prop.isBase())
						{
							if(inited)
								onSpaceNoChanged(oldval_spaceNo);
						}
						else
						{
							if(inWorld)
								onSpaceNoChanged(oldval_spaceNo);
						}

						break;
					case 31858:
						Int32 oldval_teleporterId = teleporterId;
						teleporterId = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onTeleporterIdChanged(oldval_teleporterId);
						}
						else
						{
							if(inWorld)
								onTeleporterIdChanged(oldval_teleporterId);
						}

						break;
					default:
						break;
				};
			}
		}

		public override void callPropertysSetMethods()
		{
			ScriptModule sm = EntityDef.moduledefs["CityBattleTeleporter"];
			Dictionary<UInt16, Property> pdatas = sm.idpropertys;

			Int32 oldval_CBTimes = CBTimes;
			Property prop_CBTimes = pdatas[9];
			if(prop_CBTimes.isBase())
			{
				if(inited && !inWorld)
					onCBTimesChanged(oldval_CBTimes);
			}
			else
			{
				if(inWorld)
				{
					if(prop_CBTimes.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onCBTimesChanged(oldval_CBTimes);
					}
				}
			}

			Vector3 oldval_direction = direction;
			Property prop_direction = pdatas[2];
			if(prop_direction.isBase())
			{
				if(inited && !inWorld)
					onDirectionChanged(oldval_direction);
			}
			else
			{
				if(inWorld)
				{
					if(prop_direction.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onDirectionChanged(oldval_direction);
					}
				}
			}

			Byte oldval_dunTimeFreezeFlag = dunTimeFreezeFlag;
			Property prop_dunTimeFreezeFlag = pdatas[4];
			if(prop_dunTimeFreezeFlag.isBase())
			{
				if(inited && !inWorld)
					onDunTimeFreezeFlagChanged(oldval_dunTimeFreezeFlag);
			}
			else
			{
				if(inWorld)
				{
					if(prop_dunTimeFreezeFlag.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onDunTimeFreezeFlagChanged(oldval_dunTimeFreezeFlag);
					}
				}
			}

			Int32 oldval_force = force;
			Property prop_force = pdatas[5];
			if(prop_force.isBase())
			{
				if(inited && !inWorld)
					onForceChanged(oldval_force);
			}
			else
			{
				if(inWorld)
				{
					if(prop_force.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onForceChanged(oldval_force);
					}
				}
			}

			Int64 oldval_gameEntityId = gameEntityId;
			Property prop_gameEntityId = pdatas[6];
			if(prop_gameEntityId.isBase())
			{
				if(inited && !inWorld)
					onGameEntityIdChanged(oldval_gameEntityId);
			}
			else
			{
				if(inWorld)
				{
					if(prop_gameEntityId.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onGameEntityIdChanged(oldval_gameEntityId);
					}
				}
			}

			Vector3 oldval_position = position;
			Property prop_position = pdatas[1];
			if(prop_position.isBase())
			{
				if(inited && !inWorld)
					onPositionChanged(oldval_position);
			}
			else
			{
				if(inWorld)
				{
					if(prop_position.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onPositionChanged(oldval_position);
					}
				}
			}

			UInt32 oldval_spaceNo = spaceNo;
			Property prop_spaceNo = pdatas[8];
			if(prop_spaceNo.isBase())
			{
				if(inited && !inWorld)
					onSpaceNoChanged(oldval_spaceNo);
			}
			else
			{
				if(inWorld)
				{
					if(prop_spaceNo.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onSpaceNoChanged(oldval_spaceNo);
					}
				}
			}

			Int32 oldval_teleporterId = teleporterId;
			Property prop_teleporterId = pdatas[7];
			if(prop_teleporterId.isBase())
			{
				if(inited && !inWorld)
					onTeleporterIdChanged(oldval_teleporterId);
			}
			else
			{
				if(inWorld)
				{
					if(prop_teleporterId.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onTeleporterIdChanged(oldval_teleporterId);
					}
				}
			}

		}
	}
}