/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class CoreAreaFlag : CoreAreaFlagBase)
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/CoreAreaFlag.def
	// Please inherit and implement "class CoreAreaFlag : CoreAreaFlagBase"
	public abstract class CoreAreaFlagBase : ModelEntity
	{
		public EntityBaseEntityCall_CoreAreaFlagBase baseEntityCall = null;
		public EntityCellEntityCall_CoreAreaFlagBase cellEntityCall = null;

		public Int32 defenseNum = 0;
		public virtual void onDefenseNumChanged(Int32 oldValue) {}
		
		
		public Int32 offenseNum = 0;
		public virtual void onOffenseNumChanged(Int32 oldValue) {}
		


		public CoreAreaFlagBase()
		{
		}

		public override void onComponentsEnterworld()
		{
		}

		public override void onComponentsLeaveworld()
		{
		}

		public override void onGetBase()
		{
			baseEntityCall = new EntityBaseEntityCall_CoreAreaFlagBase(id, className);
		}

		public override void onGetCell()
		{
			cellEntityCall = new EntityCellEntityCall_CoreAreaFlagBase(id, className);
		}

		public override void onLoseCell()
		{
			cellEntityCall = null;
		}

		public override EntityCall getBaseEntityCall()
		{
			return baseEntityCall;
		}

		public override EntityCall getCellEntityCall()
		{
			return cellEntityCall;
		}

		public override void attachComponents()
		{
		}

		public override void detachComponents()
		{
		}

		public override void onRemoteMethodCall(MemoryStream stream)
		{
			ScriptModule sm = EntityDef.moduledefs["CoreAreaFlag"];

			UInt16 methodUtype = 0;
			UInt16 componentPropertyUType = 0;

			if(sm.usePropertyDescrAlias)
			{
				componentPropertyUType = stream.readUint8();
			}
			else
			{
				componentPropertyUType = stream.readUint16();
			}

			if(sm.useMethodDescrAlias)
			{
				methodUtype = stream.readUint8();
			}
			else
			{
				methodUtype = stream.readUint16();
			}

			Method method = null;

			if(componentPropertyUType == 0)
			{
				method = sm.idmethods[methodUtype];
			}
			else
			{
				Property pComponentPropertyDescription = sm.idpropertys[componentPropertyUType];
				switch(pComponentPropertyDescription.properUtype)
				{
					default:
						break;
				}

				return;
			}

			switch(method.methodUtype)
			{
				default:
					break;
			};
		}

		public override void onUpdatePropertys(MemoryStream stream)
		{
			ScriptModule sm = EntityDef.moduledefs["CoreAreaFlag"];
			Dictionary<UInt16, Property> pdatas = sm.idpropertys;

			while(stream.length() > 0)
			{
				UInt16 _t_utype = 0;
				{
					if(sm.usePropertyDescrAlias)
					{
						_t_utype = stream.readUint8();
					}
					else
					{
						_t_utype = stream.readUint16();
					}
				}

				Property prop = null;

				if(_t_utype != 0)
				{
					prop = pdatas[_t_utype];
				}
				else
				{
					Property pComponentPropertyDescription = pdatas[_t_utype];
					switch(pComponentPropertyDescription.properUtype)
					{
						default:
							break;
					}

					return;
				}

				switch(prop.properUtype)
				{
					case 259:
						Int32 oldval_defenseNum = defenseNum;
						defenseNum = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onDefenseNumChanged(oldval_defenseNum);
						}
						else
						{
							if(inWorld)
								onDefenseNumChanged(oldval_defenseNum);
						}

						break;
					case 40001:
						Vector3 oldval_direction = direction;
						direction = stream.readVector3();

						if(prop.isBase())
						{
							if(inited)
								onDirectionChanged(oldval_direction);
						}
						else
						{
							if(inWorld)
								onDirectionChanged(oldval_direction);
						}

						break;
					case 263:
						Int32 oldval_force = force;
						force = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onForceChanged(oldval_force);
						}
						else
						{
							if(inWorld)
								onForceChanged(oldval_force);
						}

						break;
					case 346:
						Int64 oldval_gameEntityId = gameEntityId;
						gameEntityId = stream.readInt64();

						if(prop.isBase())
						{
							if(inited)
								onGameEntityIdChanged(oldval_gameEntityId);
						}
						else
						{
							if(inWorld)
								onGameEntityIdChanged(oldval_gameEntityId);
						}

						break;
					case 258:
						Int32 oldval_offenseNum = offenseNum;
						offenseNum = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onOffenseNumChanged(oldval_offenseNum);
						}
						else
						{
							if(inWorld)
								onOffenseNumChanged(oldval_offenseNum);
						}

						break;
					case 40000:
						Vector3 oldval_position = position;
						position = stream.readVector3();

						if(prop.isBase())
						{
							if(inited)
								onPositionChanged(oldval_position);
						}
						else
						{
							if(inWorld)
								onPositionChanged(oldval_position);
						}

						break;
					case 40002:
						stream.readUint32();
						break;
					case 262:
						UInt32 oldval_spaceNo = spaceNo;
						oldSpaceNo = oldval_spaceNo;
						spaceNo = stream.readUint32();

						if(prop.isBase())
						{
							if(inited)
								onSpaceNoChanged(oldval_spaceNo);
						}
						else
						{
							if(inWorld)
								onSpaceNoChanged(oldval_spaceNo);
						}

						break;
					default:
						break;
				};
			}
		}

		public override void callPropertysSetMethods()
		{
			ScriptModule sm = EntityDef.moduledefs["CoreAreaFlag"];
			Dictionary<UInt16, Property> pdatas = sm.idpropertys;

			Int32 oldval_defenseNum = defenseNum;
			Property prop_defenseNum = pdatas[4];
			if(prop_defenseNum.isBase())
			{
				if(inited && !inWorld)
					onDefenseNumChanged(oldval_defenseNum);
			}
			else
			{
				if(inWorld)
				{
					if(prop_defenseNum.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onDefenseNumChanged(oldval_defenseNum);
					}
				}
			}

			Vector3 oldval_direction = direction;
			Property prop_direction = pdatas[2];
			if(prop_direction.isBase())
			{
				if(inited && !inWorld)
					onDirectionChanged(oldval_direction);
			}
			else
			{
				if(inWorld)
				{
					if(prop_direction.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onDirectionChanged(oldval_direction);
					}
				}
			}

			Int32 oldval_force = force;
			Property prop_force = pdatas[6];
			if(prop_force.isBase())
			{
				if(inited && !inWorld)
					onForceChanged(oldval_force);
			}
			else
			{
				if(inWorld)
				{
					if(prop_force.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onForceChanged(oldval_force);
					}
				}
			}

			Int64 oldval_gameEntityId = gameEntityId;
			Property prop_gameEntityId = pdatas[7];
			if(prop_gameEntityId.isBase())
			{
				if(inited && !inWorld)
					onGameEntityIdChanged(oldval_gameEntityId);
			}
			else
			{
				if(inWorld)
				{
					if(prop_gameEntityId.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onGameEntityIdChanged(oldval_gameEntityId);
					}
				}
			}

			Int32 oldval_offenseNum = offenseNum;
			Property prop_offenseNum = pdatas[8];
			if(prop_offenseNum.isBase())
			{
				if(inited && !inWorld)
					onOffenseNumChanged(oldval_offenseNum);
			}
			else
			{
				if(inWorld)
				{
					if(prop_offenseNum.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onOffenseNumChanged(oldval_offenseNum);
					}
				}
			}

			Vector3 oldval_position = position;
			Property prop_position = pdatas[1];
			if(prop_position.isBase())
			{
				if(inited && !inWorld)
					onPositionChanged(oldval_position);
			}
			else
			{
				if(inWorld)
				{
					if(prop_position.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onPositionChanged(oldval_position);
					}
				}
			}

			UInt32 oldval_spaceNo = spaceNo;
			Property prop_spaceNo = pdatas[9];
			if(prop_spaceNo.isBase())
			{
				if(inited && !inWorld)
					onSpaceNoChanged(oldval_spaceNo);
			}
			else
			{
				if(inWorld)
				{
					if(prop_spaceNo.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onSpaceNoChanged(oldval_spaceNo);
					}
				}
			}

		}
	}
}