/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Avataring.def
	public class EntityBaseEntityCall_AvataringBase : EntityCall
	{

		public EntityBaseEntityCall_AvataringBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_BASE;
		}

		public void sendWorldChatMsg(CHAT_MSG_DATA arg1)
		{
			Bundle pBundle = newCall("sendWorldChatMsg", 0);
			if(pBundle == null)
				return;

			((DATATYPE_CHAT_MSG_DATA)EntityDef.id2datatypes[119]).addToStreamEx(bundle, arg1);
			sendCall(null);
		}

	}

	public class EntityCellEntityCall_AvataringBase : EntityCall
	{

		public EntityCellEntityCall_AvataringBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_CELL;
		}

		public void clientRemoveState(Byte arg1)
		{
			Bundle pBundle = newCall("clientRemoveState", 0);
			if(pBundle == null)
				return;

			bundle.writeUint8(arg1);
			sendCall(null);
		}

		public void clientSetState(Byte arg1)
		{
			Bundle pBundle = newCall("clientSetState", 0);
			if(pBundle == null)
				return;

			bundle.writeUint8(arg1);
			sendCall(null);
		}

	}
	}
