/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Accounting.def
	public class EntityBaseEntityCall_AccountingBase : EntityCall
	{

		public EntityBaseEntityCall_AccountingBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_BASE;
		}

		public void accountOffline()
		{
			Bundle pBundle = newCall("accountOffline", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void createAvataring(UInt64 arg1, string arg2, UInt16 arg3, Byte arg4, Byte arg5, Byte arg6, OUTFIT_DATA arg7, FACE_DATA arg8)
		{
			Bundle pBundle = newCall("createAvataring", 0);
			if(pBundle == null)
				return;

			bundle.writeUint64(arg1);
			bundle.writeUnicode(arg2);
			bundle.writeUint16(arg3);
			bundle.writeUint8(arg4);
			bundle.writeUint8(arg5);
			bundle.writeUint8(arg6);
			((DATATYPE_OUTFIT_DATA)EntityDef.id2datatypes[33]).addToStreamEx(bundle, arg7);
			((DATATYPE_FACE_DATA)EntityDef.id2datatypes[28]).addToStreamEx(bundle, arg8);
			sendCall(null);
		}

		public void queryAvataringCharacter(List<UInt64> arg1)
		{
			Bundle pBundle = newCall("queryAvataringCharacter", 0);
			if(pBundle == null)
				return;

			((DATATYPE_AnonymousArray_10046)EntityDef.id2datatypes[10046]).addToStreamEx(bundle, arg1);
			sendCall(null);
		}

	}

	public class EntityCellEntityCall_AccountingBase : EntityCall
	{

		public EntityCellEntityCall_AccountingBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_CELL;
		}

	}
	}
