/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Avataring.def
	public class EntityBaseEntityCall_AvataringBase : EntityCall
	{

		public EntityBaseEntityCall_AvataringBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_BASE;
		}

		public void checkTextSecurityReq(CHECK_TEXT_SECURITY_REQ arg1)
		{
			Bundle pBundle = newCall("checkTextSecurityReq", 0);
			if(pBundle == null)
				return;

			((DATATYPE_CHECK_TEXT_SECURITY_REQ)EntityDef.id2datatypes[488]).addToStreamEx(bundle, arg1);
			sendCall(null);
		}

		public void sendWorldChatMsg(CHAT_MSG_DATA arg1)
		{
			Bundle pBundle = newCall("sendWorldChatMsg", 0);
			if(pBundle == null)
				return;

			((DATATYPE_CHAT_MSG_DATA)EntityDef.id2datatypes[121]).addToStreamEx(bundle, arg1);
			sendCall(null);
		}

	}

	public class EntityCellEntityCall_AvataringBase : EntityCall
	{

		public EntityCellEntityCall_AvataringBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_CELL;
		}

		public void breakAwayStuck()
		{
			Bundle pBundle = newCall("breakAwayStuck", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void clientRemoveState(Byte arg1)
		{
			Bundle pBundle = newCall("clientRemoveState", 0);
			if(pBundle == null)
				return;

			bundle.writeUint8(arg1);
			sendCall(null);
		}

		public void clientSetState(Byte arg1)
		{
			Bundle pBundle = newCall("clientSetState", 0);
			if(pBundle == null)
				return;

			bundle.writeUint8(arg1);
			sendCall(null);
		}

		public void jump(Byte arg1, UInt32 arg2)
		{
			Bundle pBundle = newCall("jump", 0);
			if(pBundle == null)
				return;

			bundle.writeUint8(arg1);
			bundle.writeUint32(arg2);
			sendCall(null);
		}

		public void offline(Byte arg1)
		{
			Bundle pBundle = newCall("offline", 0);
			if(pBundle == null)
				return;

			bundle.writeUint8(arg1);
			sendCall(null);
		}

		public void reqPlayEmote(UInt16 arg1)
		{
			Bundle pBundle = newCall("reqPlayEmote", 0);
			if(pBundle == null)
				return;

			bundle.writeUint16(arg1);
			sendCall(null);
		}

		public void reqStopPlayEmote()
		{
			Bundle pBundle = newCall("reqStopPlayEmote", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void setShowCompleteNum(Byte arg1)
		{
			Bundle pBundle = newCall("setShowCompleteNum", 0);
			if(pBundle == null)
				return;

			bundle.writeUint8(arg1);
			sendCall(null);
		}

	}
	}
