/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Account.def
	public class EntityBaseEntityCall_AccountBase : EntityCall
	{

		public EntityBaseEntityCall_AccountBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_BASE;
		}

		public void accountOffline()
		{
			Bundle pBundle = newCall("accountOffline", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void getAvatarDetailForAccount(UInt64 arg1)
		{
			Bundle pBundle = newCall("getAvatarDetailForAccount", 0);
			if(pBundle == null)
				return;

			bundle.writeUint64(arg1);
			sendCall(null);
		}

		public void getAvatarOfflineTime(UInt64 arg1)
		{
			Bundle pBundle = newCall("getAvatarOfflineTime", 0);
			if(pBundle == null)
				return;

			bundle.writeUint64(arg1);
			sendCall(null);
		}

		public void kickAnotherAvatar(Byte arg1)
		{
			Bundle pBundle = newCall("kickAnotherAvatar", 0);
			if(pBundle == null)
				return;

			bundle.writeUint8(arg1);
			sendCall(null);
		}

		public void logBeforeLogin(Int32 arg1, string arg2)
		{
			Bundle pBundle = newCall("logBeforeLogin", 0);
			if(pBundle == null)
				return;

			bundle.writeInt32(arg1);
			bundle.writeUnicode(arg2);
			sendCall(null);
		}

		public void reqCreateAvatar(UInt16 arg1, string arg2, Byte arg3, Byte arg4, FACE_DATA arg5)
		{
			Bundle pBundle = newCall("reqCreateAvatar", 0);
			if(pBundle == null)
				return;

			bundle.writeUint16(arg1);
			bundle.writeUnicode(arg2);
			bundle.writeUint8(arg3);
			bundle.writeUint8(arg4);
			((DATATYPE_FACE_DATA)EntityDef.id2datatypes[26]).addToStreamEx(bundle, arg5);
			sendCall(null);
		}

		public void reqCreateBot(string arg1, UInt16 arg2, FACE_DATA arg3)
		{
			Bundle pBundle = newCall("reqCreateBot", 0);
			if(pBundle == null)
				return;

			bundle.writeUnicode(arg1);
			bundle.writeUint16(arg2);
			((DATATYPE_FACE_DATA)EntityDef.id2datatypes[26]).addToStreamEx(bundle, arg3);
			sendCall(null);
		}

		public void reqRemoveAvatar(string arg1)
		{
			Bundle pBundle = newCall("reqRemoveAvatar", 0);
			if(pBundle == null)
				return;

			bundle.writeUnicode(arg1);
			sendCall(null);
		}

		public void selectAvatarGame(UInt64 arg1, Byte arg2)
		{
			Bundle pBundle = newCall("selectAvatarGame", 0);
			if(pBundle == null)
				return;

			bundle.writeUint64(arg1);
			bundle.writeUint8(arg2);
			sendCall(null);
		}

		public void stopCharacterAuth(UInt64 arg1)
		{
			Bundle pBundle = newCall("stopCharacterAuth", 0);
			if(pBundle == null)
				return;

			bundle.writeUint64(arg1);
			sendCall(null);
		}

	}

	public class EntityCellEntityCall_AccountBase : EntityCall
	{

		public EntityCellEntityCall_AccountBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_CELL;
		}

	}
	}
