/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Teleporter.def
	public class EntityBaseEntityCall_TeleporterBase : EntityCall
	{

		public EntityBaseEntityCall_TeleporterBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_BASE;
		}

	}

	public class EntityCellEntityCall_TeleporterBase : EntityCall
	{

		public EntityCellEntityCall_TeleporterBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_CELL;
		}

		public void doTeleport(Int32 arg1, Int16 arg2)
		{
			Bundle pBundle = newCall("doTeleport", 0);
			if(pBundle == null)
				return;

			bundle.writeInt32(arg1);
			bundle.writeInt16(arg2);
			sendCall(null);
		}

	}
	}
