/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class Npc : NpcBase)
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Npc.def
	// Please inherit and implement "class Npc : NpcBase"
	public abstract class NpcBase : ModelEntity
	{
		public EntityBaseEntityCall_NpcBase baseEntityCall = null;
		public EntityCellEntityCall_NpcBase cellEntityCall = null;

		
		public Int32 antiFatal = 0;
		public float bePushedSpeed = 0f;
		
		public UInt32 deathTime = 0;
		public virtual void onDeathTimeChanged(UInt32 oldValue) {}
		public float dmgArmor = 0f;
		public Int32 firstHateTargetId = 0;
		
		
		
		
		
		public float ignoreArmor = 0f;
		
		
		
		
		public float mulSpeed = 0f;
		
		
		public virtual void onNpcIdChanged(Int32 oldValue) {}
		
		public Int32 siegeWarCamp = 0;
		
		
		
		


		public NpcBase()
		{
		}

		public override void onComponentsEnterworld()
		{
		}

		public override void onComponentsLeaveworld()
		{
		}

		public override void onGetBase()
		{
			baseEntityCall = new EntityBaseEntityCall_NpcBase(id, className);
		}

		public override void onGetCell()
		{
			cellEntityCall = new EntityCellEntityCall_NpcBase(id, className);
		}

		public override void onLoseCell()
		{
			cellEntityCall = null;
		}

		public override EntityCall getBaseEntityCall()
		{
			return baseEntityCall;
		}

		public override EntityCall getCellEntityCall()
		{
			return cellEntityCall;
		}

		public override void attachComponents()
		{
		}

		public override void detachComponents()
		{
		}

		public override void onRemoteMethodCall(MemoryStream stream)
		{
			ScriptModule sm = EntityDef.moduledefs["Npc"];

			UInt16 methodUtype = 0;
			UInt16 componentPropertyUType = 0;

			if(sm.usePropertyDescrAlias)
			{
				componentPropertyUType = stream.readUint8();
			}
			else
			{
				componentPropertyUType = stream.readUint16();
			}

			if(sm.useMethodDescrAlias)
			{
				methodUtype = stream.readUint8();
			}
			else
			{
				methodUtype = stream.readUint16();
			}

			Method method = null;

			if(componentPropertyUType == 0)
			{
				method = sm.idmethods[methodUtype];
			}
			else
			{
				Property pComponentPropertyDescription = sm.idpropertys[componentPropertyUType];
				switch(pComponentPropertyDescription.properUtype)
				{
					default:
						break;
				}

				return;
			}

			switch(method.methodUtype)
			{
				case 108:
					UInt32 aiChatToPlayer_arg1 = stream.readUint32();
					UInt32 aiChatToPlayer_arg2 = stream.readUint32();
					aiChatToPlayer(aiChatToPlayer_arg1, aiChatToPlayer_arg2);
					break;
				case 737:
					Vector3 drawCube_arg1 = stream.readVector3();
					Vector3 drawCube_arg2 = stream.readVector3();
					float drawCube_arg3 = stream.readFloat();
					float drawCube_arg4 = stream.readFloat();
					drawCube(drawCube_arg1, drawCube_arg2, drawCube_arg3, drawCube_arg4);
					break;
				case 261:
					UInt32 notifyCastingSkill_arg1 = stream.readUint32();
					double notifyCastingSkill_arg2 = stream.readDouble();
					notifyCastingSkill(notifyCastingSkill_arg1, notifyCastingSkill_arg2);
					break;
				case 240:
					CLIENT_AUREOLE_VAL onAddAureole_arg1 = ((DATATYPE_CLIENT_AUREOLE_VAL)method.args[0]).createFromStreamEx(stream);
					onAddAureole(onAddAureole_arg1);
					break;
				case 243:
					CLIENT_AUREOLE_VAL onAddAureoleFromOthers_arg1 = ((DATATYPE_CLIENT_AUREOLE_VAL)method.args[0]).createFromStreamEx(stream);
					onAddAureoleFromOthers(onAddAureoleFromOthers_arg1);
					break;
				case 253:
					CLIENT_BUFF_VAL onAddBuff_arg1 = ((DATATYPE_CLIENT_BUFF_VAL)method.args[0]).createFromStreamEx(stream);
					onAddBuff(onAddBuff_arg1);
					break;
				case 69:
					UInt32 onAddPassiveSkill_arg1 = stream.readUint32();
					UInt32 onAddPassiveSkill_arg2 = stream.readUint32();
					onAddPassiveSkill(onAddPassiveSkill_arg1, onAddPassiveSkill_arg2);
					break;
				case 67:
					UInt32 onAddSkill_arg1 = stream.readUint32();
					UInt32 onAddSkill_arg2 = stream.readUint32();
					Byte onAddSkill_arg3 = stream.readUint8();
					double onAddSkill_arg4 = stream.readDouble();
					float onAddSkill_arg5 = stream.readFloat();
					Byte onAddSkill_arg6 = stream.readUint8();
					onAddSkill(onAddSkill_arg1, onAddSkill_arg2, onAddSkill_arg3, onAddSkill_arg4, onAddSkill_arg5, onAddSkill_arg6);
					break;
				case 158:
					onBornAction();
					break;
				case 250:
					Int32 onBreakCastingSkill_arg1 = stream.readInt32();
					UInt32 onBreakCastingSkill_arg2 = stream.readUint32();
					Int32 onBreakCastingSkill_arg3 = stream.readInt32();
					onBreakCastingSkill(onBreakCastingSkill_arg1, onBreakCastingSkill_arg2, onBreakCastingSkill_arg3);
					break;
				case 251:
					Int32 onBreakChannelingSkill_arg1 = stream.readInt32();
					UInt32 onBreakChannelingSkill_arg2 = stream.readUint32();
					Int32 onBreakChannelingSkill_arg3 = stream.readInt32();
					onBreakChannelingSkill(onBreakChannelingSkill_arg1, onBreakChannelingSkill_arg2, onBreakChannelingSkill_arg3);
					break;
				case 157:
					Int32 onDead_arg1 = stream.readInt32();
					onDead(onDead_arg1);
					break;
				case 496:
					Vector3 onExitShiftByConflict_arg1 = stream.readVector3();
					onExitShiftByConflict(onExitShiftByConflict_arg1);
					break;
				case 257:
					Int32 onGetAureoleInfo_arg1 = stream.readInt32();
					CLIENT_AUREOLES onGetAureoleInfo_arg2 = ((DATATYPE_CLIENT_AUREOLES)method.args[1]).createFromStreamEx(stream);
					onGetAureoleInfo(onGetAureoleInfo_arg1, onGetAureoleInfo_arg2);
					break;
				case 256:
					Int32 onGetBuffInfo_arg1 = stream.readInt32();
					CLIENT_BUFFS onGetBuffInfo_arg2 = ((DATATYPE_CLIENT_BUFFS)method.args[1]).createFromStreamEx(stream);
					onGetBuffInfo(onGetBuffInfo_arg1, onGetBuffInfo_arg2);
					break;
				case 249:
					Int32 onMessage_arg1 = stream.readInt32();
					List<string> onMessage_arg2 = ((DATATYPE_AnonymousArray_10001)method.args[1]).createFromStreamEx(stream);
					onMessage(onMessage_arg1, onMessage_arg2);
					break;
				case 238:
					Int32 onOthersSkillDamage_arg1 = stream.readInt32();
					List<Int32> onOthersSkillDamage_arg2 = ((DATATYPE_AnonymousArray_10004)method.args[1]).createFromStreamEx(stream);
					onOthersSkillDamage(onOthersSkillDamage_arg1, onOthersSkillDamage_arg2);
					break;
				case 241:
					Int32 onRemoveAureole_arg1 = stream.readInt32();
					onRemoveAureole(onRemoveAureole_arg1);
					break;
				case 244:
					Int32 onRemoveAureoleFromOthers_arg1 = stream.readInt32();
					onRemoveAureoleFromOthers(onRemoveAureoleFromOthers_arg1);
					break;
				case 254:
					Int32 onRemoveBuff_arg1 = stream.readInt32();
					List<UInt64> onRemoveBuff_arg2 = ((DATATYPE_AnonymousArray_10006)method.args[1]).createFromStreamEx(stream);
					onRemoveBuff(onRemoveBuff_arg1, onRemoveBuff_arg2);
					break;
				case 258:
					UInt32 onSetAddSkillCd_arg1 = stream.readUint32();
					float onSetAddSkillCd_arg2 = stream.readFloat();
					double onSetAddSkillCd_arg3 = stream.readDouble();
					Byte onSetAddSkillCd_arg4 = stream.readUint8();
					double onSetAddSkillCd_arg5 = stream.readDouble();
					SByte onSetAddSkillCd_arg6 = stream.readInt8();
					SByte onSetAddSkillCd_arg7 = stream.readInt8();
					Byte onSetAddSkillCd_arg8 = stream.readUint8();
					onSetAddSkillCd(onSetAddSkillCd_arg1, onSetAddSkillCd_arg2, onSetAddSkillCd_arg3, onSetAddSkillCd_arg4, onSetAddSkillCd_arg5, onSetAddSkillCd_arg6, onSetAddSkillCd_arg7, onSetAddSkillCd_arg8);
					break;
				case 264:
					UInt32 onShooterSkillCanUse_arg1 = stream.readUint32();
					double onShooterSkillCanUse_arg2 = stream.readDouble();
					Byte onShooterSkillCanUse_arg3 = stream.readUint8();
					onShooterSkillCanUse(onShooterSkillCanUse_arg1, onShooterSkillCanUse_arg2, onShooterSkillCanUse_arg3);
					break;
				case 237:
					SKILL_DAMAGE_INFO onSkillDamage_arg1 = ((DATATYPE_SKILL_DAMAGE_INFO)method.args[0]).createFromStreamEx(stream);
					onSkillDamage(onSkillDamage_arg1);
					break;
				case 538:
					Byte onStateChangedForce_arg1 = stream.readUint8();
					onStateChangedForce(onStateChangedForce_arg1);
					break;
				case 242:
					CLIENT_AUREOLES onUpdateAureoles_arg1 = ((DATATYPE_CLIENT_AUREOLES)method.args[0]).createFromStreamEx(stream);
					onUpdateAureoles(onUpdateAureoles_arg1);
					break;
				case 245:
					AUREOLE_FROM_OTHERS onUpdateAureolesFromOthers_arg1 = ((DATATYPE_AUREOLE_FROM_OTHERS)method.args[0]).createFromStreamEx(stream);
					onUpdateAureolesFromOthers(onUpdateAureolesFromOthers_arg1);
					break;
				case 255:
					CLIENT_BUFF_VAL onUpdateBuff_arg1 = ((DATATYPE_CLIENT_BUFF_VAL)method.args[0]).createFromStreamEx(stream);
					onUpdateBuff(onUpdateBuff_arg1);
					break;
				case 252:
					CLIENT_BUFFS onUpdateBuffs_arg1 = ((DATATYPE_CLIENT_BUFFS)method.args[0]).createFromStreamEx(stream);
					onUpdateBuffs(onUpdateBuffs_arg1);
					break;
				case 72:
					Int32 onUseCasting_arg1 = stream.readInt32();
					UInt32 onUseCasting_arg2 = stream.readUint32();
					Int32 onUseCasting_arg3 = stream.readInt32();
					List<float> onUseCasting_arg4 = ((DATATYPE_AnonymousArray_10009)method.args[3]).createFromStreamEx(stream);
					List<Int32> onUseCasting_arg5 = ((DATATYPE_AnonymousArray_10004)method.args[4]).createFromStreamEx(stream);
					List<float> onUseCasting_arg6 = ((DATATYPE_AnonymousArray_10009)method.args[5]).createFromStreamEx(stream);
					onUseCasting(onUseCasting_arg1, onUseCasting_arg2, onUseCasting_arg3, onUseCasting_arg4, onUseCasting_arg5, onUseCasting_arg6);
					break;
				case 88:
					Int32 onUseChanneling_arg1 = stream.readInt32();
					UInt32 onUseChanneling_arg2 = stream.readUint32();
					Int32 onUseChanneling_arg3 = stream.readInt32();
					List<float> onUseChanneling_arg4 = ((DATATYPE_AnonymousArray_10009)method.args[3]).createFromStreamEx(stream);
					List<Int32> onUseChanneling_arg5 = ((DATATYPE_AnonymousArray_10004)method.args[4]).createFromStreamEx(stream);
					Int32 onUseChanneling_arg6 = stream.readInt32();
					List<float> onUseChanneling_arg7 = ((DATATYPE_AnonymousArray_10009)method.args[6]).createFromStreamEx(stream);
					onUseChanneling(onUseChanneling_arg1, onUseChanneling_arg2, onUseChanneling_arg3, onUseChanneling_arg4, onUseChanneling_arg5, onUseChanneling_arg6, onUseChanneling_arg7);
					break;
				case 70:
					Byte onUseSkill_arg1 = stream.readUint8();
					UInt32 onUseSkill_arg2 = stream.readUint32();
					Int32 onUseSkill_arg3 = stream.readInt32();
					List<float> onUseSkill_arg4 = ((DATATYPE_AnonymousArray_10009)method.args[3]).createFromStreamEx(stream);
					List<Int32> onUseSkill_arg5 = ((DATATYPE_AnonymousArray_10004)method.args[4]).createFromStreamEx(stream);
					List<float> onUseSkill_arg6 = ((DATATYPE_AnonymousArray_10009)method.args[5]).createFromStreamEx(stream);
					onUseSkill(onUseSkill_arg1, onUseSkill_arg2, onUseSkill_arg3, onUseSkill_arg4, onUseSkill_arg5, onUseSkill_arg6);
					break;
				case 159:
					Int32 popDialog_arg1 = stream.readInt32();
					popDialog(popDialog_arg1);
					break;
				case 161:
					UInt32 showPopoverMsg_arg1 = stream.readUint32();
					showPopoverMsg(showPopoverMsg_arg1);
					break;
				case 162:
					UInt32 showPopoverMsgWithArg_arg1 = stream.readUint32();
					List<string> showPopoverMsgWithArg_arg2 = ((DATATYPE_AnonymousArray_10001)method.args[1]).createFromStreamEx(stream);
					showPopoverMsgWithArg(showPopoverMsgWithArg_arg1, showPopoverMsgWithArg_arg2);
					break;
				case 1153:
					List<UInt16> updateForbidSkillTags_arg1 = ((DATATYPE_AnonymousArray_10005)method.args[0]).createFromStreamEx(stream);
					updateForbidSkillTags(updateForbidSkillTags_arg1);
					break;
				default:
					break;
			};
		}

		public override void onUpdatePropertys(MemoryStream stream)
		{
			ScriptModule sm = EntityDef.moduledefs["Npc"];
			Dictionary<UInt16, Property> pdatas = sm.idpropertys;

			while(stream.length() > 0)
			{
				UInt16 _t_utype = 0;
				{
					if(sm.usePropertyDescrAlias)
					{
						_t_utype = stream.readUint8();
					}
					else
					{
						_t_utype = stream.readUint16();
					}
				}

				Property prop = null;

				if(_t_utype != 0)
				{
					prop = pdatas[_t_utype];
				}
				else
				{
					Property pComponentPropertyDescription = pdatas[_t_utype];
					switch(pComponentPropertyDescription.properUtype)
					{
						default:
							break;
					}

					return;
				}

				switch(prop.properUtype)
				{
					case 312:
						float oldval_adjCD = adjCD;
						adjCD = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onAdjCDChanged(oldval_adjCD);
						}
						else
						{
							if(inWorld)
								onAdjCDChanged(oldval_adjCD);
						}

						break;
					case 328:
						Int32 oldval_antiFatal = antiFatal;
						antiFatal = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onAntiFatalChanged(oldval_antiFatal);
						}
						else
						{
							if(inWorld)
								onAntiFatalChanged(oldval_antiFatal);
						}

						break;
					case 72:
						float oldval_bePushedSpeed = bePushedSpeed;
						bePushedSpeed = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onBePushedSpeedChanged(oldval_bePushedSpeed);
						}
						else
						{
							if(inWorld)
								onBePushedSpeedChanged(oldval_bePushedSpeed);
						}

						break;
					case 62:
						Byte oldval_bornState = bornState;
						bornState = stream.readUint8();

						if(prop.isBase())
						{
							if(inited)
								onBornStateChanged(oldval_bornState);
						}
						else
						{
							if(inWorld)
								onBornStateChanged(oldval_bornState);
						}

						break;
					case 69:
						UInt32 oldval_deathTime = deathTime;
						deathTime = stream.readUint32();

						if(prop.isBase())
						{
							if(inited)
								onDeathTimeChanged(oldval_deathTime);
						}
						else
						{
							if(inWorld)
								onDeathTimeChanged(oldval_deathTime);
						}

						break;
					case 40001:
						Vector3 oldval_direction = direction;
						direction = stream.readVector3();

						if(prop.isBase())
						{
							if(inited)
								onDirectionChanged(oldval_direction);
						}
						else
						{
							if(inWorld)
								onDirectionChanged(oldval_direction);
						}

						break;
					case 540:
						float oldval_dmgArmor = dmgArmor;
						dmgArmor = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onDmgArmorChanged(oldval_dmgArmor);
						}
						else
						{
							if(inWorld)
								onDmgArmorChanged(oldval_dmgArmor);
						}

						break;
					case 242:
						Int32 oldval_firstHateTargetId = firstHateTargetId;
						firstHateTargetId = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onFirstHateTargetIdChanged(oldval_firstHateTargetId);
						}
						else
						{
							if(inWorld)
								onFirstHateTargetIdChanged(oldval_firstHateTargetId);
						}

						break;
					case 572:
						Int32 oldval_force = force;
						force = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onForceChanged(oldval_force);
						}
						else
						{
							if(inWorld)
								onForceChanged(oldval_force);
						}

						break;
					case 219:
						Int32 oldval_fullHp = fullHp;
						fullHp = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onFullHpChanged(oldval_fullHp);
						}
						else
						{
							if(inWorld)
								onFullHpChanged(oldval_fullHp);
						}

						break;
					case 232:
						Int32 oldval_fullMp = fullMp;
						fullMp = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onFullMpChanged(oldval_fullMp);
						}
						else
						{
							if(inWorld)
								onFullMpChanged(oldval_fullMp);
						}

						break;
					case 40:
						Int64 oldval_gameEntityId = gameEntityId;
						gameEntityId = stream.readInt64();

						if(prop.isBase())
						{
							if(inited)
								onGameEntityIdChanged(oldval_gameEntityId);
						}
						else
						{
							if(inWorld)
								onGameEntityIdChanged(oldval_gameEntityId);
						}

						break;
					case 220:
						Int32 oldval_hp = hp;
						hp = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onHpChanged(oldval_hp);
						}
						else
						{
							if(inWorld)
								onHpChanged(oldval_hp);
						}

						break;
					case 537:
						float oldval_ignoreArmor = ignoreArmor;
						ignoreArmor = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onIgnoreArmorChanged(oldval_ignoreArmor);
						}
						else
						{
							if(inWorld)
								onIgnoreArmorChanged(oldval_ignoreArmor);
						}

						break;
					case 61:
						Byte oldval_isBoss = isBoss;
						isBoss = stream.readUint8();

						if(prop.isBase())
						{
							if(inited)
								onIsBossChanged(oldval_isBoss);
						}
						else
						{
							if(inWorld)
								onIsBossChanged(oldval_isBoss);
						}

						break;
					case 213:
						Byte oldval_isWitnessComplete = isWitnessComplete;
						isWitnessComplete = stream.readUint8();

						if(prop.isBase())
						{
							if(inited)
								onIsWitnessCompleteChanged(oldval_isWitnessComplete);
						}
						else
						{
							if(inWorld)
								onIsWitnessCompleteChanged(oldval_isWitnessComplete);
						}

						break;
					case 214:
						UInt32 oldval_level = level;
						level = stream.readUint32();

						if(prop.isBase())
						{
							if(inited)
								onLevelChanged(oldval_level);
						}
						else
						{
							if(inWorld)
								onLevelChanged(oldval_level);
						}

						break;
					case 313:
						float oldval_mulCD = mulCD;
						mulCD = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onMulCDChanged(oldval_mulCD);
						}
						else
						{
							if(inWorld)
								onMulCDChanged(oldval_mulCD);
						}

						break;
					case 30515:
						float oldval_mulSpeed = mulSpeed;
						mulSpeed = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onMulSpeedChanged(oldval_mulSpeed);
						}
						else
						{
							if(inWorld)
								onMulSpeedChanged(oldval_mulSpeed);
						}

						break;
					case 33:
						string oldval_name = name;
						name = stream.readUnicode();

						if(prop.isBase())
						{
							if(inited)
								onNameChanged(oldval_name);
						}
						else
						{
							if(inWorld)
								onNameChanged(oldval_name);
						}

						break;
					case 32:
						Int32 oldval_npcId = npcId;
						npcId = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onNpcIdChanged(oldval_npcId);
						}
						else
						{
							if(inWorld)
								onNpcIdChanged(oldval_npcId);
						}

						break;
					case 40000:
						Vector3 oldval_position = position;
						position = stream.readVector3();

						if(prop.isBase())
						{
							if(inited)
								onPositionChanged(oldval_position);
						}
						else
						{
							if(inWorld)
								onPositionChanged(oldval_position);
						}

						break;
					case 383:
						Int32 oldval_selectedTargetId = selectedTargetId;
						selectedTargetId = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onSelectedTargetIdChanged(oldval_selectedTargetId);
						}
						else
						{
							if(inWorld)
								onSelectedTargetIdChanged(oldval_selectedTargetId);
						}

						break;
					case 553:
						Int32 oldval_siegeWarCamp = siegeWarCamp;
						siegeWarCamp = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onSiegeWarCampChanged(oldval_siegeWarCamp);
						}
						else
						{
							if(inWorld)
								onSiegeWarCampChanged(oldval_siegeWarCamp);
						}

						break;
					case 40002:
						stream.readUint32();
						break;
					case 39:
						UInt32 oldval_spaceNo = spaceNo;
						oldSpaceNo = oldval_spaceNo;
						spaceNo = stream.readUint32();

						if(prop.isBase())
						{
							if(inited)
								onSpaceNoChanged(oldval_spaceNo);
						}
						else
						{
							if(inWorld)
								onSpaceNoChanged(oldval_spaceNo);
						}

						break;
					case 314:
						float oldval_speed = speed;
						speed = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onSpeedChanged(oldval_speed);
						}
						else
						{
							if(inWorld)
								onSpeedChanged(oldval_speed);
						}

						break;
					case 42:
						Int64 oldval_state = state;
						state = stream.readInt64();

						if(prop.isBase())
						{
							if(inited)
								onStateChanged(oldval_state);
						}
						else
						{
							if(inWorld)
								onStateChanged(oldval_state);
						}

						break;
					case 43:
						Int64 oldval_state2 = state2;
						state2 = stream.readInt64();

						if(prop.isBase())
						{
							if(inited)
								onState2Changed(oldval_state2);
						}
						else
						{
							if(inWorld)
								onState2Changed(oldval_state2);
						}

						break;
					default:
						break;
				};
			}
		}

		public override void callPropertysSetMethods()
		{
			ScriptModule sm = EntityDef.moduledefs["Npc"];
			Dictionary<UInt16, Property> pdatas = sm.idpropertys;

			float oldval_adjCD = adjCD;
			Property prop_adjCD = pdatas[16];
			if(prop_adjCD.isBase())
			{
				if(inited && !inWorld)
					onAdjCDChanged(oldval_adjCD);
			}
			else
			{
				if(inWorld)
				{
					if(prop_adjCD.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onAdjCDChanged(oldval_adjCD);
					}
				}
			}

			Int32 oldval_antiFatal = antiFatal;
			Property prop_antiFatal = pdatas[58];
			if(prop_antiFatal.isBase())
			{
				if(inited && !inWorld)
					onAntiFatalChanged(oldval_antiFatal);
			}
			else
			{
				if(inWorld)
				{
					if(prop_antiFatal.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onAntiFatalChanged(oldval_antiFatal);
					}
				}
			}

			float oldval_bePushedSpeed = bePushedSpeed;
			Property prop_bePushedSpeed = pdatas[22];
			if(prop_bePushedSpeed.isBase())
			{
				if(inited && !inWorld)
					onBePushedSpeedChanged(oldval_bePushedSpeed);
			}
			else
			{
				if(inWorld)
				{
					if(prop_bePushedSpeed.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onBePushedSpeedChanged(oldval_bePushedSpeed);
					}
				}
			}

			Byte oldval_bornState = bornState;
			Property prop_bornState = pdatas[17];
			if(prop_bornState.isBase())
			{
				if(inited && !inWorld)
					onBornStateChanged(oldval_bornState);
			}
			else
			{
				if(inWorld)
				{
					if(prop_bornState.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onBornStateChanged(oldval_bornState);
					}
				}
			}

			UInt32 oldval_deathTime = deathTime;
			Property prop_deathTime = pdatas[5];
			if(prop_deathTime.isBase())
			{
				if(inited && !inWorld)
					onDeathTimeChanged(oldval_deathTime);
			}
			else
			{
				if(inWorld)
				{
					if(prop_deathTime.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onDeathTimeChanged(oldval_deathTime);
					}
				}
			}

			Vector3 oldval_direction = direction;
			Property prop_direction = pdatas[2];
			if(prop_direction.isBase())
			{
				if(inited && !inWorld)
					onDirectionChanged(oldval_direction);
			}
			else
			{
				if(inWorld)
				{
					if(prop_direction.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onDirectionChanged(oldval_direction);
					}
				}
			}

			float oldval_dmgArmor = dmgArmor;
			Property prop_dmgArmor = pdatas[55];
			if(prop_dmgArmor.isBase())
			{
				if(inited && !inWorld)
					onDmgArmorChanged(oldval_dmgArmor);
			}
			else
			{
				if(inWorld)
				{
					if(prop_dmgArmor.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onDmgArmorChanged(oldval_dmgArmor);
					}
				}
			}

			Int32 oldval_firstHateTargetId = firstHateTargetId;
			Property prop_firstHateTargetId = pdatas[4];
			if(prop_firstHateTargetId.isBase())
			{
				if(inited && !inWorld)
					onFirstHateTargetIdChanged(oldval_firstHateTargetId);
			}
			else
			{
				if(inWorld)
				{
					if(prop_firstHateTargetId.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onFirstHateTargetIdChanged(oldval_firstHateTargetId);
					}
				}
			}

			Int32 oldval_force = force;
			Property prop_force = pdatas[184];
			if(prop_force.isBase())
			{
				if(inited && !inWorld)
					onForceChanged(oldval_force);
			}
			else
			{
				if(inWorld)
				{
					if(prop_force.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onForceChanged(oldval_force);
					}
				}
			}

			Int32 oldval_fullHp = fullHp;
			Property prop_fullHp = pdatas[80];
			if(prop_fullHp.isBase())
			{
				if(inited && !inWorld)
					onFullHpChanged(oldval_fullHp);
			}
			else
			{
				if(inWorld)
				{
					if(prop_fullHp.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onFullHpChanged(oldval_fullHp);
					}
				}
			}

			Int32 oldval_fullMp = fullMp;
			Property prop_fullMp = pdatas[81];
			if(prop_fullMp.isBase())
			{
				if(inited && !inWorld)
					onFullMpChanged(oldval_fullMp);
			}
			else
			{
				if(inWorld)
				{
					if(prop_fullMp.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onFullMpChanged(oldval_fullMp);
					}
				}
			}

			Int64 oldval_gameEntityId = gameEntityId;
			Property prop_gameEntityId = pdatas[6];
			if(prop_gameEntityId.isBase())
			{
				if(inited && !inWorld)
					onGameEntityIdChanged(oldval_gameEntityId);
			}
			else
			{
				if(inWorld)
				{
					if(prop_gameEntityId.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onGameEntityIdChanged(oldval_gameEntityId);
					}
				}
			}

			Int32 oldval_hp = hp;
			Property prop_hp = pdatas[84];
			if(prop_hp.isBase())
			{
				if(inited && !inWorld)
					onHpChanged(oldval_hp);
			}
			else
			{
				if(inWorld)
				{
					if(prop_hp.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onHpChanged(oldval_hp);
					}
				}
			}

			float oldval_ignoreArmor = ignoreArmor;
			Property prop_ignoreArmor = pdatas[62];
			if(prop_ignoreArmor.isBase())
			{
				if(inited && !inWorld)
					onIgnoreArmorChanged(oldval_ignoreArmor);
			}
			else
			{
				if(inWorld)
				{
					if(prop_ignoreArmor.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onIgnoreArmorChanged(oldval_ignoreArmor);
					}
				}
			}

			Byte oldval_isBoss = isBoss;
			Property prop_isBoss = pdatas[18];
			if(prop_isBoss.isBase())
			{
				if(inited && !inWorld)
					onIsBossChanged(oldval_isBoss);
			}
			else
			{
				if(inWorld)
				{
					if(prop_isBoss.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onIsBossChanged(oldval_isBoss);
					}
				}
			}

			Byte oldval_isWitnessComplete = isWitnessComplete;
			Property prop_isWitnessComplete = pdatas[85];
			if(prop_isWitnessComplete.isBase())
			{
				if(inited && !inWorld)
					onIsWitnessCompleteChanged(oldval_isWitnessComplete);
			}
			else
			{
				if(inWorld)
				{
					if(prop_isWitnessComplete.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onIsWitnessCompleteChanged(oldval_isWitnessComplete);
					}
				}
			}

			UInt32 oldval_level = level;
			Property prop_level = pdatas[86];
			if(prop_level.isBase())
			{
				if(inited && !inWorld)
					onLevelChanged(oldval_level);
			}
			else
			{
				if(inWorld)
				{
					if(prop_level.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onLevelChanged(oldval_level);
					}
				}
			}

			float oldval_mulCD = mulCD;
			Property prop_mulCD = pdatas[101];
			if(prop_mulCD.isBase())
			{
				if(inited && !inWorld)
					onMulCDChanged(oldval_mulCD);
			}
			else
			{
				if(inWorld)
				{
					if(prop_mulCD.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onMulCDChanged(oldval_mulCD);
					}
				}
			}

			float oldval_mulSpeed = mulSpeed;
			Property prop_mulSpeed = pdatas[44];
			if(prop_mulSpeed.isBase())
			{
				if(inited && !inWorld)
					onMulSpeedChanged(oldval_mulSpeed);
			}
			else
			{
				if(inWorld)
				{
					if(prop_mulSpeed.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onMulSpeedChanged(oldval_mulSpeed);
					}
				}
			}

			string oldval_name = name;
			Property prop_name = pdatas[7];
			if(prop_name.isBase())
			{
				if(inited && !inWorld)
					onNameChanged(oldval_name);
			}
			else
			{
				if(inWorld)
				{
					if(prop_name.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onNameChanged(oldval_name);
					}
				}
			}

			Int32 oldval_npcId = npcId;
			Property prop_npcId = pdatas[8];
			if(prop_npcId.isBase())
			{
				if(inited && !inWorld)
					onNpcIdChanged(oldval_npcId);
			}
			else
			{
				if(inWorld)
				{
					if(prop_npcId.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onNpcIdChanged(oldval_npcId);
					}
				}
			}

			Vector3 oldval_position = position;
			Property prop_position = pdatas[1];
			if(prop_position.isBase())
			{
				if(inited && !inWorld)
					onPositionChanged(oldval_position);
			}
			else
			{
				if(inWorld)
				{
					if(prop_position.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onPositionChanged(oldval_position);
					}
				}
			}

			Int32 oldval_selectedTargetId = selectedTargetId;
			Property prop_selectedTargetId = pdatas[160];
			if(prop_selectedTargetId.isBase())
			{
				if(inited && !inWorld)
					onSelectedTargetIdChanged(oldval_selectedTargetId);
			}
			else
			{
				if(inWorld)
				{
					if(prop_selectedTargetId.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onSelectedTargetIdChanged(oldval_selectedTargetId);
					}
				}
			}

			Int32 oldval_siegeWarCamp = siegeWarCamp;
			Property prop_siegeWarCamp = pdatas[9];
			if(prop_siegeWarCamp.isBase())
			{
				if(inited && !inWorld)
					onSiegeWarCampChanged(oldval_siegeWarCamp);
			}
			else
			{
				if(inWorld)
				{
					if(prop_siegeWarCamp.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onSiegeWarCampChanged(oldval_siegeWarCamp);
					}
				}
			}

			UInt32 oldval_spaceNo = spaceNo;
			Property prop_spaceNo = pdatas[10];
			if(prop_spaceNo.isBase())
			{
				if(inited && !inWorld)
					onSpaceNoChanged(oldval_spaceNo);
			}
			else
			{
				if(inWorld)
				{
					if(prop_spaceNo.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onSpaceNoChanged(oldval_spaceNo);
					}
				}
			}

			float oldval_speed = speed;
			Property prop_speed = pdatas[169];
			if(prop_speed.isBase())
			{
				if(inited && !inWorld)
					onSpeedChanged(oldval_speed);
			}
			else
			{
				if(inWorld)
				{
					if(prop_speed.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onSpeedChanged(oldval_speed);
					}
				}
			}

			Int64 oldval_state = state;
			Property prop_state = pdatas[12];
			if(prop_state.isBase())
			{
				if(inited && !inWorld)
					onStateChanged(oldval_state);
			}
			else
			{
				if(inWorld)
				{
					if(prop_state.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onStateChanged(oldval_state);
					}
				}
			}

			Int64 oldval_state2 = state2;
			Property prop_state2 = pdatas[13];
			if(prop_state2.isBase())
			{
				if(inited && !inWorld)
					onState2Changed(oldval_state2);
			}
			else
			{
				if(inWorld)
				{
					if(prop_state2.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onState2Changed(oldval_state2);
					}
				}
			}

		}
	}
}