syntax = "proto3";

package adminGsManager;
option go_package = "../gsmanager";

option py_generic_services = true;

message Void {
}

message CommandInfo
{
    bytes uuid = 1;
    string account = 2;     //account name
    string command = 3;     //gm command
}

message CommandResult
{
    bytes uuid = 1;
    string account = 2;
    uint32 resultCode = 3;
    string result = 4;    //command result
}

message ServerInfoMessage
{
    uint32 serverId = 1;  //serverId
    uint32 compId = 2;
    string serverName = 3;  //serverName
}

message HttpAPICommand
{
    string uuid = 1;
    string cmd = 2;
    string args = 3;
    string seqId = 4;
}

message HttpAPICommandResponse
{
    string uuid = 1;
    int32 result = 2;
    string retErrMsg = 3;
    bytes body = 4;
}

// gm 进程的 service
service Admin
{
    rpc registerServer(ServerInfoMessage) returns(Void);
    rpc doReplyCommand(CommandResult) returns(Void);
    rpc activeTick(Void) returns(Void);
    rpc replyHttpCommand(HttpAPICommandResponse) returns(Void);
}

// game 的 service
service GameServer
{
    rpc doCommand(CommandInfo) returns(Void);
    rpc doHttpCommand(HttpAPICommand) returns(Void);
    rpc activeTickCallback(Void) returns(Void);
}
