# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gf_ranking.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gf_ranking.proto',
  package='gfranking',
  syntax='proto3',
  serialized_options=_b('Z\007./proto'),
  serialized_pb=_b('\n\x10gf_ranking.proto\x12\tgfranking\"y\n\x0cupdateTopReq\x12\x10\n\x08serverId\x18\x01 \x01(\r\x12\x0f\n\x07topType\x18\x02 \x01(\r\x12\x0b\n\x03uid\x18\x03 \x01(\x03\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x0e\n\x06gender\x18\x05 \x01(\r\x12\x0c\n\x04icon\x18\x06 \x01(\r\x12\r\n\x05value\x18\x07 \x01(\x04\"\x1f\n\rupdateTopResp\x12\x0e\n\x06result\x18\x01 \x01(\x08\"S\n\x0cqueryRankReq\x12\x0f\n\x07topType\x18\x01 \x01(\r\x12\x10\n\x08serverId\x18\x02 \x01(\r\x12\x0f\n\x07userArg\x18\x03 \x01(\x04\x12\x0f\n\x07rankNum\x18\x04 \x01(\r\"k\n\rqueryRankResp\x12/\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32!.gfranking.queryRankResp.rankData\x12\x0f\n\x07userArg\x18\x02 \x01(\x04\x1a\x18\n\x08rankData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x03\x32\x8d\x01\n\x07ranking\x12\x42\n\rupdateTopList\x12\x17.gfranking.updateTopReq\x1a\x18.gfranking.updateTopResp\x12>\n\tqueryRank\x12\x17.gfranking.queryRankReq\x1a\x18.gfranking.queryRankRespB\tZ\x07./protob\x06proto3')
)




_UPDATETOPREQ = _descriptor.Descriptor(
  name='updateTopReq',
  full_name='gfranking.updateTopReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='serverId', full_name='gfranking.updateTopReq.serverId', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='topType', full_name='gfranking.updateTopReq.topType', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uid', full_name='gfranking.updateTopReq.uid', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='gfranking.updateTopReq.name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gender', full_name='gfranking.updateTopReq.gender', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='icon', full_name='gfranking.updateTopReq.icon', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='gfranking.updateTopReq.value', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=152,
)


_UPDATETOPRESP = _descriptor.Descriptor(
  name='updateTopResp',
  full_name='gfranking.updateTopResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='gfranking.updateTopResp.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=185,
)


_QUERYRANKREQ = _descriptor.Descriptor(
  name='queryRankReq',
  full_name='gfranking.queryRankReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topType', full_name='gfranking.queryRankReq.topType', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serverId', full_name='gfranking.queryRankReq.serverId', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userArg', full_name='gfranking.queryRankReq.userArg', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rankNum', full_name='gfranking.queryRankReq.rankNum', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=270,
)


_QUERYRANKRESP_RANKDATA = _descriptor.Descriptor(
  name='rankData',
  full_name='gfranking.queryRankResp.rankData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='gfranking.queryRankResp.rankData.data', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=355,
  serialized_end=379,
)

_QUERYRANKRESP = _descriptor.Descriptor(
  name='queryRankResp',
  full_name='gfranking.queryRankResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='gfranking.queryRankResp.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userArg', full_name='gfranking.queryRankResp.userArg', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_QUERYRANKRESP_RANKDATA, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=379,
)

_QUERYRANKRESP_RANKDATA.containing_type = _QUERYRANKRESP
_QUERYRANKRESP.fields_by_name['data'].message_type = _QUERYRANKRESP_RANKDATA
DESCRIPTOR.message_types_by_name['updateTopReq'] = _UPDATETOPREQ
DESCRIPTOR.message_types_by_name['updateTopResp'] = _UPDATETOPRESP
DESCRIPTOR.message_types_by_name['queryRankReq'] = _QUERYRANKREQ
DESCRIPTOR.message_types_by_name['queryRankResp'] = _QUERYRANKRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

updateTopReq = _reflection.GeneratedProtocolMessageType('updateTopReq', (_message.Message,), dict(
  DESCRIPTOR = _UPDATETOPREQ,
  __module__ = 'gf_ranking_pb2'
  # @@protoc_insertion_point(class_scope:gfranking.updateTopReq)
  ))
_sym_db.RegisterMessage(updateTopReq)

updateTopResp = _reflection.GeneratedProtocolMessageType('updateTopResp', (_message.Message,), dict(
  DESCRIPTOR = _UPDATETOPRESP,
  __module__ = 'gf_ranking_pb2'
  # @@protoc_insertion_point(class_scope:gfranking.updateTopResp)
  ))
_sym_db.RegisterMessage(updateTopResp)

queryRankReq = _reflection.GeneratedProtocolMessageType('queryRankReq', (_message.Message,), dict(
  DESCRIPTOR = _QUERYRANKREQ,
  __module__ = 'gf_ranking_pb2'
  # @@protoc_insertion_point(class_scope:gfranking.queryRankReq)
  ))
_sym_db.RegisterMessage(queryRankReq)

queryRankResp = _reflection.GeneratedProtocolMessageType('queryRankResp', (_message.Message,), dict(

  rankData = _reflection.GeneratedProtocolMessageType('rankData', (_message.Message,), dict(
    DESCRIPTOR = _QUERYRANKRESP_RANKDATA,
    __module__ = 'gf_ranking_pb2'
    # @@protoc_insertion_point(class_scope:gfranking.queryRankResp.rankData)
    ))
  ,
  DESCRIPTOR = _QUERYRANKRESP,
  __module__ = 'gf_ranking_pb2'
  # @@protoc_insertion_point(class_scope:gfranking.queryRankResp)
  ))
_sym_db.RegisterMessage(queryRankResp)
_sym_db.RegisterMessage(queryRankResp.rankData)


DESCRIPTOR._options = None

_RANKING = _descriptor.ServiceDescriptor(
  name='ranking',
  full_name='gfranking.ranking',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=382,
  serialized_end=523,
  methods=[
  _descriptor.MethodDescriptor(
    name='updateTopList',
    full_name='gfranking.ranking.updateTopList',
    index=0,
    containing_service=None,
    input_type=_UPDATETOPREQ,
    output_type=_UPDATETOPRESP,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='queryRank',
    full_name='gfranking.ranking.queryRank',
    index=1,
    containing_service=None,
    input_type=_QUERYRANKREQ,
    output_type=_QUERYRANKRESP,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RANKING)

DESCRIPTOR.services_by_name['ranking'] = _RANKING

# @@protoc_insertion_point(module_scope)
