# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gf_ranking_server.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import gf_ranking_pb2 as gf__ranking__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gf_ranking_server.proto',
  package='gfranking',
  syntax='proto3',
  serialized_options=_b('Z\007./proto\220\001\001'),
  serialized_pb=_b('\n\x17gf_ranking_server.proto\x12\tgfranking\x1a\x10gf_ranking.proto\"\x06\n\x04Void\"\x1f\n\x0bRankTypeReq\x12\x10\n\x08rankType\x18\x01 \x01(\r\"4\n\x0f\x46inalizeRankReq\x12\x10\n\x08rankType\x18\x01 \x01(\r\x12\x0f\n\x07rankNum\x18\x02 \x01(\r\"\x1d\n\rdeleteRankReq\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\r\"/\n\x0e\x64\x65leteRankResp\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\r\x12\x0f\n\x07reqdata\x18\x02 \x03(\r2\xe0\x02\n\rRankingServer\x12\x39\n\rupdateTopList\x12\x17.gfranking.updateTopReq\x1a\x0f.gfranking.Void\x12\x35\n\tqueryRank\x12\x17.gfranking.queryRankReq\x1a\x0f.gfranking.Void\x12;\n\x0c\x66inalizeRank\x12\x1a.gfranking.FinalizeRankReq\x1a\x0f.gfranking.Void\x12\x37\n\x0cregisterRank\x12\x16.gfranking.RankTypeReq\x1a\x0f.gfranking.Void\x12.\n\nactiveTick\x12\x0f.gfranking.Void\x1a\x0f.gfranking.Void\x12\x37\n\ndeleteRank\x12\x18.gfranking.deleteRankReq\x1a\x0f.gfranking.Void2\xb8\x01\n\nGameServer\x12\x36\n\tonGetRank\x12\x18.gfranking.queryRankResp\x1a\x0f.gfranking.Void\x12\x36\n\x12\x61\x63tiveTickCallback\x12\x0f.gfranking.Void\x1a\x0f.gfranking.Void\x12:\n\x0conDeleteRank\x12\x19.gfranking.deleteRankResp\x1a\x0f.gfranking.VoidB\x0cZ\x07./proto\x90\x01\x01\x62\x06proto3')
  ,
  dependencies=[gf__ranking__pb2.DESCRIPTOR,])




_VOID = _descriptor.Descriptor(
  name='Void',
  full_name='gfranking.Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=62,
)


_RANKTYPEREQ = _descriptor.Descriptor(
  name='RankTypeReq',
  full_name='gfranking.RankTypeReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rankType', full_name='gfranking.RankTypeReq.rankType', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=95,
)


_FINALIZERANKREQ = _descriptor.Descriptor(
  name='FinalizeRankReq',
  full_name='gfranking.FinalizeRankReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rankType', full_name='gfranking.FinalizeRankReq.rankType', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rankNum', full_name='gfranking.FinalizeRankReq.rankNum', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=149,
)


_DELETERANKREQ = _descriptor.Descriptor(
  name='deleteRankReq',
  full_name='gfranking.deleteRankReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='gfranking.deleteRankReq.data', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=180,
)


_DELETERANKRESP = _descriptor.Descriptor(
  name='deleteRankResp',
  full_name='gfranking.deleteRankResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='gfranking.deleteRankResp.data', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reqdata', full_name='gfranking.deleteRankResp.reqdata', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=229,
)

DESCRIPTOR.message_types_by_name['Void'] = _VOID
DESCRIPTOR.message_types_by_name['RankTypeReq'] = _RANKTYPEREQ
DESCRIPTOR.message_types_by_name['FinalizeRankReq'] = _FINALIZERANKREQ
DESCRIPTOR.message_types_by_name['deleteRankReq'] = _DELETERANKREQ
DESCRIPTOR.message_types_by_name['deleteRankResp'] = _DELETERANKRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), dict(
  DESCRIPTOR = _VOID,
  __module__ = 'gf_ranking_server_pb2'
  # @@protoc_insertion_point(class_scope:gfranking.Void)
  ))
_sym_db.RegisterMessage(Void)

RankTypeReq = _reflection.GeneratedProtocolMessageType('RankTypeReq', (_message.Message,), dict(
  DESCRIPTOR = _RANKTYPEREQ,
  __module__ = 'gf_ranking_server_pb2'
  # @@protoc_insertion_point(class_scope:gfranking.RankTypeReq)
  ))
_sym_db.RegisterMessage(RankTypeReq)

FinalizeRankReq = _reflection.GeneratedProtocolMessageType('FinalizeRankReq', (_message.Message,), dict(
  DESCRIPTOR = _FINALIZERANKREQ,
  __module__ = 'gf_ranking_server_pb2'
  # @@protoc_insertion_point(class_scope:gfranking.FinalizeRankReq)
  ))
_sym_db.RegisterMessage(FinalizeRankReq)

deleteRankReq = _reflection.GeneratedProtocolMessageType('deleteRankReq', (_message.Message,), dict(
  DESCRIPTOR = _DELETERANKREQ,
  __module__ = 'gf_ranking_server_pb2'
  # @@protoc_insertion_point(class_scope:gfranking.deleteRankReq)
  ))
_sym_db.RegisterMessage(deleteRankReq)

deleteRankResp = _reflection.GeneratedProtocolMessageType('deleteRankResp', (_message.Message,), dict(
  DESCRIPTOR = _DELETERANKRESP,
  __module__ = 'gf_ranking_server_pb2'
  # @@protoc_insertion_point(class_scope:gfranking.deleteRankResp)
  ))
_sym_db.RegisterMessage(deleteRankResp)


DESCRIPTOR._options = None

_RANKINGSERVER = _descriptor.ServiceDescriptor(
  name='RankingServer',
  full_name='gfranking.RankingServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=232,
  serialized_end=584,
  methods=[
  _descriptor.MethodDescriptor(
    name='updateTopList',
    full_name='gfranking.RankingServer.updateTopList',
    index=0,
    containing_service=None,
    input_type=gf__ranking__pb2._UPDATETOPREQ,
    output_type=_VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='queryRank',
    full_name='gfranking.RankingServer.queryRank',
    index=1,
    containing_service=None,
    input_type=gf__ranking__pb2._QUERYRANKREQ,
    output_type=_VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='finalizeRank',
    full_name='gfranking.RankingServer.finalizeRank',
    index=2,
    containing_service=None,
    input_type=_FINALIZERANKREQ,
    output_type=_VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='registerRank',
    full_name='gfranking.RankingServer.registerRank',
    index=3,
    containing_service=None,
    input_type=_RANKTYPEREQ,
    output_type=_VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='activeTick',
    full_name='gfranking.RankingServer.activeTick',
    index=4,
    containing_service=None,
    input_type=_VOID,
    output_type=_VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='deleteRank',
    full_name='gfranking.RankingServer.deleteRank',
    index=5,
    containing_service=None,
    input_type=_DELETERANKREQ,
    output_type=_VOID,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RANKINGSERVER)

DESCRIPTOR.services_by_name['RankingServer'] = _RANKINGSERVER


_GAMESERVER = _descriptor.ServiceDescriptor(
  name='GameServer',
  full_name='gfranking.GameServer',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=587,
  serialized_end=771,
  methods=[
  _descriptor.MethodDescriptor(
    name='onGetRank',
    full_name='gfranking.GameServer.onGetRank',
    index=0,
    containing_service=None,
    input_type=gf__ranking__pb2._QUERYRANKRESP,
    output_type=_VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='activeTickCallback',
    full_name='gfranking.GameServer.activeTickCallback',
    index=1,
    containing_service=None,
    input_type=_VOID,
    output_type=_VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='onDeleteRank',
    full_name='gfranking.GameServer.onDeleteRank',
    index=2,
    containing_service=None,
    input_type=_DELETERANKRESP,
    output_type=_VOID,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GAMESERVER)

DESCRIPTOR.services_by_name['GameServer'] = _GAMESERVER

RankingServer = service_reflection.GeneratedServiceType('RankingServer', (_service.Service,), dict(
  DESCRIPTOR = _RANKINGSERVER,
  __module__ = 'gf_ranking_server_pb2'
  ))

RankingServer_Stub = service_reflection.GeneratedServiceStubType('RankingServer_Stub', (RankingServer,), dict(
  DESCRIPTOR = _RANKINGSERVER,
  __module__ = 'gf_ranking_server_pb2'
  ))


GameServer = service_reflection.GeneratedServiceType('GameServer', (_service.Service,), dict(
  DESCRIPTOR = _GAMESERVER,
  __module__ = 'gf_ranking_server_pb2'
  ))

GameServer_Stub = service_reflection.GeneratedServiceStubType('GameServer_Stub', (GameServer,), dict(
  DESCRIPTOR = _GAMESERVER,
  __module__ = 'gf_ranking_server_pb2'
  ))


# @@protoc_insertion_point(module_scope)
