# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interface.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='interface.proto',
  package='gameInterface',
  syntax='proto3',
  serialized_options=_b('\220\001\001'),
  serialized_pb=_b('\n\x0finterface.proto\x12\rgameInterface\"\x06\n\x04Void\"&\n\tConfigVal\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03val\x18\x02 \x01(\t\"\x17\n\x07ListVal\x12\x0c\n\x04vals\x18\x01 \x03(\t\"\x17\n\x06IntVal\x12\r\n\x05value\x18\x01 \x01(\r\"J\n\x11SetAccountCompVal\x12\x13\n\x0b\x61\x63\x63ountName\x18\x01 \x01(\t\x12\x0e\n\x06\x63ompID\x18\x02 \x01(\x04\x12\x10\n\x08\x65ntityID\x18\x03 \x01(\r\"8\n\x14SetAccountCompResult\x12\x0e\n\x06result\x18\x01 \x01(\r\x12\x10\n\x08\x65ntityID\x18\x02 \x01(\r\"8\n\x11\x41ntiAddictionData\x12\x10\n\x08timeType\x18\x01 \x01(\r\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\"\x1f\n\x0fMapleServerInfo\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2\xca\x05\n\tInterface\x12K\n\x1agameConfigChangedOnBaseapp\x12\x18.gameInterface.ConfigVal\x1a\x13.gameInterface.Void\x12\x45\n\x14\x63\x61\x63heConfigOnBaseapp\x12\x18.gameInterface.ConfigVal\x1a\x13.gameInterface.Void\x12I\n\x18syncCacheConfigOnBaseapp\x12\x18.gameInterface.ConfigVal\x1a\x13.gameInterface.Void\x12\x36\n\nactiveTick\x12\x13.gameInterface.Void\x1a\x13.gameInterface.Void\x12;\n\x0finterfaceReload\x12\x13.gameInterface.Void\x1a\x13.gameInterface.Void\x12\x42\n\x13interfaceDataReload\x12\x16.gameInterface.ListVal\x1a\x13.gameInterface.Void\x12?\n\x11syncRegisterCount\x12\x15.gameInterface.IntVal\x1a\x13.gameInterface.Void\x12G\n\x0esetAccountComp\x12 .gameInterface.SetAccountCompVal\x1a\x13.gameInterface.Void\x12P\n\x17updateAntiAddictionData\x12 .gameInterface.AntiAddictionData\x1a\x13.gameInterface.Void\x12I\n\x12setMapleServerInfo\x12\x1e.gameInterface.MapleServerInfo\x1a\x13.gameInterface.Void2\xe4\x01\n\x07\x42\x61seApp\x12>\n\x12\x61\x63tiveTickCallback\x12\x13.gameInterface.Void\x1a\x13.gameInterface.Void\x12G\n\x1breqSyncCacheConfigOnBaseapp\x12\x13.gameInterface.Void\x1a\x13.gameInterface.Void\x12P\n\x14setAccountCompResult\x12#.gameInterface.SetAccountCompResult\x1a\x13.gameInterface.VoidB\x03\x90\x01\x01\x62\x06proto3')
)




_VOID = _descriptor.Descriptor(
  name='Void',
  full_name='gameInterface.Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=40,
)


_CONFIGVAL = _descriptor.Descriptor(
  name='ConfigVal',
  full_name='gameInterface.ConfigVal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='gameInterface.ConfigVal.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='val', full_name='gameInterface.ConfigVal.val', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=80,
)


_LISTVAL = _descriptor.Descriptor(
  name='ListVal',
  full_name='gameInterface.ListVal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vals', full_name='gameInterface.ListVal.vals', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=105,
)


_INTVAL = _descriptor.Descriptor(
  name='IntVal',
  full_name='gameInterface.IntVal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='gameInterface.IntVal.value', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=130,
)


_SETACCOUNTCOMPVAL = _descriptor.Descriptor(
  name='SetAccountCompVal',
  full_name='gameInterface.SetAccountCompVal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='accountName', full_name='gameInterface.SetAccountCompVal.accountName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='compID', full_name='gameInterface.SetAccountCompVal.compID', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entityID', full_name='gameInterface.SetAccountCompVal.entityID', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=206,
)


_SETACCOUNTCOMPRESULT = _descriptor.Descriptor(
  name='SetAccountCompResult',
  full_name='gameInterface.SetAccountCompResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='gameInterface.SetAccountCompResult.result', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entityID', full_name='gameInterface.SetAccountCompResult.entityID', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=264,
)


_ANTIADDICTIONDATA = _descriptor.Descriptor(
  name='AntiAddictionData',
  full_name='gameInterface.AntiAddictionData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeType', full_name='gameInterface.AntiAddictionData.timeType', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='gameInterface.AntiAddictionData.timestamp', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=322,
)


_MAPLESERVERINFO = _descriptor.Descriptor(
  name='MapleServerInfo',
  full_name='gameInterface.MapleServerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='gameInterface.MapleServerInfo.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=324,
  serialized_end=355,
)

DESCRIPTOR.message_types_by_name['Void'] = _VOID
DESCRIPTOR.message_types_by_name['ConfigVal'] = _CONFIGVAL
DESCRIPTOR.message_types_by_name['ListVal'] = _LISTVAL
DESCRIPTOR.message_types_by_name['IntVal'] = _INTVAL
DESCRIPTOR.message_types_by_name['SetAccountCompVal'] = _SETACCOUNTCOMPVAL
DESCRIPTOR.message_types_by_name['SetAccountCompResult'] = _SETACCOUNTCOMPRESULT
DESCRIPTOR.message_types_by_name['AntiAddictionData'] = _ANTIADDICTIONDATA
DESCRIPTOR.message_types_by_name['MapleServerInfo'] = _MAPLESERVERINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), dict(
  DESCRIPTOR = _VOID,
  __module__ = 'interface_pb2'
  # @@protoc_insertion_point(class_scope:gameInterface.Void)
  ))
_sym_db.RegisterMessage(Void)

ConfigVal = _reflection.GeneratedProtocolMessageType('ConfigVal', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGVAL,
  __module__ = 'interface_pb2'
  # @@protoc_insertion_point(class_scope:gameInterface.ConfigVal)
  ))
_sym_db.RegisterMessage(ConfigVal)

ListVal = _reflection.GeneratedProtocolMessageType('ListVal', (_message.Message,), dict(
  DESCRIPTOR = _LISTVAL,
  __module__ = 'interface_pb2'
  # @@protoc_insertion_point(class_scope:gameInterface.ListVal)
  ))
_sym_db.RegisterMessage(ListVal)

IntVal = _reflection.GeneratedProtocolMessageType('IntVal', (_message.Message,), dict(
  DESCRIPTOR = _INTVAL,
  __module__ = 'interface_pb2'
  # @@protoc_insertion_point(class_scope:gameInterface.IntVal)
  ))
_sym_db.RegisterMessage(IntVal)

SetAccountCompVal = _reflection.GeneratedProtocolMessageType('SetAccountCompVal', (_message.Message,), dict(
  DESCRIPTOR = _SETACCOUNTCOMPVAL,
  __module__ = 'interface_pb2'
  # @@protoc_insertion_point(class_scope:gameInterface.SetAccountCompVal)
  ))
_sym_db.RegisterMessage(SetAccountCompVal)

SetAccountCompResult = _reflection.GeneratedProtocolMessageType('SetAccountCompResult', (_message.Message,), dict(
  DESCRIPTOR = _SETACCOUNTCOMPRESULT,
  __module__ = 'interface_pb2'
  # @@protoc_insertion_point(class_scope:gameInterface.SetAccountCompResult)
  ))
_sym_db.RegisterMessage(SetAccountCompResult)

AntiAddictionData = _reflection.GeneratedProtocolMessageType('AntiAddictionData', (_message.Message,), dict(
  DESCRIPTOR = _ANTIADDICTIONDATA,
  __module__ = 'interface_pb2'
  # @@protoc_insertion_point(class_scope:gameInterface.AntiAddictionData)
  ))
_sym_db.RegisterMessage(AntiAddictionData)

MapleServerInfo = _reflection.GeneratedProtocolMessageType('MapleServerInfo', (_message.Message,), dict(
  DESCRIPTOR = _MAPLESERVERINFO,
  __module__ = 'interface_pb2'
  # @@protoc_insertion_point(class_scope:gameInterface.MapleServerInfo)
  ))
_sym_db.RegisterMessage(MapleServerInfo)


DESCRIPTOR._options = None

_INTERFACE = _descriptor.ServiceDescriptor(
  name='Interface',
  full_name='gameInterface.Interface',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=358,
  serialized_end=1072,
  methods=[
  _descriptor.MethodDescriptor(
    name='gameConfigChangedOnBaseapp',
    full_name='gameInterface.Interface.gameConfigChangedOnBaseapp',
    index=0,
    containing_service=None,
    input_type=_CONFIGVAL,
    output_type=_VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='cacheConfigOnBaseapp',
    full_name='gameInterface.Interface.cacheConfigOnBaseapp',
    index=1,
    containing_service=None,
    input_type=_CONFIGVAL,
    output_type=_VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='syncCacheConfigOnBaseapp',
    full_name='gameInterface.Interface.syncCacheConfigOnBaseapp',
    index=2,
    containing_service=None,
    input_type=_CONFIGVAL,
    output_type=_VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='activeTick',
    full_name='gameInterface.Interface.activeTick',
    index=3,
    containing_service=None,
    input_type=_VOID,
    output_type=_VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='interfaceReload',
    full_name='gameInterface.Interface.interfaceReload',
    index=4,
    containing_service=None,
    input_type=_VOID,
    output_type=_VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='interfaceDataReload',
    full_name='gameInterface.Interface.interfaceDataReload',
    index=5,
    containing_service=None,
    input_type=_LISTVAL,
    output_type=_VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='syncRegisterCount',
    full_name='gameInterface.Interface.syncRegisterCount',
    index=6,
    containing_service=None,
    input_type=_INTVAL,
    output_type=_VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='setAccountComp',
    full_name='gameInterface.Interface.setAccountComp',
    index=7,
    containing_service=None,
    input_type=_SETACCOUNTCOMPVAL,
    output_type=_VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='updateAntiAddictionData',
    full_name='gameInterface.Interface.updateAntiAddictionData',
    index=8,
    containing_service=None,
    input_type=_ANTIADDICTIONDATA,
    output_type=_VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='setMapleServerInfo',
    full_name='gameInterface.Interface.setMapleServerInfo',
    index=9,
    containing_service=None,
    input_type=_MAPLESERVERINFO,
    output_type=_VOID,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_INTERFACE)

DESCRIPTOR.services_by_name['Interface'] = _INTERFACE


_BASEAPP = _descriptor.ServiceDescriptor(
  name='BaseApp',
  full_name='gameInterface.BaseApp',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=1075,
  serialized_end=1303,
  methods=[
  _descriptor.MethodDescriptor(
    name='activeTickCallback',
    full_name='gameInterface.BaseApp.activeTickCallback',
    index=0,
    containing_service=None,
    input_type=_VOID,
    output_type=_VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='reqSyncCacheConfigOnBaseapp',
    full_name='gameInterface.BaseApp.reqSyncCacheConfigOnBaseapp',
    index=1,
    containing_service=None,
    input_type=_VOID,
    output_type=_VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='setAccountCompResult',
    full_name='gameInterface.BaseApp.setAccountCompResult',
    index=2,
    containing_service=None,
    input_type=_SETACCOUNTCOMPRESULT,
    output_type=_VOID,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BASEAPP)

DESCRIPTOR.services_by_name['BaseApp'] = _BASEAPP

Interface = service_reflection.GeneratedServiceType('Interface', (_service.Service,), dict(
  DESCRIPTOR = _INTERFACE,
  __module__ = 'interface_pb2'
  ))

Interface_Stub = service_reflection.GeneratedServiceStubType('Interface_Stub', (Interface,), dict(
  DESCRIPTOR = _INTERFACE,
  __module__ = 'interface_pb2'
  ))


BaseApp = service_reflection.GeneratedServiceType('BaseApp', (_service.Service,), dict(
  DESCRIPTOR = _BASEAPP,
  __module__ = 'interface_pb2'
  ))

BaseApp_Stub = service_reflection.GeneratedServiceStubType('BaseApp_Stub', (BaseApp,), dict(
  DESCRIPTOR = _BASEAPP,
  __module__ = 'interface_pb2'
  ))


# @@protoc_insertion_point(module_scope)
