# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ranking_server.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ranking_pb2 as ranking__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ranking_server.proto',
  package='ranking',
  syntax='proto3',
  serialized_options=_b('Z\007./proto\220\001\001'),
  serialized_pb=_b('\n\x14ranking_server.proto\x12\x07ranking\x1a\rranking.proto\"\x06\n\x04Void\"\x1f\n\x0bRankTypeReq\x12\x10\n\x08rankType\x18\x01 \x01(\r\"4\n\x0f\x46inalizeRankReq\x12\x10\n\x08rankType\x18\x01 \x01(\r\x12\x0f\n\x07rankNum\x18\x02 \x01(\r\"\x1d\n\rdeleteRankReq\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\r\"/\n\x0e\x64\x65leteRankResp\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\r\x12\x0f\n\x07reqdata\x18\x02 \x03(\r2\xc8\x02\n\rRankingServer\x12\x35\n\rupdateTopList\x12\x15.ranking.updateTopReq\x1a\r.ranking.Void\x12\x31\n\tqueryRank\x12\x15.ranking.queryRankReq\x1a\r.ranking.Void\x12\x37\n\x0c\x66inalizeRank\x12\x18.ranking.FinalizeRankReq\x1a\r.ranking.Void\x12\x33\n\x0cregisterRank\x12\x14.ranking.RankTypeReq\x1a\r.ranking.Void\x12*\n\nactiveTick\x12\r.ranking.Void\x1a\r.ranking.Void\x12\x33\n\ndeleteRank\x12\x16.ranking.deleteRankReq\x1a\r.ranking.Void2\xac\x01\n\nGameServer\x12\x32\n\tonGetRank\x12\x16.ranking.queryRankResp\x1a\r.ranking.Void\x12\x32\n\x12\x61\x63tiveTickCallback\x12\r.ranking.Void\x1a\r.ranking.Void\x12\x36\n\x0conDeleteRank\x12\x17.ranking.deleteRankResp\x1a\r.ranking.VoidB\x0cZ\x07./proto\x90\x01\x01\x62\x06proto3')
  ,
  dependencies=[ranking__pb2.DESCRIPTOR,])




_VOID = _descriptor.Descriptor(
  name='Void',
  full_name='ranking.Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=54,
)


_RANKTYPEREQ = _descriptor.Descriptor(
  name='RankTypeReq',
  full_name='ranking.RankTypeReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rankType', full_name='ranking.RankTypeReq.rankType', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=87,
)


_FINALIZERANKREQ = _descriptor.Descriptor(
  name='FinalizeRankReq',
  full_name='ranking.FinalizeRankReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rankType', full_name='ranking.FinalizeRankReq.rankType', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rankNum', full_name='ranking.FinalizeRankReq.rankNum', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=141,
)


_DELETERANKREQ = _descriptor.Descriptor(
  name='deleteRankReq',
  full_name='ranking.deleteRankReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='ranking.deleteRankReq.data', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=172,
)


_DELETERANKRESP = _descriptor.Descriptor(
  name='deleteRankResp',
  full_name='ranking.deleteRankResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='ranking.deleteRankResp.data', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reqdata', full_name='ranking.deleteRankResp.reqdata', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=221,
)

DESCRIPTOR.message_types_by_name['Void'] = _VOID
DESCRIPTOR.message_types_by_name['RankTypeReq'] = _RANKTYPEREQ
DESCRIPTOR.message_types_by_name['FinalizeRankReq'] = _FINALIZERANKREQ
DESCRIPTOR.message_types_by_name['deleteRankReq'] = _DELETERANKREQ
DESCRIPTOR.message_types_by_name['deleteRankResp'] = _DELETERANKRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), dict(
  DESCRIPTOR = _VOID,
  __module__ = 'ranking_server_pb2'
  # @@protoc_insertion_point(class_scope:ranking.Void)
  ))
_sym_db.RegisterMessage(Void)

RankTypeReq = _reflection.GeneratedProtocolMessageType('RankTypeReq', (_message.Message,), dict(
  DESCRIPTOR = _RANKTYPEREQ,
  __module__ = 'ranking_server_pb2'
  # @@protoc_insertion_point(class_scope:ranking.RankTypeReq)
  ))
_sym_db.RegisterMessage(RankTypeReq)

FinalizeRankReq = _reflection.GeneratedProtocolMessageType('FinalizeRankReq', (_message.Message,), dict(
  DESCRIPTOR = _FINALIZERANKREQ,
  __module__ = 'ranking_server_pb2'
  # @@protoc_insertion_point(class_scope:ranking.FinalizeRankReq)
  ))
_sym_db.RegisterMessage(FinalizeRankReq)

deleteRankReq = _reflection.GeneratedProtocolMessageType('deleteRankReq', (_message.Message,), dict(
  DESCRIPTOR = _DELETERANKREQ,
  __module__ = 'ranking_server_pb2'
  # @@protoc_insertion_point(class_scope:ranking.deleteRankReq)
  ))
_sym_db.RegisterMessage(deleteRankReq)

deleteRankResp = _reflection.GeneratedProtocolMessageType('deleteRankResp', (_message.Message,), dict(
  DESCRIPTOR = _DELETERANKRESP,
  __module__ = 'ranking_server_pb2'
  # @@protoc_insertion_point(class_scope:ranking.deleteRankResp)
  ))
_sym_db.RegisterMessage(deleteRankResp)


DESCRIPTOR._options = None

_RANKINGSERVER = _descriptor.ServiceDescriptor(
  name='RankingServer',
  full_name='ranking.RankingServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=224,
  serialized_end=552,
  methods=[
  _descriptor.MethodDescriptor(
    name='updateTopList',
    full_name='ranking.RankingServer.updateTopList',
    index=0,
    containing_service=None,
    input_type=ranking__pb2._UPDATETOPREQ,
    output_type=_VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='queryRank',
    full_name='ranking.RankingServer.queryRank',
    index=1,
    containing_service=None,
    input_type=ranking__pb2._QUERYRANKREQ,
    output_type=_VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='finalizeRank',
    full_name='ranking.RankingServer.finalizeRank',
    index=2,
    containing_service=None,
    input_type=_FINALIZERANKREQ,
    output_type=_VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='registerRank',
    full_name='ranking.RankingServer.registerRank',
    index=3,
    containing_service=None,
    input_type=_RANKTYPEREQ,
    output_type=_VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='activeTick',
    full_name='ranking.RankingServer.activeTick',
    index=4,
    containing_service=None,
    input_type=_VOID,
    output_type=_VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='deleteRank',
    full_name='ranking.RankingServer.deleteRank',
    index=5,
    containing_service=None,
    input_type=_DELETERANKREQ,
    output_type=_VOID,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RANKINGSERVER)

DESCRIPTOR.services_by_name['RankingServer'] = _RANKINGSERVER


_GAMESERVER = _descriptor.ServiceDescriptor(
  name='GameServer',
  full_name='ranking.GameServer',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=555,
  serialized_end=727,
  methods=[
  _descriptor.MethodDescriptor(
    name='onGetRank',
    full_name='ranking.GameServer.onGetRank',
    index=0,
    containing_service=None,
    input_type=ranking__pb2._QUERYRANKRESP,
    output_type=_VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='activeTickCallback',
    full_name='ranking.GameServer.activeTickCallback',
    index=1,
    containing_service=None,
    input_type=_VOID,
    output_type=_VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='onDeleteRank',
    full_name='ranking.GameServer.onDeleteRank',
    index=2,
    containing_service=None,
    input_type=_DELETERANKRESP,
    output_type=_VOID,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GAMESERVER)

DESCRIPTOR.services_by_name['GameServer'] = _GAMESERVER

RankingServer = service_reflection.GeneratedServiceType('RankingServer', (_service.Service,), dict(
  DESCRIPTOR = _RANKINGSERVER,
  __module__ = 'ranking_server_pb2'
  ))

RankingServer_Stub = service_reflection.GeneratedServiceStubType('RankingServer_Stub', (RankingServer,), dict(
  DESCRIPTOR = _RANKINGSERVER,
  __module__ = 'ranking_server_pb2'
  ))


GameServer = service_reflection.GeneratedServiceType('GameServer', (_service.Service,), dict(
  DESCRIPTOR = _GAMESERVER,
  __module__ = 'ranking_server_pb2'
  ))

GameServer_Stub = service_reflection.GeneratedServiceStubType('GameServer_Stub', (GameServer,), dict(
  DESCRIPTOR = _GAMESERVER,
  __module__ = 'ranking_server_pb2'
  ))


# @@protoc_insertion_point(module_scope)
