# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orderService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='orderService.proto',
  package='OrderService',
  syntax='proto3',
  serialized_options=_b('H\003Z\n../service\220\001\001'),
  serialized_pb=_b('\n\x12orderService.proto\x12\x0cOrderService\"\x06\n\x04Void\"I\n\x11ServerInfoMessage\x12\x10\n\x08serverId\x18\x01 \x01(\r\x12\x0e\n\x06\x63ompId\x18\x02 \x01(\r\x12\x12\n\nserverName\x18\x03 \x01(\t\"\x9b\x01\n\x0cOrderRequest\x12\x10\n\x08serverId\x18\x01 \x01(\x05\x12\x12\n\noutTradeNo\x18\x02 \x01(\t\x12\x12\n\ncreateTime\x18\x03 \x01(\x03\x12\x0c\n\x04gbId\x18\x04 \x01(\x03\x12\x0e\n\x06itemId\x18\x05 \x01(\x05\x12\x11\n\titemCount\x18\x06 \x01(\x05\x12\r\n\x05price\x18\x07 \x01(\x01\x12\x11\n\taddToSafe\x18\x08 \x01(\x08\"3\n\rOrderResponse\x12\x12\n\noutTradeNo\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\x05*0\n\x07\x45RRCODE\x12\x0b\n\x07SUCCESS\x10\x00\x12\x08\n\x04\x46\x41IL\x10\x01\x12\x0e\n\nPROCESSING\x10\x02\x32\xcb\x01\n\x0cOrderService\x12\x45\n\x0eregisterServer\x12\x1f.OrderService.ServerInfoMessage\x1a\x12.OrderService.Void\x12\x34\n\nactiveTick\x12\x12.OrderService.Void\x1a\x12.OrderService.Void\x12>\n\x0b\x66inishOrder\x12\x1b.OrderService.OrderResponse\x1a\x12.OrderService.Void2\x89\x01\n\nGameServer\x12<\n\x12\x61\x63tiveTickCallback\x12\x12.OrderService.Void\x1a\x12.OrderService.Void\x12=\n\x0bnotifyOrder\x12\x1a.OrderService.OrderRequest\x1a\x12.OrderService.VoidB\x11H\x03Z\n../service\x90\x01\x01\x62\x06proto3')
)

_ERRCODE = _descriptor.EnumDescriptor(
  name='ERRCODE',
  full_name='OrderService.ERRCODE',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAIL', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROCESSING', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=330,
  serialized_end=378,
)
_sym_db.RegisterEnumDescriptor(_ERRCODE)

ERRCODE = enum_type_wrapper.EnumTypeWrapper(_ERRCODE)
SUCCESS = 0
FAIL = 1
PROCESSING = 2



_VOID = _descriptor.Descriptor(
  name='Void',
  full_name='OrderService.Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=42,
)


_SERVERINFOMESSAGE = _descriptor.Descriptor(
  name='ServerInfoMessage',
  full_name='OrderService.ServerInfoMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='serverId', full_name='OrderService.ServerInfoMessage.serverId', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='compId', full_name='OrderService.ServerInfoMessage.compId', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serverName', full_name='OrderService.ServerInfoMessage.serverName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=117,
)


_ORDERREQUEST = _descriptor.Descriptor(
  name='OrderRequest',
  full_name='OrderService.OrderRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='serverId', full_name='OrderService.OrderRequest.serverId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='outTradeNo', full_name='OrderService.OrderRequest.outTradeNo', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='createTime', full_name='OrderService.OrderRequest.createTime', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gbId', full_name='OrderService.OrderRequest.gbId', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='itemId', full_name='OrderService.OrderRequest.itemId', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='itemCount', full_name='OrderService.OrderRequest.itemCount', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='OrderService.OrderRequest.price', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='addToSafe', full_name='OrderService.OrderRequest.addToSafe', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=275,
)


_ORDERRESPONSE = _descriptor.Descriptor(
  name='OrderResponse',
  full_name='OrderService.OrderResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='outTradeNo', full_name='OrderService.OrderResponse.outTradeNo', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='OrderService.OrderResponse.result', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=277,
  serialized_end=328,
)

DESCRIPTOR.message_types_by_name['Void'] = _VOID
DESCRIPTOR.message_types_by_name['ServerInfoMessage'] = _SERVERINFOMESSAGE
DESCRIPTOR.message_types_by_name['OrderRequest'] = _ORDERREQUEST
DESCRIPTOR.message_types_by_name['OrderResponse'] = _ORDERRESPONSE
DESCRIPTOR.enum_types_by_name['ERRCODE'] = _ERRCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), dict(
  DESCRIPTOR = _VOID,
  __module__ = 'orderService_pb2'
  # @@protoc_insertion_point(class_scope:OrderService.Void)
  ))
_sym_db.RegisterMessage(Void)

ServerInfoMessage = _reflection.GeneratedProtocolMessageType('ServerInfoMessage', (_message.Message,), dict(
  DESCRIPTOR = _SERVERINFOMESSAGE,
  __module__ = 'orderService_pb2'
  # @@protoc_insertion_point(class_scope:OrderService.ServerInfoMessage)
  ))
_sym_db.RegisterMessage(ServerInfoMessage)

OrderRequest = _reflection.GeneratedProtocolMessageType('OrderRequest', (_message.Message,), dict(
  DESCRIPTOR = _ORDERREQUEST,
  __module__ = 'orderService_pb2'
  # @@protoc_insertion_point(class_scope:OrderService.OrderRequest)
  ))
_sym_db.RegisterMessage(OrderRequest)

OrderResponse = _reflection.GeneratedProtocolMessageType('OrderResponse', (_message.Message,), dict(
  DESCRIPTOR = _ORDERRESPONSE,
  __module__ = 'orderService_pb2'
  # @@protoc_insertion_point(class_scope:OrderService.OrderResponse)
  ))
_sym_db.RegisterMessage(OrderResponse)


DESCRIPTOR._options = None

_ORDERSERVICE = _descriptor.ServiceDescriptor(
  name='OrderService',
  full_name='OrderService.OrderService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=381,
  serialized_end=584,
  methods=[
  _descriptor.MethodDescriptor(
    name='registerServer',
    full_name='OrderService.OrderService.registerServer',
    index=0,
    containing_service=None,
    input_type=_SERVERINFOMESSAGE,
    output_type=_VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='activeTick',
    full_name='OrderService.OrderService.activeTick',
    index=1,
    containing_service=None,
    input_type=_VOID,
    output_type=_VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='finishOrder',
    full_name='OrderService.OrderService.finishOrder',
    index=2,
    containing_service=None,
    input_type=_ORDERRESPONSE,
    output_type=_VOID,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ORDERSERVICE)

DESCRIPTOR.services_by_name['OrderService'] = _ORDERSERVICE


_GAMESERVER = _descriptor.ServiceDescriptor(
  name='GameServer',
  full_name='OrderService.GameServer',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=587,
  serialized_end=724,
  methods=[
  _descriptor.MethodDescriptor(
    name='activeTickCallback',
    full_name='OrderService.GameServer.activeTickCallback',
    index=0,
    containing_service=None,
    input_type=_VOID,
    output_type=_VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='notifyOrder',
    full_name='OrderService.GameServer.notifyOrder',
    index=1,
    containing_service=None,
    input_type=_ORDERREQUEST,
    output_type=_VOID,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GAMESERVER)

DESCRIPTOR.services_by_name['GameServer'] = _GAMESERVER

OrderService = service_reflection.GeneratedServiceType('OrderService', (_service.Service,), dict(
  DESCRIPTOR = _ORDERSERVICE,
  __module__ = 'orderService_pb2'
  ))

OrderService_Stub = service_reflection.GeneratedServiceStubType('OrderService_Stub', (OrderService,), dict(
  DESCRIPTOR = _ORDERSERVICE,
  __module__ = 'orderService_pb2'
  ))


GameServer = service_reflection.GeneratedServiceType('GameServer', (_service.Service,), dict(
  DESCRIPTOR = _GAMESERVER,
  __module__ = 'orderService_pb2'
  ))

GameServer_Stub = service_reflection.GeneratedServiceStubType('GameServer_Stub', (GameServer,), dict(
  DESCRIPTOR = _GAMESERVER,
  __module__ = 'orderService_pb2'
  ))


# @@protoc_insertion_point(module_scope)
