// Generated by protobuf plugin.  DO NOT EDIT!

package service

import (
    prpc "centralService/src/trpc"
)

func OrderService_RegisterServer_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(ServerInfoMessage)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IOrderServiceInterface).RegisterServer(in)
}
func OrderService_ActiveTick_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(Void)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IOrderServiceInterface).ActiveTick(in)
}
func OrderService_FinishOrder_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(OrderResponse)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IOrderServiceInterface).FinishOrder(in)
}
var OrderServiceServiceDesc = prpc.ServiceDesc{
    ServiceName: "OrderService.OrderService",
    Methods: []prpc.MethodDesc{
        {
            MethodName:  "RegisterServer",
            MethodIndex: 0,
            Handler:     OrderService_RegisterServer_Handler,
        },
        {
            MethodName:  "ActiveTick",
            MethodIndex: 1,
            Handler:     OrderService_ActiveTick_Handler,
        },
        {
            MethodName:  "FinishOrder",
            MethodIndex: 2,
            Handler:     OrderService_FinishOrder_Handler,
        },
    },
}

func NewOrderServiceService(client prpc.IEndPoint) *prpc.ServerEndPoint {
    return &prpc.ServerEndPoint{&OrderServiceServiceDesc, client}
}

func NewOrderServiceClient(channel *prpc.RpcChannel) *OrderServiceClient {
    return &OrderServiceClient{prpc.ClientEndPoint{channel}}
}

type OrderServiceClient struct {
	prpc.ClientEndPoint
}
func (self *OrderServiceClient) RegisterServer(in *ServerInfoMessage) (*Void, error) {
    err := self.Channel.CallMethod(&OrderServiceServiceDesc.Methods[0], in)
    return &Void{}, err
}
func (self *OrderServiceClient) ActiveTick(in *Void) (*Void, error) {
    err := self.Channel.CallMethod(&OrderServiceServiceDesc.Methods[1], in)
    return &Void{}, err
}
func (self *OrderServiceClient) FinishOrder(in *OrderResponse) (*Void, error) {
    err := self.Channel.CallMethod(&OrderServiceServiceDesc.Methods[2], in)
    return &Void{}, err
}
type IOrderServiceInterface interface {
    RegisterServer(*ServerInfoMessage) (*Void, error)
    ActiveTick(*Void) (*Void, error)
    FinishOrder(*OrderResponse) (*Void, error)
}

func GameServer_ActiveTickCallback_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(Void)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).ActiveTickCallback(in)
}
func GameServer_NotifyOrder_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(OrderRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).NotifyOrder(in)
}
var GameServerServiceDesc = prpc.ServiceDesc{
    ServiceName: "OrderService.GameServer",
    Methods: []prpc.MethodDesc{
        {
            MethodName:  "ActiveTickCallback",
            MethodIndex: 0,
            Handler:     GameServer_ActiveTickCallback_Handler,
        },
        {
            MethodName:  "NotifyOrder",
            MethodIndex: 1,
            Handler:     GameServer_NotifyOrder_Handler,
        },
    },
}

func NewGameServerService(client prpc.IEndPoint) *prpc.ServerEndPoint {
    return &prpc.ServerEndPoint{&GameServerServiceDesc, client}
}

func NewGameServerClient(channel *prpc.RpcChannel) *GameServerClient {
    return &GameServerClient{prpc.ClientEndPoint{channel}}
}

type GameServerClient struct {
	prpc.ClientEndPoint
}
func (self *GameServerClient) ActiveTickCallback(in *Void) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[0], in)
    return &Void{}, err
}
func (self *GameServerClient) NotifyOrder(in *OrderRequest) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[1], in)
    return &Void{}, err
}
type IGameServerInterface interface {
    ActiveTickCallback(*Void) (*Void, error)
    NotifyOrder(*OrderRequest) (*Void, error)
}

