syntax = "proto3";

package CrossDataServer;
option go_package = "../gameServerService";
option py_generic_services = true;

message Void {

}

message RegisterGameServerRequest
{
    uint32 serverId = 1;
}

message GuildInfo {
    uint64 guildUUID = 1;
    string guildName = 2;
    uint32 serverId = 3;
    uint32 flag = 4;
    uint32 guildScore = 5;
    uint32 guildLevel = 6;
    uint32 guildIcon = 7;
    uint32 memberCnt = 8;
}

message GetEnemyGuildInfosRequest {
    uint64 guildUUID = 1;
    uint64 uuid = 2;
}

message EnemyGuildInfo {
    uint64 guildUUID = 1;
    string guildName = 2;
    uint32 serverId = 3;
    uint32 flag = 4;
    uint32 guildScore = 5;
    uint32 guildLevel = 6;
    uint32 endTime = 7;
    uint32 memberCnt = 8;
    uint32 guildIcon = 9;
}
message GetEnemyGuildInfosResult {
    repeated EnemyGuildInfo enemyGuildInfos = 1;
    uint64 uuid = 2;
}

message AddGuildInfoRequest {
    GuildInfo guildInfo = 1;
    uint64 uuid = 2;
}

message AddGuildInfoResult {
    uint64 uuid = 1;
}

message GetGuildInfosRequest {
    uint32 serverId = 1;
    uint64 uuid = 2;
}

message GetGuildInfosByGuildUUIDRequest {
    repeated uint64 guildUUIDs = 1;
    uint64 uuid = 2;
}

message GetGuildInfosResult {
    repeated GuildInfo guildInfos = 1;
    uint64 uuid = 2;
}

message RemoveGuildInfoRequest {
    uint64 guildUUID = 2;
}

message AddGuildRelationRequest {
    uint64 guildUUID1 = 1;
    uint64 guildUUID2 = 2;
    int32 relationType = 3;
    int64 endTime = 4;
    uint64 uuid = 5;
}

message AddGuildRelationResult {
    uint64 uuid = 1;
    bool success = 2;
    GuildInfo guildInfo = 3;
    uint32 errCode = 4;
}

message GuildRelation {
    uint64 guildUUID1 = 1;
    uint64 guildUUID2 = 2;
    int32 relationType = 3;
}

message BroadcastGuildRelationSingle {
    GuildRelation guildRelation = 1;
    uint32 version = 2;
}

message GuildRelationAll {
    repeated GuildRelation guildRelations = 1;
    uint32 version = 2;
}

message RemoveGuildRelationRequest {
    uint64 guildUUID1 = 1;
    uint64 guildUUID2 = 2;
    int32 relationType = 3;
    uint64 uuid = 4;
}

message RemoveGuildRelationResult {
    bool success = 1;
    uint64 uuid = 2;
    GuildInfo guildInfo = 3;
}

message BroadcastRemoveGuildRelation {
    uint64 guildUUID1 = 1;
    uint64 guildUUID2 = 2;
    uint32 version = 3;
}

message ApplyGuildUnionRequest {
    uint64 senderGuildUUID = 1;
    uint64 receiverGuildUUID = 2;
    uint64 uuid = 3;
}

message ApplyGuildUnionResult {
    uint64 uuid = 1;
    GuildInfo receiverGuildInfo = 2;
}

message OnApplyGuildUnionRequest {
    uint64 senderGuildUUID = 1;
    uint64 receiverGuildUUID = 2;
    GuildInfo senderGuildInfo = 3;
}

message OnNotifyGuildRelation {
    GuildInfo guildInfo = 1;
    int32 relationType = 2;
    uint64 receiverGuildUUID = 3;
}

message OnNotifyGuildCancelUnion {
    GuildInfo guildInfo = 1;
    uint64 receiverGuildUUID = 2;
}

message RemoveReceiverGuildApplyUnionRequest {
    uint64 senderGuildUUID = 1;
    uint64 receiverGuildUUID = 2;
}

message NotifyRemoveReceiverGuildApplyUnion {
    uint64 senderGuildUUID = 1;
    uint64 receiverGuildUUID = 2;
}

message GetCrossServerGuildDetailRequest {
    uint64 guildUUID = 1;
    uint32 senderServerId = 2;
    uint64 uuid = 3;
}

message GetCrossServerGuildDetailToOtherServer {
    uint64 guildUUID = 1;
    uint32 senderServerId = 2;
    uint64 uuid = 3;
}

message GuildDetailInfo {
    uint64 guildUUID = 1;
    string desc = 2;
    string leaderName = 3;
    uint32 leaderSex = 4;
    uint32 leaderSchool = 5;
    uint32 leaderLevel = 6;
    uint64 leaderGbId = 7;
}

message GetCrossServerGuildDetailFromOtherServer {
    GuildDetailInfo guildDetailInfo = 1;
    uint32 senderServerId = 2;
    uint64 uuid = 3;
}

message GetCrossServerGuildDetailResult {
    GuildDetailInfo guildDetailInfo = 1;
    uint64 uuid = 3;
}

message DoOnCrossGuildRequest {
    uint64 guildUUID = 1;
    string func = 2;
    bytes args = 3;
    uint64 uuid = 4;
}

message DoOnCrossGuildToGameServer {
    uint64 guildUUID = 1;
    string func = 2;
    bytes args = 3;
    uint64 uuid = 4;
    uint32 senderServerId = 5;
}

message DoOnCrossGuildResult {
    uint64 uuid = 1;
    bool success = 2;
    bytes result = 3;
}

message DoOnCrossGuildResultBack {
    uint64 uuid = 1;
    uint32 serverId = 2;
    bool success = 3;
    bytes result = 4;
}


service CrossDataServer
{
    rpc registerGameServer(RegisterGameServerRequest) returns (Void);
    rpc activeTick(Void) returns(Void);
    rpc addGuildInfo(AddGuildInfoRequest) returns(Void);
    rpc getGuildInfos(GetGuildInfosRequest) returns(Void);
    rpc getGuildInfosByGuildUUID(GetGuildInfosByGuildUUIDRequest) returns(Void);
    rpc removeGuildInfo(RemoveGuildInfoRequest) returns(Void);
    rpc addGuildRelation(AddGuildRelationRequest) returns(Void);
    rpc removeGuildRelation(RemoveGuildRelationRequest) returns(Void);
    rpc applyGuildUnion(ApplyGuildUnionRequest) returns(Void);
    rpc getEnemyGuildInfos(GetEnemyGuildInfosRequest) returns(Void);
    rpc removeReceiverGuildApplyUnion(RemoveReceiverGuildApplyUnionRequest) returns(Void);
    rpc getCrossServerGuildDetail(GetCrossServerGuildDetailRequest) returns(Void);
    rpc getCrossServerGuildDetailFromOtherServer(GetCrossServerGuildDetailFromOtherServer) returns(Void);
    rpc doOnCrossGuildRequest(DoOnCrossGuildRequest) returns(Void);
    rpc doOnCrossGuildResultBack(DoOnCrossGuildResultBack) returns(Void);
}

service GameServer
{
    rpc activeTickCallback(Void) returns(Void);
    rpc onAddGuildInfo(AddGuildInfoResult) returns(Void);
    rpc onGetGuildInfos(GetGuildInfosResult) returns(Void);
    rpc onBroadcastGuildRelationSingle(BroadcastGuildRelationSingle) returns(Void);
    rpc onGuildRelationAll(GuildRelationAll) returns(Void);
    rpc onBroadcastRemoveGuildRelation(BroadcastRemoveGuildRelation) returns(Void);
    rpc onRemoveGuildRelation(RemoveGuildRelationResult) returns(Void);
    rpc onAddGuildRelation(AddGuildRelationResult) returns(Void);
    rpc onApplyGuildUnion(OnApplyGuildUnionRequest) returns(Void);
    rpc onNotifyGuildRelation(OnNotifyGuildRelation) returns(Void);
    rpc onNotifyGuildCancelUnion(OnNotifyGuildCancelUnion) returns(Void);
    rpc onGetEnemyGuildInfos(GetEnemyGuildInfosResult) returns(Void);
    rpc onApplyGuildUnionResult(ApplyGuildUnionResult) returns(Void);
    rpc onNotifyRemoveReceiverGuildApplyUnion(NotifyRemoveReceiverGuildApplyUnion) returns(Void);
    rpc onGetCrossServerGuildDetail(GetCrossServerGuildDetailResult) returns(Void);
    rpc onGetCrossServerGuildDetailToOtherServer(GetCrossServerGuildDetailToOtherServer) returns(Void);
    rpc onDoOnCrossGuildToGameServer(DoOnCrossGuildToGameServer) returns(Void);
    rpc onDoOnCrossGuildResult(DoOnCrossGuildResult) returns(Void);
}

