syntax = "proto3";

package socializationService;

option go_package = "./socializationService";

option py_generic_services = true;

message Void {}

enum Event
{
    Event_Keepalive = 0;
    Event_Login     = 1;
    Event_Logout    = 2;
    Event_Redirect  = 3;
}

message ClientPingMsg
{
    Event event      = 1;
    uint64 operator  = 2;
    string device_id = 3;
    string token     = 4;
}

enum FriendType
{
    FT_UNKNOW = 0;
    FT_TEMP   = 1;  // 临时好友
    FT_FRIEND = 2;  // 普通好友
    FT_CLOSE  = 3;  // 密友
}

message FriendList
{
    Contact contact = 1;
    repeated PlayerInfo recent = 2;
    repeated PlayerInfo block = 3;
}

message Contact
{
    repeated PlayerInfo close  = 1;
    repeated PlayerInfo normal = 2;
    repeated PlayerInfo temp   = 3;
}

message PlayerInfo
{
    bool online             = 1;
    bool pin                = 2;
    int32 intimacy          = 3;
    int32 sex               = 4;
    uint64 id               = 5;
    string name             = 6;
    string avatar           = 7;
    string remark           = 8;
    int64 add_time          = 9;
    int64 last_chat_time    = 10;
}

message ClientPongMsg
{
    int32 event                      = 1;
    string device_id                 = 2;
    map<int32, bool> settings        = 3;
    map<uint64, int32> offlineMsgCnt = 4;
    FriendList friend_list           = 5;
}

message QueryPlayerInfoReq
{
    uint64 operator   = 1;  // 操作人
    uint64 playerId   = 2;  // 查询条件：id
    string playerName = 3;  // 查询条件：名称
}

message QueryPlayerInfoResp
{
    PlayerInfo info = 1;
}

enum RelationshipOperation
{
    RelOp_UNKNOW            = 0;
    RelOp_ADD               = 1;          // 添加好友
    RelOp_PIN               = 2;          // 置顶好友
    RelOp_UNPIN             = 3;          // 取消置顶好友
    RelOp_DEL               = 4;          // 删除好友
    RelOp_BLOCK             = 5;          // 屏蔽好友
    RelOp_BLOCKED           = 6;          // 被好友屏蔽
    RelOp_UNBLOCK           = 7;          // 取消屏蔽好友
    RelOp_UNBLOCKED         = 8;          // 被取消屏蔽
    RelOp_UPDATEINTIMACY    = 9;          // 更新亲密度
    RelOp_PLAYERLOGIN       = 10;         // 玩家上线通知好友
    RelOp_PLAYERLOGOUT      = 11;         // 玩家离线通知好友
    RelOp_TempADD           = 12;         // 添加临时好友
}

message OperateSocializationReq
{
    uint64                  operator  = 1;
    uint64                  target    = 2;
    RelationshipOperation   operation = 3;
}

message OperateSocializationResp
{
    int32 old_type      = 1;
    int32 type          = 2;
    int32 operation     = 3;
    uint64 operator     = 4;
    PlayerInfo newInfo  = 5;
}

message ModifyRemarkReq
{
    uint64 operator  = 1;
    uint64 target    = 2;
    string remark    = 3;
}

message ModifyRemarkResp
{
    bool success   = 1;
    string message = 2;
}

message Message
{
    int64 send_time     = 1;
    PlayerInfo sender   = 2;
    string content      = 3;
}

message QueryOfflineMsgReq
{
    bool all           = 1;
    uint64 senderId    = 2;     // 消息发送者，即操作者
    uint64 receiverId  = 3;     // 聊天对象
}

message QueryOfflineMsgResp
{
    repeated Message content = 1;
}

message SingleChatReq
{
    uint64 senderId     = 1;
    uint64 receiverId   = 2;
    string content      = 3;
}

message SingleChatResp
{
    uint64 senderId     = 1;
    uint64 receiverId   = 2;
    Message content     = 3;
}

message DeliverMessageReq
{
    int64 msgId         = 1;
    uint64 senderSrvId  = 2;
    uint64 senderId     = 3;
    uint64 receiverId   = 4;
    Message content     = 5;
}

enum DeliverMsgStatus
{
    UNKNOWN     = 0;
    SUCCESS     = 1;    // 发送成功
    OFFLINE     = 2;    // receiver离线
    BLOCK       = 3;    // receiver屏蔽
    SWITCHOFF   = 4;    // receiver不接收陌生人消息
}

message OnDeliverMessageReq
{
    DeliverMsgStatus status = 1;
    int64 msgId             = 2;
    uint64 senderId         = 3;
}

message QueryFlushOfflineMsgReq
{
    bool needTriggerCB  = 1;
    uint64 receiverId   = 2;
    uint64 SrcId        = 3;
}

message OnQueryFlushOfflineMsgReq
{
    uint64 receiverId = 1;
}

enum MsgType
{
    Msg_UNKNOW      = 0;
    Msg_PING        = 1;
    Msg_PONG        = 2;
    Msg_MEET        = 3;
    Msg_FAIL        = 4;
    Msg_PlayerPos   = 5;
}

message nodeInfo
{
    uint64 nodeId   = 1;
    string host     = 2;
    int32 port      = 3;
    int32 cport     = 4;
    int32 gport     = 5;
}

message ClusterPingMsg
{
    enum ClusterMsg
    {
        Meet = 0;
        Ping = 1;
        Pong = 2;
    }
    ClusterMsg msg = 1;
    nodeInfo node  = 2;
}

message UpdatePlayerPosReq
{
    PlayerPos pos = 1;
}

message PlayerPos
{
    bool   login       = 1;
    uint64 playerId    = 2;
    uint64 hash_srv_id = 3;
    uint64 real_srv_id = 4;
}

enum AvatarSetting
{
    AvatarSetting_Unknow        = 0;
    AvatarSetting_StrangerMsg   = 1;   // 设置是否接收陌生人消息
    AvatarSetting_StrangerAdd   = 2;   // 设置是否接收陌生人加好友请求
    AvatarSetting_End           = 3;   // 限定范围，必须在最后
}

message OperateAvatarSettingsReq
{
    bool switchOn           = 1;
    AvatarSetting setting   = 2;
    uint64 operator         = 3;
    string selfToken        = 4;
}

message NotifyPlayerStatusMsg
{
    int32 operation           = 1;
    int32 oldType             = 2;
    int32 newType             = 3;
    uint64 affectedId         = 4;
    PlayerInfo operatorInfo   = 5;
}

message QueryPlayersReq
{
    int32 cnt            = 1;
    int64 chanKey        = 2;
    uint64 operator      = 3;
    uint64 operatorSrvId = 4;
}

message QueryPlayersResp
{
    int64 chanKey              = 1;
    repeated PlayerInfo infos  = 2;
}

message TransferPlayerStatusMsg
{
    enum MsgType {
        None        = 0;
        AddTempToS  = 1;
        AddTempToR  = 2;
        AddTempToB  = 3;
        Login       = 4;
        Operate     = 5;
        Logout      = 6;
    }
    enum ValueType
    {
        Int    = 0;
        Uint64 = 1;
        String = 3;
        Time   = 4;
    }

    message changedValue
    {
        string value    = 1;
        ValueType oType = 2;
    }
    MsgType type                    = 1;
    bool operatorOnline             = 2;
    uint64 operator                 = 3;
    uint64 target                   = 4;
    map<string, changedValue> changeInfo  = 5;
}

message GetPlayerFromNodeResp
{
    bool online = 1;
}

message DependencyPongResp
{
    bool success = 1;
}

message QueryRecommendationReq
{
    int32 cnt       = 1;
    uint64 operator = 2;
}

message QueryRecommendationResp
{
    bool hasMore = 1;
    repeated PlayerInfo playerList = 2;
}

message TriggerRelationUpdatedReq
{
    uint64 operator = 1;
    uint64 target   = 2;
    int32 type      = 3;
}

message RegisterGameSrv
{
    uint32 serverId         = 1;
    uint32 componentOrder   = 2;
    string tokenKey         = 3;
}

message UpdatePlayerInfoReq
{
    bool online     = 1;
    int32 sex       = 2;
    uint64 gbId     = 3;
    string name     = 4;
    string avatar   = 5;
}

message SetFriendIntimacyReq
{
    int32 intimacy = 1;
    uint64 uid     = 2;
    uint64 fid     = 3;
}

message QueryPlayerStatusReq
{
    uint64 playerId = 1;
    uint64 srvId    = 2;
}

message OnQueryPlayerStatusResp
{
    bool online     = 1;
    uint64 playerId = 2;
}

message QueryPlayerBasicInfoReq
{
    uint64 gbId   = 1;
    int64 chanKey = 2;
}

message PlayerBasicInfo
{
    bool online     = 1;
    int32 sex       = 2;
    uint64 gbId     = 3;
    string name     = 4;
    string avatar   = 5;
}

message AnswerPlayerBasicInfoReq
{
    uint64 lastId          = 1;
    int64 chanKey          = 2;
    PlayerBasicInfo info   = 3;
}

message NotifyMessage
{
    int32 msgId             = 1;
    repeated string argv    = 2;
}

message ForwardMethodReq
{
    int32 methodId             = 1;
    uint64 gbId                = 2;
    bytes data                 = 3;
    uint64  realNodeId         = 4;
}

service SocializationService
{
    // 客户端保活，包括登录注册获取好友信息，下线通知
    rpc clientPing(ClientPingMsg) returns(Void);
    // 获取玩家信息
    rpc queryPlayerInfo(QueryPlayerInfoReq) returns(Void);
    // 好友设置
    rpc operateSocialization(OperateSocializationReq) returns(Void);
    // 修改备注
    rpc modifyRemark(ModifyRemarkReq) returns(Void);
    // 获取离线信息
    rpc queryOfflineMsg(QueryOfflineMsgReq) returns(Void);
    // 单聊
    rpc singleChat(SingleChatReq) returns(Void);
    // 获取系统推荐好友
    rpc queryRecommendation(QueryRecommendationReq) returns(Void);
    // 玩家设置
    rpc operateAvatarSettings(OperateAvatarSettingsReq) returns(Void);
}

// client 的 service
service ClientServer
{
    rpc onClientPing(ClientPongMsg) returns(Void);
    rpc onQueryPlayInfo(QueryPlayerInfoResp) returns(Void);
    rpc onSocializationOperated(OperateSocializationResp) returns(Void);
    rpc onRemarkModification(ModifyRemarkResp) returns(Void);

    rpc onQueryOfflineMsg(QueryOfflineMsgResp) returns(Void);
    rpc onQueryRecommendation(QueryRecommendationResp) returns(Void);

    rpc notifyMessage(NotifyMessage) returns(Void);

    // 发送回调，告知发送者是否成功/下发消息，接收者收到好友发送过来的消息
    rpc sendMessage(SingleChatResp) returns(Void);
}

service SocialPeerNodeService
{
    // 服务端内部通信
    rpc clusterPing(ClusterPingMsg) returns(Void);
    rpc updatePlayerPos(UpdatePlayerPosReq) returns(Void);
    rpc transferPlayerStatus(TransferPlayerStatusMsg) returns(Void);
    rpc NotifyPlayerStatus(NotifyPlayerStatusMsg) returns(Void);
	  rpc deliverMessage(DeliverMessageReq) returns(Void);
	  rpc onDeliverMessage(OnDeliverMessageReq) returns(Void);
	  rpc queryFlushOfflineMsg(QueryFlushOfflineMsgReq) returns(Void);
	  rpc onQueryFlushOfflineMsg(OnQueryFlushOfflineMsgReq) returns(Void);
	  rpc queryPlayers(QueryPlayersReq) returns(Void);
	  rpc answerPlayersQuery(QueryPlayersResp) returns(Void);
    rpc ForwardClientMethod(ForwardMethodReq) returns(Void);
    rpc ForwardRealNodeMethod(ForwardMethodReq) returns(Void);
    rpc queryPlayerStatus(QueryPlayerStatusReq) returns(Void);
    rpc onQueryPlayerStatus(OnQueryPlayerStatusResp) returns(Void);
}

// 游戏服连接的service
service SocializationGameService
{
    rpc registerGameSrv(RegisterGameSrv) returns(Void);
    rpc gameSrvPing(Void) returns(Void);
    rpc answerPlayerBasicInfo(AnswerPlayerBasicInfoReq) returns(Void);
    rpc updatePlayerInfo(UpdatePlayerInfoReq) returns(Void);
    rpc setFriendIntimacy(SetFriendIntimacyReq) returns(Void);
}

service GameServer
{
    rpc queryPlayerBasicInfo(QueryPlayerBasicInfoReq) returns(Void);
    rpc onGameSrvPing(Void) returns(Void);
}
