// Generated by protobuf plugin.  DO NOT EDIT!

package gameServerService

import (
    prpc "centralService/src/trpc"
)

func CrossTeamServer_RegisterGameServer_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(RegisterGameServerRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(ICrossTeamServerInterface).RegisterGameServer(in)
}
func CrossTeamServer_ActiveTick_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(Void)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(ICrossTeamServerInterface).ActiveTick(in)
}
func CrossTeamServer_CreateTeam_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(CreateTeamRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(ICrossTeamServerInterface).CreateTeam(in)
}
func CrossTeamServer_JoinApply_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(JoinApplyRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(ICrossTeamServerInterface).JoinApply(in)
}
func CrossTeamServer_ReqJoin_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(ReqJoinRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(ICrossTeamServerInterface).ReqJoin(in)
}
func CrossTeamServer_ClearApplyList_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(ClearApplyListRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(ICrossTeamServerInterface).ClearApplyList(in)
}
func CrossTeamServer_SetDeputy_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(SetDeputyRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(ICrossTeamServerInterface).SetDeputy(in)
}
func CrossTeamServer_ReplyApply_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(ReplyApplyRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(ICrossTeamServerInterface).ReplyApply(in)
}
func CrossTeamServer_Invite_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(InviteRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(ICrossTeamServerInterface).Invite(in)
}
func CrossTeamServer_ReplyInvite_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(ReplyInviteRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(ICrossTeamServerInterface).ReplyInvite(in)
}
func CrossTeamServer_LeaveTeam_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(LeaveTeamRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(ICrossTeamServerInterface).LeaveTeam(in)
}
func CrossTeamServer_Kick_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(KickRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(ICrossTeamServerInterface).Kick(in)
}
func CrossTeamServer_TransferCaptain_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(TransferCaptainRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(ICrossTeamServerInterface).TransferCaptain(in)
}
func CrossTeamServer_ApplyBecomeCaptain_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(ApplyBecomeCaptainRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(ICrossTeamServerInterface).ApplyBecomeCaptain(in)
}
func CrossTeamServer_ReplyBecomeCaptain_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(ReplyBecomeCaptainRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(ICrossTeamServerInterface).ReplyBecomeCaptain(in)
}
func CrossTeamServer_Disband_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(DisbandRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(ICrossTeamServerInterface).Disband(in)
}
func CrossTeamServer_QueryTeam_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(QueryTeamRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(ICrossTeamServerInterface).QueryTeam(in)
}
func CrossTeamServer_SetTeamSettings_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(SetTeamSettingsRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(ICrossTeamServerInterface).SetTeamSettings(in)
}
func CrossTeamServer_SetAutoMatch_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(SetAutoMatchRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(ICrossTeamServerInterface).SetAutoMatch(in)
}
func CrossTeamServer_GetTeamList_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(GetTeamListRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(ICrossTeamServerInterface).GetTeamList(in)
}
func CrossTeamServer_EnterMatchPool_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(EnterMatchPoolRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(ICrossTeamServerInterface).EnterMatchPool(in)
}
func CrossTeamServer_LeaveMatchPool_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(LeaveMatchPoolRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(ICrossTeamServerInterface).LeaveMatchPool(in)
}
func CrossTeamServer_MatchJoin_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(MatchJoinRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(ICrossTeamServerInterface).MatchJoin(in)
}
func CrossTeamServer_ReportMemberState_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(ReportMemberStateRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(ICrossTeamServerInterface).ReportMemberState(in)
}
func CrossTeamServer_TeamChatMsg_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(TeamChatMsgRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(ICrossTeamServerInterface).TeamChatMsg(in)
}
func CrossTeamServer_StartCrusade_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(StartCrusadeRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(ICrossTeamServerInterface).StartCrusade(in)
}
func CrossTeamServer_CrusadeCheckResult_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(CrusadeCheckResultRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(ICrossTeamServerInterface).CrusadeCheckResult(in)
}
func CrossTeamServer_CrusadeSpaceReady_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(CrusadeSpaceReadyRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(ICrossTeamServerInterface).CrusadeSpaceReady(in)
}
func CrossTeamServer_CrusadeFinished_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(CrusadeFinishedRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(ICrossTeamServerInterface).CrusadeFinished(in)
}
func CrossTeamServer_MemberOffline_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(MemberOfflineRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(ICrossTeamServerInterface).MemberOffline(in)
}
func CrossTeamServer_SetMicsMode_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(SetMicsModeRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(ICrossTeamServerInterface).SetMicsMode(in)
}
func CrossTeamServer_BlockMic_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(BlockMicRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(ICrossTeamServerInterface).BlockMic(in)
}
func CrossTeamServer_AdjustMemberPos_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(AdjustMemberPosRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(ICrossTeamServerInterface).AdjustMemberPos(in)
}
func CrossTeamServer_SetVoiceState_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(SetVoiceStateRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(ICrossTeamServerInterface).SetVoiceState(in)
}
func CrossTeamServer_GetApplyList_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(GetApplyListRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(ICrossTeamServerInterface).GetApplyList(in)
}
func CrossTeamServer_AddMark_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(AddMarkRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(ICrossTeamServerInterface).AddMark(in)
}
func CrossTeamServer_DelMark_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(DelMarkRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(ICrossTeamServerInterface).DelMark(in)
}
func CrossTeamServer_SetOnlyCaptainMark_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(SetOnlyCaptainMarkRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(ICrossTeamServerInterface).SetOnlyCaptainMark(in)
}
func CrossTeamServer_FollowAsk_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(FollowAskRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(ICrossTeamServerInterface).FollowAsk(in)
}
var CrossTeamServerServiceDesc = prpc.ServiceDesc{
    ServiceName: "CrossTeamServer.CrossTeamServer",
    Methods: []prpc.MethodDesc{
        {
            MethodName:  "RegisterGameServer",
            MethodIndex: 0,
            Handler:     CrossTeamServer_RegisterGameServer_Handler,
        },
        {
            MethodName:  "ActiveTick",
            MethodIndex: 1,
            Handler:     CrossTeamServer_ActiveTick_Handler,
        },
        {
            MethodName:  "CreateTeam",
            MethodIndex: 2,
            Handler:     CrossTeamServer_CreateTeam_Handler,
        },
        {
            MethodName:  "JoinApply",
            MethodIndex: 3,
            Handler:     CrossTeamServer_JoinApply_Handler,
        },
        {
            MethodName:  "ReqJoin",
            MethodIndex: 4,
            Handler:     CrossTeamServer_ReqJoin_Handler,
        },
        {
            MethodName:  "ClearApplyList",
            MethodIndex: 5,
            Handler:     CrossTeamServer_ClearApplyList_Handler,
        },
        {
            MethodName:  "SetDeputy",
            MethodIndex: 6,
            Handler:     CrossTeamServer_SetDeputy_Handler,
        },
        {
            MethodName:  "ReplyApply",
            MethodIndex: 7,
            Handler:     CrossTeamServer_ReplyApply_Handler,
        },
        {
            MethodName:  "Invite",
            MethodIndex: 8,
            Handler:     CrossTeamServer_Invite_Handler,
        },
        {
            MethodName:  "ReplyInvite",
            MethodIndex: 9,
            Handler:     CrossTeamServer_ReplyInvite_Handler,
        },
        {
            MethodName:  "LeaveTeam",
            MethodIndex: 10,
            Handler:     CrossTeamServer_LeaveTeam_Handler,
        },
        {
            MethodName:  "Kick",
            MethodIndex: 11,
            Handler:     CrossTeamServer_Kick_Handler,
        },
        {
            MethodName:  "TransferCaptain",
            MethodIndex: 12,
            Handler:     CrossTeamServer_TransferCaptain_Handler,
        },
        {
            MethodName:  "ApplyBecomeCaptain",
            MethodIndex: 13,
            Handler:     CrossTeamServer_ApplyBecomeCaptain_Handler,
        },
        {
            MethodName:  "ReplyBecomeCaptain",
            MethodIndex: 14,
            Handler:     CrossTeamServer_ReplyBecomeCaptain_Handler,
        },
        {
            MethodName:  "Disband",
            MethodIndex: 15,
            Handler:     CrossTeamServer_Disband_Handler,
        },
        {
            MethodName:  "QueryTeam",
            MethodIndex: 16,
            Handler:     CrossTeamServer_QueryTeam_Handler,
        },
        {
            MethodName:  "SetTeamSettings",
            MethodIndex: 17,
            Handler:     CrossTeamServer_SetTeamSettings_Handler,
        },
        {
            MethodName:  "SetAutoMatch",
            MethodIndex: 18,
            Handler:     CrossTeamServer_SetAutoMatch_Handler,
        },
        {
            MethodName:  "GetTeamList",
            MethodIndex: 19,
            Handler:     CrossTeamServer_GetTeamList_Handler,
        },
        {
            MethodName:  "EnterMatchPool",
            MethodIndex: 20,
            Handler:     CrossTeamServer_EnterMatchPool_Handler,
        },
        {
            MethodName:  "LeaveMatchPool",
            MethodIndex: 21,
            Handler:     CrossTeamServer_LeaveMatchPool_Handler,
        },
        {
            MethodName:  "MatchJoin",
            MethodIndex: 22,
            Handler:     CrossTeamServer_MatchJoin_Handler,
        },
        {
            MethodName:  "ReportMemberState",
            MethodIndex: 23,
            Handler:     CrossTeamServer_ReportMemberState_Handler,
        },
        {
            MethodName:  "TeamChatMsg",
            MethodIndex: 24,
            Handler:     CrossTeamServer_TeamChatMsg_Handler,
        },
        {
            MethodName:  "StartCrusade",
            MethodIndex: 25,
            Handler:     CrossTeamServer_StartCrusade_Handler,
        },
        {
            MethodName:  "CrusadeCheckResult",
            MethodIndex: 26,
            Handler:     CrossTeamServer_CrusadeCheckResult_Handler,
        },
        {
            MethodName:  "CrusadeSpaceReady",
            MethodIndex: 27,
            Handler:     CrossTeamServer_CrusadeSpaceReady_Handler,
        },
        {
            MethodName:  "CrusadeFinished",
            MethodIndex: 28,
            Handler:     CrossTeamServer_CrusadeFinished_Handler,
        },
        {
            MethodName:  "MemberOffline",
            MethodIndex: 29,
            Handler:     CrossTeamServer_MemberOffline_Handler,
        },
        {
            MethodName:  "SetMicsMode",
            MethodIndex: 30,
            Handler:     CrossTeamServer_SetMicsMode_Handler,
        },
        {
            MethodName:  "BlockMic",
            MethodIndex: 31,
            Handler:     CrossTeamServer_BlockMic_Handler,
        },
        {
            MethodName:  "AdjustMemberPos",
            MethodIndex: 32,
            Handler:     CrossTeamServer_AdjustMemberPos_Handler,
        },
        {
            MethodName:  "SetVoiceState",
            MethodIndex: 33,
            Handler:     CrossTeamServer_SetVoiceState_Handler,
        },
        {
            MethodName:  "GetApplyList",
            MethodIndex: 34,
            Handler:     CrossTeamServer_GetApplyList_Handler,
        },
        {
            MethodName:  "AddMark",
            MethodIndex: 35,
            Handler:     CrossTeamServer_AddMark_Handler,
        },
        {
            MethodName:  "DelMark",
            MethodIndex: 36,
            Handler:     CrossTeamServer_DelMark_Handler,
        },
        {
            MethodName:  "SetOnlyCaptainMark",
            MethodIndex: 37,
            Handler:     CrossTeamServer_SetOnlyCaptainMark_Handler,
        },
        {
            MethodName:  "FollowAsk",
            MethodIndex: 38,
            Handler:     CrossTeamServer_FollowAsk_Handler,
        },
    },
}

func NewCrossTeamServerService(client prpc.IEndPoint) *prpc.ServerEndPoint {
    return &prpc.ServerEndPoint{&CrossTeamServerServiceDesc, client}
}

func NewCrossTeamServerClient(channel *prpc.RpcChannel) *CrossTeamServerClient {
    return &CrossTeamServerClient{prpc.ClientEndPoint{channel}}
}

type CrossTeamServerClient struct {
	prpc.ClientEndPoint
}
func (self *CrossTeamServerClient) RegisterGameServer(in *RegisterGameServerRequest) (*Void, error) {
    err := self.Channel.CallMethod(&CrossTeamServerServiceDesc.Methods[0], in)
    return &Void{}, err
}
func (self *CrossTeamServerClient) ActiveTick(in *Void) (*Void, error) {
    err := self.Channel.CallMethod(&CrossTeamServerServiceDesc.Methods[1], in)
    return &Void{}, err
}
func (self *CrossTeamServerClient) CreateTeam(in *CreateTeamRequest) (*Void, error) {
    err := self.Channel.CallMethod(&CrossTeamServerServiceDesc.Methods[2], in)
    return &Void{}, err
}
func (self *CrossTeamServerClient) JoinApply(in *JoinApplyRequest) (*Void, error) {
    err := self.Channel.CallMethod(&CrossTeamServerServiceDesc.Methods[3], in)
    return &Void{}, err
}
func (self *CrossTeamServerClient) ReqJoin(in *ReqJoinRequest) (*Void, error) {
    err := self.Channel.CallMethod(&CrossTeamServerServiceDesc.Methods[4], in)
    return &Void{}, err
}
func (self *CrossTeamServerClient) ClearApplyList(in *ClearApplyListRequest) (*Void, error) {
    err := self.Channel.CallMethod(&CrossTeamServerServiceDesc.Methods[5], in)
    return &Void{}, err
}
func (self *CrossTeamServerClient) SetDeputy(in *SetDeputyRequest) (*Void, error) {
    err := self.Channel.CallMethod(&CrossTeamServerServiceDesc.Methods[6], in)
    return &Void{}, err
}
func (self *CrossTeamServerClient) ReplyApply(in *ReplyApplyRequest) (*Void, error) {
    err := self.Channel.CallMethod(&CrossTeamServerServiceDesc.Methods[7], in)
    return &Void{}, err
}
func (self *CrossTeamServerClient) Invite(in *InviteRequest) (*Void, error) {
    err := self.Channel.CallMethod(&CrossTeamServerServiceDesc.Methods[8], in)
    return &Void{}, err
}
func (self *CrossTeamServerClient) ReplyInvite(in *ReplyInviteRequest) (*Void, error) {
    err := self.Channel.CallMethod(&CrossTeamServerServiceDesc.Methods[9], in)
    return &Void{}, err
}
func (self *CrossTeamServerClient) LeaveTeam(in *LeaveTeamRequest) (*Void, error) {
    err := self.Channel.CallMethod(&CrossTeamServerServiceDesc.Methods[10], in)
    return &Void{}, err
}
func (self *CrossTeamServerClient) Kick(in *KickRequest) (*Void, error) {
    err := self.Channel.CallMethod(&CrossTeamServerServiceDesc.Methods[11], in)
    return &Void{}, err
}
func (self *CrossTeamServerClient) TransferCaptain(in *TransferCaptainRequest) (*Void, error) {
    err := self.Channel.CallMethod(&CrossTeamServerServiceDesc.Methods[12], in)
    return &Void{}, err
}
func (self *CrossTeamServerClient) ApplyBecomeCaptain(in *ApplyBecomeCaptainRequest) (*Void, error) {
    err := self.Channel.CallMethod(&CrossTeamServerServiceDesc.Methods[13], in)
    return &Void{}, err
}
func (self *CrossTeamServerClient) ReplyBecomeCaptain(in *ReplyBecomeCaptainRequest) (*Void, error) {
    err := self.Channel.CallMethod(&CrossTeamServerServiceDesc.Methods[14], in)
    return &Void{}, err
}
func (self *CrossTeamServerClient) Disband(in *DisbandRequest) (*Void, error) {
    err := self.Channel.CallMethod(&CrossTeamServerServiceDesc.Methods[15], in)
    return &Void{}, err
}
func (self *CrossTeamServerClient) QueryTeam(in *QueryTeamRequest) (*Void, error) {
    err := self.Channel.CallMethod(&CrossTeamServerServiceDesc.Methods[16], in)
    return &Void{}, err
}
func (self *CrossTeamServerClient) SetTeamSettings(in *SetTeamSettingsRequest) (*Void, error) {
    err := self.Channel.CallMethod(&CrossTeamServerServiceDesc.Methods[17], in)
    return &Void{}, err
}
func (self *CrossTeamServerClient) SetAutoMatch(in *SetAutoMatchRequest) (*Void, error) {
    err := self.Channel.CallMethod(&CrossTeamServerServiceDesc.Methods[18], in)
    return &Void{}, err
}
func (self *CrossTeamServerClient) GetTeamList(in *GetTeamListRequest) (*Void, error) {
    err := self.Channel.CallMethod(&CrossTeamServerServiceDesc.Methods[19], in)
    return &Void{}, err
}
func (self *CrossTeamServerClient) EnterMatchPool(in *EnterMatchPoolRequest) (*Void, error) {
    err := self.Channel.CallMethod(&CrossTeamServerServiceDesc.Methods[20], in)
    return &Void{}, err
}
func (self *CrossTeamServerClient) LeaveMatchPool(in *LeaveMatchPoolRequest) (*Void, error) {
    err := self.Channel.CallMethod(&CrossTeamServerServiceDesc.Methods[21], in)
    return &Void{}, err
}
func (self *CrossTeamServerClient) MatchJoin(in *MatchJoinRequest) (*Void, error) {
    err := self.Channel.CallMethod(&CrossTeamServerServiceDesc.Methods[22], in)
    return &Void{}, err
}
func (self *CrossTeamServerClient) ReportMemberState(in *ReportMemberStateRequest) (*Void, error) {
    err := self.Channel.CallMethod(&CrossTeamServerServiceDesc.Methods[23], in)
    return &Void{}, err
}
func (self *CrossTeamServerClient) TeamChatMsg(in *TeamChatMsgRequest) (*Void, error) {
    err := self.Channel.CallMethod(&CrossTeamServerServiceDesc.Methods[24], in)
    return &Void{}, err
}
func (self *CrossTeamServerClient) StartCrusade(in *StartCrusadeRequest) (*Void, error) {
    err := self.Channel.CallMethod(&CrossTeamServerServiceDesc.Methods[25], in)
    return &Void{}, err
}
func (self *CrossTeamServerClient) CrusadeCheckResult(in *CrusadeCheckResultRequest) (*Void, error) {
    err := self.Channel.CallMethod(&CrossTeamServerServiceDesc.Methods[26], in)
    return &Void{}, err
}
func (self *CrossTeamServerClient) CrusadeSpaceReady(in *CrusadeSpaceReadyRequest) (*Void, error) {
    err := self.Channel.CallMethod(&CrossTeamServerServiceDesc.Methods[27], in)
    return &Void{}, err
}
func (self *CrossTeamServerClient) CrusadeFinished(in *CrusadeFinishedRequest) (*Void, error) {
    err := self.Channel.CallMethod(&CrossTeamServerServiceDesc.Methods[28], in)
    return &Void{}, err
}
func (self *CrossTeamServerClient) MemberOffline(in *MemberOfflineRequest) (*Void, error) {
    err := self.Channel.CallMethod(&CrossTeamServerServiceDesc.Methods[29], in)
    return &Void{}, err
}
func (self *CrossTeamServerClient) SetMicsMode(in *SetMicsModeRequest) (*Void, error) {
    err := self.Channel.CallMethod(&CrossTeamServerServiceDesc.Methods[30], in)
    return &Void{}, err
}
func (self *CrossTeamServerClient) BlockMic(in *BlockMicRequest) (*Void, error) {
    err := self.Channel.CallMethod(&CrossTeamServerServiceDesc.Methods[31], in)
    return &Void{}, err
}
func (self *CrossTeamServerClient) AdjustMemberPos(in *AdjustMemberPosRequest) (*Void, error) {
    err := self.Channel.CallMethod(&CrossTeamServerServiceDesc.Methods[32], in)
    return &Void{}, err
}
func (self *CrossTeamServerClient) SetVoiceState(in *SetVoiceStateRequest) (*Void, error) {
    err := self.Channel.CallMethod(&CrossTeamServerServiceDesc.Methods[33], in)
    return &Void{}, err
}
func (self *CrossTeamServerClient) GetApplyList(in *GetApplyListRequest) (*Void, error) {
    err := self.Channel.CallMethod(&CrossTeamServerServiceDesc.Methods[34], in)
    return &Void{}, err
}
func (self *CrossTeamServerClient) AddMark(in *AddMarkRequest) (*Void, error) {
    err := self.Channel.CallMethod(&CrossTeamServerServiceDesc.Methods[35], in)
    return &Void{}, err
}
func (self *CrossTeamServerClient) DelMark(in *DelMarkRequest) (*Void, error) {
    err := self.Channel.CallMethod(&CrossTeamServerServiceDesc.Methods[36], in)
    return &Void{}, err
}
func (self *CrossTeamServerClient) SetOnlyCaptainMark(in *SetOnlyCaptainMarkRequest) (*Void, error) {
    err := self.Channel.CallMethod(&CrossTeamServerServiceDesc.Methods[37], in)
    return &Void{}, err
}
func (self *CrossTeamServerClient) FollowAsk(in *FollowAskRequest) (*Void, error) {
    err := self.Channel.CallMethod(&CrossTeamServerServiceDesc.Methods[38], in)
    return &Void{}, err
}
type ICrossTeamServerInterface interface {
    RegisterGameServer(*RegisterGameServerRequest) (*Void, error)
    ActiveTick(*Void) (*Void, error)
    CreateTeam(*CreateTeamRequest) (*Void, error)
    JoinApply(*JoinApplyRequest) (*Void, error)
    ReqJoin(*ReqJoinRequest) (*Void, error)
    ClearApplyList(*ClearApplyListRequest) (*Void, error)
    SetDeputy(*SetDeputyRequest) (*Void, error)
    ReplyApply(*ReplyApplyRequest) (*Void, error)
    Invite(*InviteRequest) (*Void, error)
    ReplyInvite(*ReplyInviteRequest) (*Void, error)
    LeaveTeam(*LeaveTeamRequest) (*Void, error)
    Kick(*KickRequest) (*Void, error)
    TransferCaptain(*TransferCaptainRequest) (*Void, error)
    ApplyBecomeCaptain(*ApplyBecomeCaptainRequest) (*Void, error)
    ReplyBecomeCaptain(*ReplyBecomeCaptainRequest) (*Void, error)
    Disband(*DisbandRequest) (*Void, error)
    QueryTeam(*QueryTeamRequest) (*Void, error)
    SetTeamSettings(*SetTeamSettingsRequest) (*Void, error)
    SetAutoMatch(*SetAutoMatchRequest) (*Void, error)
    GetTeamList(*GetTeamListRequest) (*Void, error)
    EnterMatchPool(*EnterMatchPoolRequest) (*Void, error)
    LeaveMatchPool(*LeaveMatchPoolRequest) (*Void, error)
    MatchJoin(*MatchJoinRequest) (*Void, error)
    ReportMemberState(*ReportMemberStateRequest) (*Void, error)
    TeamChatMsg(*TeamChatMsgRequest) (*Void, error)
    StartCrusade(*StartCrusadeRequest) (*Void, error)
    CrusadeCheckResult(*CrusadeCheckResultRequest) (*Void, error)
    CrusadeSpaceReady(*CrusadeSpaceReadyRequest) (*Void, error)
    CrusadeFinished(*CrusadeFinishedRequest) (*Void, error)
    MemberOffline(*MemberOfflineRequest) (*Void, error)
    SetMicsMode(*SetMicsModeRequest) (*Void, error)
    BlockMic(*BlockMicRequest) (*Void, error)
    AdjustMemberPos(*AdjustMemberPosRequest) (*Void, error)
    SetVoiceState(*SetVoiceStateRequest) (*Void, error)
    GetApplyList(*GetApplyListRequest) (*Void, error)
    AddMark(*AddMarkRequest) (*Void, error)
    DelMark(*DelMarkRequest) (*Void, error)
    SetOnlyCaptainMark(*SetOnlyCaptainMarkRequest) (*Void, error)
    FollowAsk(*FollowAskRequest) (*Void, error)
}

func GameServer_ActiveTickCallback_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(Void)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).ActiveTickCallback(in)
}
func GameServer_TeamOpResult_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(TeamOpResultMsg)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).TeamOpResult(in)
}
func GameServer_ReplyApplyNotify_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(ReplyApplyNotifyMsg)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).ReplyApplyNotify(in)
}
func GameServer_TeamCreateSuccessPush_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(TeamCreateSuccessPushMsg)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).TeamCreateSuccessPush(in)
}
func GameServer_TeamJoinSuccessPush_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(TeamJoinSuccessPushMsg)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).TeamJoinSuccessPush(in)
}
func GameServer_MemberJoinPush_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(MemberJoinPushMsg)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).MemberJoinPush(in)
}
func GameServer_MemberLeavePush_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(MemberLeavePushMsg)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).MemberLeavePush(in)
}
func GameServer_CaptainChangePush_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(CaptainChangePushMsg)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).CaptainChangePush(in)
}
func GameServer_DeputyChangePush_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(DeputyChangePushMsg)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).DeputyChangePush(in)
}
func GameServer_BecomeCaptainApplyPush_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(BecomeCaptainApplyPushMsg)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).BecomeCaptainApplyPush(in)
}
func GameServer_TeamDisbandPush_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(TeamDisbandPushMsg)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).TeamDisbandPush(in)
}
func GameServer_TeamSettingsChangePush_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(TeamSettingsChangePushMsg)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).TeamSettingsChangePush(in)
}
func GameServer_TeamAutoMatchChangePush_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(TeamAutoMatchChangePushMsg)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).TeamAutoMatchChangePush(in)
}
func GameServer_TeamMicsModeChangePush_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(TeamMicsModeChangePushMsg)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).TeamMicsModeChangePush(in)
}
func GameServer_MemberMicBlockPush_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(MemberMicBlockPushMsg)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).MemberMicBlockPush(in)
}
func GameServer_AdjustMemberPosPush_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(AdjustMemberPosPushMsg)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).AdjustMemberPosPush(in)
}
func GameServer_TeamListResult_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(TeamListResultMsg)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).TeamListResult(in)
}
func GameServer_MatchSuccess_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(MatchSuccessMsg)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).MatchSuccess(in)
}
func GameServer_MatchTimeout_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(MatchTimeoutMsg)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).MatchTimeout(in)
}
func GameServer_BroadcastMemberState_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(BroadcastMemberStateMsg)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).BroadcastMemberState(in)
}
func GameServer_TeamChatBatch_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(TeamChatBatchMsg)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).TeamChatBatch(in)
}
func GameServer_CrusadeCheck_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(CrusadeCheckMsg)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).CrusadeCheck(in)
}
func GameServer_CrusadeGo_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(CrusadeGoMsg)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).CrusadeGo(in)
}
func GameServer_CrusadeAbort_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(CrusadeAbortMsg)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).CrusadeAbort(in)
}
func GameServer_CreateCrusadeSpace_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(CreateCrusadeSpaceMsg)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).CreateCrusadeSpace(in)
}
func GameServer_TeamDataResp_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(TeamDataRespMsg)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).TeamDataResp(in)
}
func GameServer_QueryTeamCrossResp_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(QueryTeamCrossRespMsg)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).QueryTeamCrossResp(in)
}
func GameServer_JoinApplyNotify_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(JoinApplyNotifyMsg)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).JoinApplyNotify(in)
}
func GameServer_InviteNotify_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(InviteNotifyMsg)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).InviteNotify(in)
}
func GameServer_MemberVoiceStatePush_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(MemberVoiceStatePushMsg)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).MemberVoiceStatePush(in)
}
func GameServer_MatchStart_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(MatchStartMsg)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).MatchStart(in)
}
func GameServer_MatchStop_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(MatchStopMsg)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).MatchStop(in)
}
func GameServer_ApplyListPush_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(ApplyListPushMsg)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).ApplyListPush(in)
}
func GameServer_ApplyRemoveNotify_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(ApplyRemoveNotifyMsg)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).ApplyRemoveNotify(in)
}
func GameServer_DungeonCDRefreshPush_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(DungeonCDRefreshPushMsg)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).DungeonCDRefreshPush(in)
}
func GameServer_MarkChangePush_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(MarkChangePushMsg)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).MarkChangePush(in)
}
func GameServer_FollowAskPush_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(FollowAskPushMsg)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).FollowAskPush(in)
}
var GameServerServiceDesc = prpc.ServiceDesc{
    ServiceName: "CrossTeamServer.GameServer",
    Methods: []prpc.MethodDesc{
        {
            MethodName:  "ActiveTickCallback",
            MethodIndex: 0,
            Handler:     GameServer_ActiveTickCallback_Handler,
        },
        {
            MethodName:  "TeamOpResult",
            MethodIndex: 1,
            Handler:     GameServer_TeamOpResult_Handler,
        },
        {
            MethodName:  "ReplyApplyNotify",
            MethodIndex: 2,
            Handler:     GameServer_ReplyApplyNotify_Handler,
        },
        {
            MethodName:  "TeamCreateSuccessPush",
            MethodIndex: 3,
            Handler:     GameServer_TeamCreateSuccessPush_Handler,
        },
        {
            MethodName:  "TeamJoinSuccessPush",
            MethodIndex: 4,
            Handler:     GameServer_TeamJoinSuccessPush_Handler,
        },
        {
            MethodName:  "MemberJoinPush",
            MethodIndex: 5,
            Handler:     GameServer_MemberJoinPush_Handler,
        },
        {
            MethodName:  "MemberLeavePush",
            MethodIndex: 6,
            Handler:     GameServer_MemberLeavePush_Handler,
        },
        {
            MethodName:  "CaptainChangePush",
            MethodIndex: 7,
            Handler:     GameServer_CaptainChangePush_Handler,
        },
        {
            MethodName:  "DeputyChangePush",
            MethodIndex: 8,
            Handler:     GameServer_DeputyChangePush_Handler,
        },
        {
            MethodName:  "BecomeCaptainApplyPush",
            MethodIndex: 9,
            Handler:     GameServer_BecomeCaptainApplyPush_Handler,
        },
        {
            MethodName:  "TeamDisbandPush",
            MethodIndex: 10,
            Handler:     GameServer_TeamDisbandPush_Handler,
        },
        {
            MethodName:  "TeamSettingsChangePush",
            MethodIndex: 11,
            Handler:     GameServer_TeamSettingsChangePush_Handler,
        },
        {
            MethodName:  "TeamAutoMatchChangePush",
            MethodIndex: 12,
            Handler:     GameServer_TeamAutoMatchChangePush_Handler,
        },
        {
            MethodName:  "TeamMicsModeChangePush",
            MethodIndex: 13,
            Handler:     GameServer_TeamMicsModeChangePush_Handler,
        },
        {
            MethodName:  "MemberMicBlockPush",
            MethodIndex: 14,
            Handler:     GameServer_MemberMicBlockPush_Handler,
        },
        {
            MethodName:  "AdjustMemberPosPush",
            MethodIndex: 15,
            Handler:     GameServer_AdjustMemberPosPush_Handler,
        },
        {
            MethodName:  "TeamListResult",
            MethodIndex: 16,
            Handler:     GameServer_TeamListResult_Handler,
        },
        {
            MethodName:  "MatchSuccess",
            MethodIndex: 17,
            Handler:     GameServer_MatchSuccess_Handler,
        },
        {
            MethodName:  "MatchTimeout",
            MethodIndex: 18,
            Handler:     GameServer_MatchTimeout_Handler,
        },
        {
            MethodName:  "BroadcastMemberState",
            MethodIndex: 19,
            Handler:     GameServer_BroadcastMemberState_Handler,
        },
        {
            MethodName:  "TeamChatBatch",
            MethodIndex: 20,
            Handler:     GameServer_TeamChatBatch_Handler,
        },
        {
            MethodName:  "CrusadeCheck",
            MethodIndex: 21,
            Handler:     GameServer_CrusadeCheck_Handler,
        },
        {
            MethodName:  "CrusadeGo",
            MethodIndex: 22,
            Handler:     GameServer_CrusadeGo_Handler,
        },
        {
            MethodName:  "CrusadeAbort",
            MethodIndex: 23,
            Handler:     GameServer_CrusadeAbort_Handler,
        },
        {
            MethodName:  "CreateCrusadeSpace",
            MethodIndex: 24,
            Handler:     GameServer_CreateCrusadeSpace_Handler,
        },
        {
            MethodName:  "TeamDataResp",
            MethodIndex: 25,
            Handler:     GameServer_TeamDataResp_Handler,
        },
        {
            MethodName:  "QueryTeamCrossResp",
            MethodIndex: 26,
            Handler:     GameServer_QueryTeamCrossResp_Handler,
        },
        {
            MethodName:  "JoinApplyNotify",
            MethodIndex: 27,
            Handler:     GameServer_JoinApplyNotify_Handler,
        },
        {
            MethodName:  "InviteNotify",
            MethodIndex: 28,
            Handler:     GameServer_InviteNotify_Handler,
        },
        {
            MethodName:  "MemberVoiceStatePush",
            MethodIndex: 29,
            Handler:     GameServer_MemberVoiceStatePush_Handler,
        },
        {
            MethodName:  "MatchStart",
            MethodIndex: 30,
            Handler:     GameServer_MatchStart_Handler,
        },
        {
            MethodName:  "MatchStop",
            MethodIndex: 31,
            Handler:     GameServer_MatchStop_Handler,
        },
        {
            MethodName:  "ApplyListPush",
            MethodIndex: 32,
            Handler:     GameServer_ApplyListPush_Handler,
        },
        {
            MethodName:  "ApplyRemoveNotify",
            MethodIndex: 33,
            Handler:     GameServer_ApplyRemoveNotify_Handler,
        },
        {
            MethodName:  "DungeonCDRefreshPush",
            MethodIndex: 34,
            Handler:     GameServer_DungeonCDRefreshPush_Handler,
        },
        {
            MethodName:  "MarkChangePush",
            MethodIndex: 35,
            Handler:     GameServer_MarkChangePush_Handler,
        },
        {
            MethodName:  "FollowAskPush",
            MethodIndex: 36,
            Handler:     GameServer_FollowAskPush_Handler,
        },
    },
}

func NewGameServerService(client prpc.IEndPoint) *prpc.ServerEndPoint {
    return &prpc.ServerEndPoint{&GameServerServiceDesc, client}
}

func NewGameServerClient(channel *prpc.RpcChannel) *GameServerClient {
    return &GameServerClient{prpc.ClientEndPoint{channel}}
}

type GameServerClient struct {
	prpc.ClientEndPoint
}
func (self *GameServerClient) ActiveTickCallback(in *Void) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[0], in)
    return &Void{}, err
}
func (self *GameServerClient) TeamOpResult(in *TeamOpResultMsg) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[1], in)
    return &Void{}, err
}
func (self *GameServerClient) ReplyApplyNotify(in *ReplyApplyNotifyMsg) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[2], in)
    return &Void{}, err
}
func (self *GameServerClient) TeamCreateSuccessPush(in *TeamCreateSuccessPushMsg) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[3], in)
    return &Void{}, err
}
func (self *GameServerClient) TeamJoinSuccessPush(in *TeamJoinSuccessPushMsg) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[4], in)
    return &Void{}, err
}
func (self *GameServerClient) MemberJoinPush(in *MemberJoinPushMsg) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[5], in)
    return &Void{}, err
}
func (self *GameServerClient) MemberLeavePush(in *MemberLeavePushMsg) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[6], in)
    return &Void{}, err
}
func (self *GameServerClient) CaptainChangePush(in *CaptainChangePushMsg) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[7], in)
    return &Void{}, err
}
func (self *GameServerClient) DeputyChangePush(in *DeputyChangePushMsg) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[8], in)
    return &Void{}, err
}
func (self *GameServerClient) BecomeCaptainApplyPush(in *BecomeCaptainApplyPushMsg) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[9], in)
    return &Void{}, err
}
func (self *GameServerClient) TeamDisbandPush(in *TeamDisbandPushMsg) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[10], in)
    return &Void{}, err
}
func (self *GameServerClient) TeamSettingsChangePush(in *TeamSettingsChangePushMsg) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[11], in)
    return &Void{}, err
}
func (self *GameServerClient) TeamAutoMatchChangePush(in *TeamAutoMatchChangePushMsg) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[12], in)
    return &Void{}, err
}
func (self *GameServerClient) TeamMicsModeChangePush(in *TeamMicsModeChangePushMsg) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[13], in)
    return &Void{}, err
}
func (self *GameServerClient) MemberMicBlockPush(in *MemberMicBlockPushMsg) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[14], in)
    return &Void{}, err
}
func (self *GameServerClient) AdjustMemberPosPush(in *AdjustMemberPosPushMsg) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[15], in)
    return &Void{}, err
}
func (self *GameServerClient) TeamListResult(in *TeamListResultMsg) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[16], in)
    return &Void{}, err
}
func (self *GameServerClient) MatchSuccess(in *MatchSuccessMsg) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[17], in)
    return &Void{}, err
}
func (self *GameServerClient) MatchTimeout(in *MatchTimeoutMsg) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[18], in)
    return &Void{}, err
}
func (self *GameServerClient) BroadcastMemberState(in *BroadcastMemberStateMsg) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[19], in)
    return &Void{}, err
}
func (self *GameServerClient) TeamChatBatch(in *TeamChatBatchMsg) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[20], in)
    return &Void{}, err
}
func (self *GameServerClient) CrusadeCheck(in *CrusadeCheckMsg) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[21], in)
    return &Void{}, err
}
func (self *GameServerClient) CrusadeGo(in *CrusadeGoMsg) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[22], in)
    return &Void{}, err
}
func (self *GameServerClient) CrusadeAbort(in *CrusadeAbortMsg) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[23], in)
    return &Void{}, err
}
func (self *GameServerClient) CreateCrusadeSpace(in *CreateCrusadeSpaceMsg) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[24], in)
    return &Void{}, err
}
func (self *GameServerClient) TeamDataResp(in *TeamDataRespMsg) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[25], in)
    return &Void{}, err
}
func (self *GameServerClient) QueryTeamCrossResp(in *QueryTeamCrossRespMsg) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[26], in)
    return &Void{}, err
}
func (self *GameServerClient) JoinApplyNotify(in *JoinApplyNotifyMsg) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[27], in)
    return &Void{}, err
}
func (self *GameServerClient) InviteNotify(in *InviteNotifyMsg) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[28], in)
    return &Void{}, err
}
func (self *GameServerClient) MemberVoiceStatePush(in *MemberVoiceStatePushMsg) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[29], in)
    return &Void{}, err
}
func (self *GameServerClient) MatchStart(in *MatchStartMsg) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[30], in)
    return &Void{}, err
}
func (self *GameServerClient) MatchStop(in *MatchStopMsg) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[31], in)
    return &Void{}, err
}
func (self *GameServerClient) ApplyListPush(in *ApplyListPushMsg) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[32], in)
    return &Void{}, err
}
func (self *GameServerClient) ApplyRemoveNotify(in *ApplyRemoveNotifyMsg) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[33], in)
    return &Void{}, err
}
func (self *GameServerClient) DungeonCDRefreshPush(in *DungeonCDRefreshPushMsg) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[34], in)
    return &Void{}, err
}
func (self *GameServerClient) MarkChangePush(in *MarkChangePushMsg) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[35], in)
    return &Void{}, err
}
func (self *GameServerClient) FollowAskPush(in *FollowAskPushMsg) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[36], in)
    return &Void{}, err
}
type IGameServerInterface interface {
    ActiveTickCallback(*Void) (*Void, error)
    TeamOpResult(*TeamOpResultMsg) (*Void, error)
    ReplyApplyNotify(*ReplyApplyNotifyMsg) (*Void, error)
    TeamCreateSuccessPush(*TeamCreateSuccessPushMsg) (*Void, error)
    TeamJoinSuccessPush(*TeamJoinSuccessPushMsg) (*Void, error)
    MemberJoinPush(*MemberJoinPushMsg) (*Void, error)
    MemberLeavePush(*MemberLeavePushMsg) (*Void, error)
    CaptainChangePush(*CaptainChangePushMsg) (*Void, error)
    DeputyChangePush(*DeputyChangePushMsg) (*Void, error)
    BecomeCaptainApplyPush(*BecomeCaptainApplyPushMsg) (*Void, error)
    TeamDisbandPush(*TeamDisbandPushMsg) (*Void, error)
    TeamSettingsChangePush(*TeamSettingsChangePushMsg) (*Void, error)
    TeamAutoMatchChangePush(*TeamAutoMatchChangePushMsg) (*Void, error)
    TeamMicsModeChangePush(*TeamMicsModeChangePushMsg) (*Void, error)
    MemberMicBlockPush(*MemberMicBlockPushMsg) (*Void, error)
    AdjustMemberPosPush(*AdjustMemberPosPushMsg) (*Void, error)
    TeamListResult(*TeamListResultMsg) (*Void, error)
    MatchSuccess(*MatchSuccessMsg) (*Void, error)
    MatchTimeout(*MatchTimeoutMsg) (*Void, error)
    BroadcastMemberState(*BroadcastMemberStateMsg) (*Void, error)
    TeamChatBatch(*TeamChatBatchMsg) (*Void, error)
    CrusadeCheck(*CrusadeCheckMsg) (*Void, error)
    CrusadeGo(*CrusadeGoMsg) (*Void, error)
    CrusadeAbort(*CrusadeAbortMsg) (*Void, error)
    CreateCrusadeSpace(*CreateCrusadeSpaceMsg) (*Void, error)
    TeamDataResp(*TeamDataRespMsg) (*Void, error)
    QueryTeamCrossResp(*QueryTeamCrossRespMsg) (*Void, error)
    JoinApplyNotify(*JoinApplyNotifyMsg) (*Void, error)
    InviteNotify(*InviteNotifyMsg) (*Void, error)
    MemberVoiceStatePush(*MemberVoiceStatePushMsg) (*Void, error)
    MatchStart(*MatchStartMsg) (*Void, error)
    MatchStop(*MatchStopMsg) (*Void, error)
    ApplyListPush(*ApplyListPushMsg) (*Void, error)
    ApplyRemoveNotify(*ApplyRemoveNotifyMsg) (*Void, error)
    DungeonCDRefreshPush(*DungeonCDRefreshPushMsg) (*Void, error)
    MarkChangePush(*MarkChangePushMsg) (*Void, error)
    FollowAskPush(*FollowAskPushMsg) (*Void, error)
}

