package crossDataApp

const (
	ERROR_CODE_SUCCESS                 = 0
	ERROR_CODE_COMMON                  = 1
	ERROR_CODE_NOT_FOUND_GUILD         = 2
	ERROR_CODE_RELATION_MAX_NUM_GUILD1 = 3
	ERROR_CODE_RELATION_MAX_NUM_GUILD2 = 4
	ERROR_CODE_RELATION_ALREADY_EXISTS = 5
)
