syntax = "proto3";

package CrossDataServer;
option go_package = "../gameServerService";
option py_generic_services = true;

message Void {

}

message RegisterGameServerRequest
{
    uint32 serverId = 1;
}

message GuildInfo {
    uint64 guildUUID = 1;
    string guildName = 2;
    uint32 serverId = 3;
    uint32 flag = 4;
    uint32 guildScore = 5;
    uint32 guildLevel = 6;
    uint32 guildIcon = 7;
    uint32 memberCnt = 8;
}

message AddGuildInfoRequest {
    GuildInfo guildInfo = 1;
    uint64 uuid = 2;
}

message AddGuildInfoResult {
    uint64 uuid = 1;
}

message GetGuildInfosRequest {
    uint32 serverId = 1;
    uint64 uuid = 2;
}

message GetGuildInfosByGuildUUIDRequest {
    repeated uint64 guildUUIDs = 1;
    uint64 uuid = 2;
}

message GetGuildInfosResult {
    repeated GuildInfo guildInfos = 1;
    uint64 uuid = 2;
}

message RemoveGuildInfoRequest {
    uint64 guildUUID = 2;
}

message GetCrossServerGuildDetailRequest {
    uint64 guildUUID = 1;
    uint32 senderServerId = 2;
    uint64 uuid = 3;
}

message GetCrossServerGuildDetailToOtherServer {
    uint64 guildUUID = 1;
    uint32 senderServerId = 2;
    uint64 uuid = 3;
}

message GuildDetailInfo {
    uint64 guildUUID = 1;
    string desc = 2;
    string leaderName = 3;
    uint32 leaderSex = 4;
    uint32 leaderSchool = 5;
    uint32 leaderLevel = 6;
    uint64 leaderGbId = 7;
    uint64 leagueUUID = 8;
}

message GetCrossServerGuildDetailFromOtherServer {
    GuildDetailInfo guildDetailInfo = 1;
    uint32 senderServerId = 2;
    uint64 uuid = 3;
}

message GetCrossServerGuildDetailResult {
    GuildDetailInfo guildDetailInfo = 1;
    uint64 uuid = 3;
}

message DoOnCrossGuildRequest {
    uint64 guildUUID = 1;
    string func = 2;
    bytes args = 3;
    uint64 uuid = 4;
}

message DoOnCrossGuildToGameServer {
    uint64 guildUUID = 1;
    string func = 2;
    bytes args = 3;
    uint64 uuid = 4;
    uint32 senderServerId = 5;
}

message DoOnCrossGuildResult {
    uint64 uuid = 1;
    bool success = 2;
    bytes result = 3;
}

message DoOnCrossGuildResultBack {
    uint64 uuid = 1;
    uint32 serverId = 2;
    bool success = 3;
    bytes result = 4;
}

message SaveSiegeWarDataRequest {
    bytes data = 1;
    uint64 uuid = 2;
}

message SaveSiegeWarDataResult {
    uint64 uuid = 1;
    bool success = 2;
}

message LoadSiegeWarDataRequest {
    uint64 uuid = 1;
}

message LoadSiegeWarDataResult {
    bytes data = 1;
    uint64 uuid = 2;
    bool success = 3;
}


service CrossDataServer
{
    rpc registerGameServer(RegisterGameServerRequest) returns (Void);
    rpc activeTick(Void) returns(Void);
    rpc addGuildInfo(AddGuildInfoRequest) returns(Void);
    rpc getGuildInfos(GetGuildInfosRequest) returns(Void);
    rpc getGuildInfosByGuildUUID(GetGuildInfosByGuildUUIDRequest) returns(Void);
    rpc removeGuildInfo(RemoveGuildInfoRequest) returns(Void);
    rpc getCrossServerGuildDetail(GetCrossServerGuildDetailRequest) returns(Void);
    rpc getCrossServerGuildDetailFromOtherServer(GetCrossServerGuildDetailFromOtherServer) returns(Void);
    rpc doOnCrossGuildRequest(DoOnCrossGuildRequest) returns(Void);
    rpc doOnCrossGuildResultBack(DoOnCrossGuildResultBack) returns(Void);
    rpc saveSiegeWarData(SaveSiegeWarDataRequest) returns(Void);
    rpc loadSiegeWarData(LoadSiegeWarDataRequest) returns(Void);
}

service GameServer
{
    rpc activeTickCallback(Void) returns(Void);
    rpc onAddGuildInfo(AddGuildInfoResult) returns(Void);
    rpc onGetGuildInfos(GetGuildInfosResult) returns(Void);
    rpc onGetCrossServerGuildDetail(GetCrossServerGuildDetailResult) returns(Void);
    rpc onGetCrossServerGuildDetailToOtherServer(GetCrossServerGuildDetailToOtherServer) returns(Void);
    rpc onDoOnCrossGuildToGameServer(DoOnCrossGuildToGameServer) returns(Void);
    rpc onDoOnCrossGuildResult(DoOnCrossGuildResult) returns(Void);
    rpc onSaveSiegeWarData(SaveSiegeWarDataResult) returns(Void);
    rpc onLoadSiegeWarData(LoadSiegeWarDataResult) returns(Void);
}

