// Generated by protobuf plugin.  DO NOT EDIT!

package gsmanager

import (
    prpc "centralService/src/trpc"
)

func Admin_RegisterServer_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(ServerInfoMessage)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IAdminInterface).RegisterServer(in)
}
func Admin_ReplyCommand_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(CommandResult)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IAdminInterface).ReplyCommand(in)
}
func Admin_ActiveTick_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(Void)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IAdminInterface).ActiveTick(in)
}
func Admin_ReplyHttpCommand_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(HttpAPICommandResponse)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IAdminInterface).ReplyHttpCommand(in)
}
var AdminServiceDesc = prpc.ServiceDesc{
    ServiceName: "adminGsManager.Admin",
    Methods: []prpc.MethodDesc{
        {
            MethodName:  "RegisterServer",
            MethodIndex: 0,
            Handler:     Admin_RegisterServer_Handler,
        },
        {
            MethodName:  "ReplyCommand",
            MethodIndex: 1,
            Handler:     Admin_ReplyCommand_Handler,
        },
        {
            MethodName:  "ActiveTick",
            MethodIndex: 2,
            Handler:     Admin_ActiveTick_Handler,
        },
        {
            MethodName:  "ReplyHttpCommand",
            MethodIndex: 3,
            Handler:     Admin_ReplyHttpCommand_Handler,
        },
    },
}

func NewAdminService(client prpc.IEndPoint) *prpc.ServerEndPoint {
    return &prpc.ServerEndPoint{&AdminServiceDesc, client}
}

func NewAdminClient(channel *prpc.RpcChannel) *AdminClient {
    return &AdminClient{prpc.ClientEndPoint{channel}}
}

type AdminClient struct {
	prpc.ClientEndPoint
}
func (self *AdminClient) RegisterServer(in *ServerInfoMessage) (*Void, error) {
    err := self.Channel.CallMethod(&AdminServiceDesc.Methods[0], in)
    return &Void{}, err
}
func (self *AdminClient) ReplyCommand(in *CommandResult) (*Void, error) {
    err := self.Channel.CallMethod(&AdminServiceDesc.Methods[1], in)
    return &Void{}, err
}
func (self *AdminClient) ActiveTick(in *Void) (*Void, error) {
    err := self.Channel.CallMethod(&AdminServiceDesc.Methods[2], in)
    return &Void{}, err
}
func (self *AdminClient) ReplyHttpCommand(in *HttpAPICommandResponse) (*Void, error) {
    err := self.Channel.CallMethod(&AdminServiceDesc.Methods[3], in)
    return &Void{}, err
}
type IAdminInterface interface {
    RegisterServer(*ServerInfoMessage) (*Void, error)
    ReplyCommand(*CommandResult) (*Void, error)
    ActiveTick(*Void) (*Void, error)
    ReplyHttpCommand(*HttpAPICommandResponse) (*Void, error)
}

func GameServer_DoCommand_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(CommandInfo)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).DoCommand(in)
}
func GameServer_DoHttpCommand_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(HttpAPICommand)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).DoHttpCommand(in)
}
func GameServer_ActiveTickCallback_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(Void)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).ActiveTickCallback(in)
}
var GameServerServiceDesc = prpc.ServiceDesc{
    ServiceName: "adminGsManager.GameServer",
    Methods: []prpc.MethodDesc{
        {
            MethodName:  "DoCommand",
            MethodIndex: 0,
            Handler:     GameServer_DoCommand_Handler,
        },
        {
            MethodName:  "DoHttpCommand",
            MethodIndex: 1,
            Handler:     GameServer_DoHttpCommand_Handler,
        },
        {
            MethodName:  "ActiveTickCallback",
            MethodIndex: 2,
            Handler:     GameServer_ActiveTickCallback_Handler,
        },
    },
}

func NewGameServerService(client prpc.IEndPoint) *prpc.ServerEndPoint {
    return &prpc.ServerEndPoint{&GameServerServiceDesc, client}
}

func NewGameServerClient(channel *prpc.RpcChannel) *GameServerClient {
    return &GameServerClient{prpc.ClientEndPoint{channel}}
}

type GameServerClient struct {
	prpc.ClientEndPoint
}
func (self *GameServerClient) DoCommand(in *CommandInfo) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[0], in)
    return &Void{}, err
}
func (self *GameServerClient) DoHttpCommand(in *HttpAPICommand) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[1], in)
    return &Void{}, err
}
func (self *GameServerClient) ActiveTickCallback(in *Void) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[2], in)
    return &Void{}, err
}
type IGameServerInterface interface {
    DoCommand(*CommandInfo) (*Void, error)
    DoHttpCommand(*HttpAPICommand) (*Void, error)
    ActiveTickCallback(*Void) (*Void, error)
}

