/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class Creation : CreationBase)
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Creation.def
	// Please inherit and implement "class Creation : CreationBase"
	public abstract class CreationBase : ModelEntity
	{
		public EntityBaseEntityCall_CreationBase baseEntityCall = null;
		public EntityCellEntityCall_CreationBase cellEntityCall = null;

		public float PVPDmg = 0f;
		public float PVPDmgAnti = 0f;
		public float adjAntiFatal = 0f;
		public float adjAntiMortal = 0f;
		public float adjBloodSuck = 0f;
		
		public Int32 adjDebilityAnti = 0;
		public Int32 adjDebilityEnh = 0;
		public Int32 adjDmgArmor = 0;
		public Int32 adjDodge = 0;
		public float adjFatal = 0f;
		public Int32 adjFullHp = 0;
		public Int32 adjFullHpAbs = 0;
		public Int32 adjFullMp = 0;
		public Int32 adjFullMpAbs = 0;
		public Int32 adjHit = 0;
		public float adjHp = 0f;
		public float adjIgnoreArmor = 0f;
		public Int32 adjKnockAnti = 0;
		public Int32 adjKnockEnh = 0;
		public float adjMortal = 0f;
		public Int32 adjSilentAnti = 0;
		public Int32 adjSilentEnh = 0;
		public Int32 adjStunAnti = 0;
		public Int32 adjStunEnh = 0;
		public float antiFatal = 0f;
		public float antiMortal = 0f;
		public Int32 atkBless = 0;
		public Int32 baseDmgArmor = 0;
		public float baseIgnoreArmor = 0f;
		public float bePushedSpeed = 0f;
		public float bloodSuck = 0f;
		
		public virtual void onCasterTeamIdChanged(UInt64 oldValue) {}
		
		public virtual void onCreationIdChanged(Int32 oldValue) {}
		public Int32 debilityAnti = 0;
		public Int32 debilityEnh = 0;
		public Int32 dmgArmor = 0;
		public Int32 dodge = 0;
		
		public float extraDmg = 0f;
		public float extraDmgDef = 0f;
		public float fatal = 0f;
		public float finalDmg = 0f;
		public float finalDmgAnti = 0f;
		
		public Int32 frozenAnti = 0;
		public Int32 frozenEnh = 0;
		
		
		
		public Int32 hit = 0;
		public float hitRate = 0.0f;
		
		public Byte hostType = 0;
		public virtual void onHostTypeChanged(Byte oldValue) {}
		
		public float ignoreArmor = 0f;
		
		public Int32 knockAnti = 0;
		public Int32 knockEnh = 0;
		
		public Int32 magicArmor = 0;
		public Int32 maxMagicAtk = 0;
		public Int32 maxPhysicalAtk = 0;
		public Int32 minMagicAtk = 0;
		public Int32 minPhysicalAtk = 0;
		public float monsterDmg = 0f;
		public float monsterDmgAnti = 0f;
		public float mortal = 0f;
		
		public float mulBloodSuck = 0f;
		public float mulBossDmg = 0.0f;
		
		public float mulFullHp = 0f;
		public float mulFullMp = 0f;
		public float mulHp = 0f;
		
		public Int32 physicalArmor = 0;
		public Int32 realDmg = 0;
		public Int32 realDmgDef = 0;
		
		public Int32 silentAnti = 0;
		public Int32 silentEnh = 0;
		public float skillCD = 0f;
		public Int32 slowAnti = 0;
		public Int32 slowEnh = 0;
		
		
		public Int32 spirit = 0;
		
		
		public Int32 stunAnti = 0;
		public Int32 stunEnh = 0;
		public string type = "";
		public virtual void onTypeChanged(string oldValue) {}


		public CreationBase()
		{
		}

		public override void onComponentsEnterworld()
		{
		}

		public override void onComponentsLeaveworld()
		{
		}

		public override void onGetBase()
		{
			baseEntityCall = new EntityBaseEntityCall_CreationBase(id, className);
		}

		public override void onGetCell()
		{
			cellEntityCall = new EntityCellEntityCall_CreationBase(id, className);
		}

		public override void onLoseCell()
		{
			cellEntityCall = null;
		}

		public override EntityCall getBaseEntityCall()
		{
			return baseEntityCall;
		}

		public override EntityCall getCellEntityCall()
		{
			return cellEntityCall;
		}

		public override void attachComponents()
		{
		}

		public override void detachComponents()
		{
		}

		public override void onRemoteMethodCall(MemoryStream stream)
		{
			ScriptModule sm = EntityDef.moduledefs["Creation"];

			UInt16 methodUtype = 0;
			UInt16 componentPropertyUType = 0;

			if(sm.usePropertyDescrAlias)
			{
				componentPropertyUType = stream.readUint8();
			}
			else
			{
				componentPropertyUType = stream.readUint16();
			}

			if(sm.useMethodDescrAlias)
			{
				methodUtype = stream.readUint8();
			}
			else
			{
				methodUtype = stream.readUint16();
			}

			Method method = null;

			if(componentPropertyUType == 0)
			{
				method = sm.idmethods[methodUtype];
			}
			else
			{
				Property pComponentPropertyDescription = sm.idpropertys[componentPropertyUType];
				switch(pComponentPropertyDescription.properUtype)
				{
					default:
						break;
				}

				return;
			}

			switch(method.methodUtype)
			{
				case 619:
					UInt32 notifyCastingSkill_arg1 = stream.readUint32();
					double notifyCastingSkill_arg2 = stream.readDouble();
					notifyCastingSkill(notifyCastingSkill_arg1, notifyCastingSkill_arg2);
					break;
				case 598:
					CLIENT_AUREOLE_VAL onAddAureole_arg1 = ((DATATYPE_CLIENT_AUREOLE_VAL)method.args[0]).createFromStreamEx(stream);
					onAddAureole(onAddAureole_arg1);
					break;
				case 601:
					CLIENT_AUREOLE_VAL onAddAureoleFromOthers_arg1 = ((DATATYPE_CLIENT_AUREOLE_VAL)method.args[0]).createFromStreamEx(stream);
					onAddAureoleFromOthers(onAddAureoleFromOthers_arg1);
					break;
				case 611:
					CLIENT_BUFF_VAL onAddBuff_arg1 = ((DATATYPE_CLIENT_BUFF_VAL)method.args[0]).createFromStreamEx(stream);
					onAddBuff(onAddBuff_arg1);
					break;
				case 591:
					UInt32 onAddPassiveSkill_arg1 = stream.readUint32();
					UInt32 onAddPassiveSkill_arg2 = stream.readUint32();
					onAddPassiveSkill(onAddPassiveSkill_arg1, onAddPassiveSkill_arg2);
					break;
				case 590:
					UInt32 onAddSkill_arg1 = stream.readUint32();
					UInt32 onAddSkill_arg2 = stream.readUint32();
					Byte onAddSkill_arg3 = stream.readUint8();
					double onAddSkill_arg4 = stream.readDouble();
					float onAddSkill_arg5 = stream.readFloat();
					Byte onAddSkill_arg6 = stream.readUint8();
					onAddSkill(onAddSkill_arg1, onAddSkill_arg2, onAddSkill_arg3, onAddSkill_arg4, onAddSkill_arg5, onAddSkill_arg6);
					break;
				case 606:
					Int32 onAddStateRet_arg1 = stream.readInt32();
					Int32 onAddStateRet_arg2 = stream.readInt32();
					Int32 onAddStateRet_arg3 = stream.readInt32();
					Int32 onAddStateRet_arg4 = stream.readInt32();
					onAddStateRet(onAddStateRet_arg1, onAddStateRet_arg2, onAddStateRet_arg3, onAddStateRet_arg4);
					break;
				case 608:
					Int32 onBreakCastingSkill_arg1 = stream.readInt32();
					UInt32 onBreakCastingSkill_arg2 = stream.readUint32();
					Int32 onBreakCastingSkill_arg3 = stream.readInt32();
					onBreakCastingSkill(onBreakCastingSkill_arg1, onBreakCastingSkill_arg2, onBreakCastingSkill_arg3);
					break;
				case 609:
					Int32 onBreakChannelingSkill_arg1 = stream.readInt32();
					UInt32 onBreakChannelingSkill_arg2 = stream.readUint32();
					Int32 onBreakChannelingSkill_arg3 = stream.readInt32();
					onBreakChannelingSkill(onBreakChannelingSkill_arg1, onBreakChannelingSkill_arg2, onBreakChannelingSkill_arg3);
					break;
				case 604:
					List<float> onDropRuneIds_arg1 = ((DATATYPE_AnonymousArray_10007)method.args[0]).createFromStreamEx(stream);
					Int32 onDropRuneIds_arg2 = stream.readInt32();
					List<Int32> onDropRuneIds_arg3 = ((DATATYPE_AnonymousArray_10013)method.args[2]).createFromStreamEx(stream);
					onDropRuneIds(onDropRuneIds_arg1, onDropRuneIds_arg2, onDropRuneIds_arg3);
					break;
				case 621:
					Byte onFlashSkillZed_arg1 = stream.readUint8();
					onFlashSkillZed(onFlashSkillZed_arg1);
					break;
				case 615:
					Int32 onGetAureoleInfo_arg1 = stream.readInt32();
					CLIENT_AUREOLES onGetAureoleInfo_arg2 = ((DATATYPE_CLIENT_AUREOLES)method.args[1]).createFromStreamEx(stream);
					onGetAureoleInfo(onGetAureoleInfo_arg1, onGetAureoleInfo_arg2);
					break;
				case 614:
					Int32 onGetBuffInfo_arg1 = stream.readInt32();
					CLIENT_BUFFS onGetBuffInfo_arg2 = ((DATATYPE_CLIENT_BUFFS)method.args[1]).createFromStreamEx(stream);
					onGetBuffInfo(onGetBuffInfo_arg1, onGetBuffInfo_arg2);
					break;
				case 607:
					Int32 onMessage_arg1 = stream.readInt32();
					List<string> onMessage_arg2 = ((DATATYPE_AnonymousArray_10001)method.args[1]).createFromStreamEx(stream);
					onMessage(onMessage_arg1, onMessage_arg2);
					break;
				case 620:
					Byte onMultiAtkStage_arg1 = stream.readUint8();
					UInt32 onMultiAtkStage_arg2 = stream.readUint32();
					Int32 onMultiAtkStage_arg3 = stream.readInt32();
					List<float> onMultiAtkStage_arg4 = ((DATATYPE_AnonymousArray_10007)method.args[3]).createFromStreamEx(stream);
					List<Int32> onMultiAtkStage_arg5 = ((DATATYPE_AnonymousArray_10004)method.args[4]).createFromStreamEx(stream);
					onMultiAtkStage(onMultiAtkStage_arg1, onMultiAtkStage_arg2, onMultiAtkStage_arg3, onMultiAtkStage_arg4, onMultiAtkStage_arg5);
					break;
				case 596:
					Int32 onOthersSkillDamage_arg1 = stream.readInt32();
					List<Int32> onOthersSkillDamage_arg2 = ((DATATYPE_AnonymousArray_10004)method.args[1]).createFromStreamEx(stream);
					onOthersSkillDamage(onOthersSkillDamage_arg1, onOthersSkillDamage_arg2);
					break;
				case 599:
					Int32 onRemoveAureole_arg1 = stream.readInt32();
					onRemoveAureole(onRemoveAureole_arg1);
					break;
				case 602:
					Int32 onRemoveAureoleFromOthers_arg1 = stream.readInt32();
					onRemoveAureoleFromOthers(onRemoveAureoleFromOthers_arg1);
					break;
				case 612:
					Int32 onRemoveBuff_arg1 = stream.readInt32();
					List<UInt64> onRemoveBuff_arg2 = ((DATATYPE_AnonymousArray_10014)method.args[1]).createFromStreamEx(stream);
					onRemoveBuff(onRemoveBuff_arg1, onRemoveBuff_arg2);
					break;
				case 605:
					UInt32 onRemoveRune_arg1 = stream.readUint32();
					Int32 onRemoveRune_arg2 = stream.readInt32();
					onRemoveRune(onRemoveRune_arg1, onRemoveRune_arg2);
					break;
				case 597:
					UInt32 onServerUseSkill_arg1 = stream.readUint32();
					onServerUseSkill(onServerUseSkill_arg1);
					break;
				case 616:
					UInt32 onSetAddSkillCd_arg1 = stream.readUint32();
					float onSetAddSkillCd_arg2 = stream.readFloat();
					double onSetAddSkillCd_arg3 = stream.readDouble();
					Byte onSetAddSkillCd_arg4 = stream.readUint8();
					onSetAddSkillCd(onSetAddSkillCd_arg1, onSetAddSkillCd_arg2, onSetAddSkillCd_arg3, onSetAddSkillCd_arg4);
					break;
				case 622:
					UInt32 onShooterSkillCanUse_arg1 = stream.readUint32();
					double onShooterSkillCanUse_arg2 = stream.readDouble();
					Byte onShooterSkillCanUse_arg3 = stream.readUint8();
					onShooterSkillCanUse(onShooterSkillCanUse_arg1, onShooterSkillCanUse_arg2, onShooterSkillCanUse_arg3);
					break;
				case 595:
					SKILL_DAMAGE_INFO onSkillDamage_arg1 = ((DATATYPE_SKILL_DAMAGE_INFO)method.args[0]).createFromStreamEx(stream);
					onSkillDamage(onSkillDamage_arg1);
					break;
				case 618:
					UInt32 onSkillTeleport_arg1 = stream.readUint32();
					Vector3 onSkillTeleport_arg2 = stream.readVector3();
					onSkillTeleport(onSkillTeleport_arg1, onSkillTeleport_arg2);
					break;
				case 600:
					CLIENT_AUREOLES onUpdateAureoles_arg1 = ((DATATYPE_CLIENT_AUREOLES)method.args[0]).createFromStreamEx(stream);
					onUpdateAureoles(onUpdateAureoles_arg1);
					break;
				case 603:
					AUREOLE_FROM_OTHERS onUpdateAureolesFromOthers_arg1 = ((DATATYPE_AUREOLE_FROM_OTHERS)method.args[0]).createFromStreamEx(stream);
					onUpdateAureolesFromOthers(onUpdateAureolesFromOthers_arg1);
					break;
				case 613:
					CLIENT_BUFF_VAL onUpdateBuff_arg1 = ((DATATYPE_CLIENT_BUFF_VAL)method.args[0]).createFromStreamEx(stream);
					onUpdateBuff(onUpdateBuff_arg1);
					break;
				case 610:
					CLIENT_BUFFS onUpdateBuffs_arg1 = ((DATATYPE_CLIENT_BUFFS)method.args[0]).createFromStreamEx(stream);
					onUpdateBuffs(onUpdateBuffs_arg1);
					break;
				case 593:
					Int32 onUseCasting_arg1 = stream.readInt32();
					UInt32 onUseCasting_arg2 = stream.readUint32();
					Int32 onUseCasting_arg3 = stream.readInt32();
					List<float> onUseCasting_arg4 = ((DATATYPE_AnonymousArray_10007)method.args[3]).createFromStreamEx(stream);
					List<Int32> onUseCasting_arg5 = ((DATATYPE_AnonymousArray_10004)method.args[4]).createFromStreamEx(stream);
					onUseCasting(onUseCasting_arg1, onUseCasting_arg2, onUseCasting_arg3, onUseCasting_arg4, onUseCasting_arg5);
					break;
				case 594:
					Int32 onUseChanneling_arg1 = stream.readInt32();
					UInt32 onUseChanneling_arg2 = stream.readUint32();
					Int32 onUseChanneling_arg3 = stream.readInt32();
					List<float> onUseChanneling_arg4 = ((DATATYPE_AnonymousArray_10007)method.args[3]).createFromStreamEx(stream);
					List<Int32> onUseChanneling_arg5 = ((DATATYPE_AnonymousArray_10004)method.args[4]).createFromStreamEx(stream);
					Int32 onUseChanneling_arg6 = stream.readInt32();
					onUseChanneling(onUseChanneling_arg1, onUseChanneling_arg2, onUseChanneling_arg3, onUseChanneling_arg4, onUseChanneling_arg5, onUseChanneling_arg6);
					break;
				case 592:
					Byte onUseSkill_arg1 = stream.readUint8();
					UInt32 onUseSkill_arg2 = stream.readUint32();
					Int32 onUseSkill_arg3 = stream.readInt32();
					List<float> onUseSkill_arg4 = ((DATATYPE_AnonymousArray_10007)method.args[3]).createFromStreamEx(stream);
					List<Int32> onUseSkill_arg5 = ((DATATYPE_AnonymousArray_10004)method.args[4]).createFromStreamEx(stream);
					onUseSkill(onUseSkill_arg1, onUseSkill_arg2, onUseSkill_arg3, onUseSkill_arg4, onUseSkill_arg5);
					break;
				case 617:
					UInt32 skillTeleportBefore_arg1 = stream.readUint32();
					skillTeleportBefore(skillTeleportBefore_arg1);
					break;
				default:
					break;
			};
		}

		public override void onUpdatePropertys(MemoryStream stream)
		{
			ScriptModule sm = EntityDef.moduledefs["Creation"];
			Dictionary<UInt16, Property> pdatas = sm.idpropertys;

			while(stream.length() > 0)
			{
				UInt16 _t_utype = 0;
				{
					if(sm.usePropertyDescrAlias)
					{
						_t_utype = stream.readUint8();
					}
					else
					{
						_t_utype = stream.readUint16();
					}
				}

				Property prop = null;

				if(_t_utype != 0)
				{
					prop = pdatas[_t_utype];
				}
				else
				{
					Property pComponentPropertyDescription = pdatas[_t_utype];
					switch(pComponentPropertyDescription.properUtype)
					{
						default:
							break;
					}

					return;
				}

				switch(prop.properUtype)
				{
					case 602:
						float oldval_PVPDmg = PVPDmg;
						PVPDmg = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onPVPDmgChanged(oldval_PVPDmg);
						}
						else
						{
							if(inWorld)
								onPVPDmgChanged(oldval_PVPDmg);
						}

						break;
					case 603:
						float oldval_PVPDmgAnti = PVPDmgAnti;
						PVPDmgAnti = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onPVPDmgAntiChanged(oldval_PVPDmgAnti);
						}
						else
						{
							if(inWorld)
								onPVPDmgAntiChanged(oldval_PVPDmgAnti);
						}

						break;
					case 360:
						float oldval_adjAntiFatal = adjAntiFatal;
						adjAntiFatal = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onAdjAntiFatalChanged(oldval_adjAntiFatal);
						}
						else
						{
							if(inWorld)
								onAdjAntiFatalChanged(oldval_adjAntiFatal);
						}

						break;
					case 350:
						float oldval_adjAntiMortal = adjAntiMortal;
						adjAntiMortal = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onAdjAntiMortalChanged(oldval_adjAntiMortal);
						}
						else
						{
							if(inWorld)
								onAdjAntiMortalChanged(oldval_adjAntiMortal);
						}

						break;
					case 357:
						float oldval_adjBloodSuck = adjBloodSuck;
						adjBloodSuck = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onAdjBloodSuckChanged(oldval_adjBloodSuck);
						}
						else
						{
							if(inWorld)
								onAdjBloodSuckChanged(oldval_adjBloodSuck);
						}

						break;
					case 352:
						float oldval_adjCD = adjCD;
						adjCD = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onAdjCDChanged(oldval_adjCD);
						}
						else
						{
							if(inWorld)
								onAdjCDChanged(oldval_adjCD);
						}

						break;
					case 336:
						Int32 oldval_adjDebilityAnti = adjDebilityAnti;
						adjDebilityAnti = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onAdjDebilityAntiChanged(oldval_adjDebilityAnti);
						}
						else
						{
							if(inWorld)
								onAdjDebilityAntiChanged(oldval_adjDebilityAnti);
						}

						break;
					case 326:
						Int32 oldval_adjDebilityEnh = adjDebilityEnh;
						adjDebilityEnh = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onAdjDebilityEnhChanged(oldval_adjDebilityEnh);
						}
						else
						{
							if(inWorld)
								onAdjDebilityEnhChanged(oldval_adjDebilityEnh);
						}

						break;
					case 580:
						Int32 oldval_adjDmgArmor = adjDmgArmor;
						adjDmgArmor = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onAdjDmgArmorChanged(oldval_adjDmgArmor);
						}
						else
						{
							if(inWorld)
								onAdjDmgArmorChanged(oldval_adjDmgArmor);
						}

						break;
					case 344:
						Int32 oldval_adjDodge = adjDodge;
						adjDodge = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onAdjDodgeChanged(oldval_adjDodge);
						}
						else
						{
							if(inWorld)
								onAdjDodgeChanged(oldval_adjDodge);
						}

						break;
					case 294:
						float oldval_adjFatal = adjFatal;
						adjFatal = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onAdjFatalChanged(oldval_adjFatal);
						}
						else
						{
							if(inWorld)
								onAdjFatalChanged(oldval_adjFatal);
						}

						break;
					case 337:
						Int32 oldval_adjFullHp = adjFullHp;
						adjFullHp = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onAdjFullHpChanged(oldval_adjFullHp);
						}
						else
						{
							if(inWorld)
								onAdjFullHpChanged(oldval_adjFullHp);
						}

						break;
					case 338:
						Int32 oldval_adjFullHpAbs = adjFullHpAbs;
						adjFullHpAbs = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onAdjFullHpAbsChanged(oldval_adjFullHpAbs);
						}
						else
						{
							if(inWorld)
								onAdjFullHpAbsChanged(oldval_adjFullHpAbs);
						}

						break;
					case 340:
						Int32 oldval_adjFullMp = adjFullMp;
						adjFullMp = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onAdjFullMpChanged(oldval_adjFullMp);
						}
						else
						{
							if(inWorld)
								onAdjFullMpChanged(oldval_adjFullMp);
						}

						break;
					case 342:
						Int32 oldval_adjFullMpAbs = adjFullMpAbs;
						adjFullMpAbs = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onAdjFullMpAbsChanged(oldval_adjFullMpAbs);
						}
						else
						{
							if(inWorld)
								onAdjFullMpAbsChanged(oldval_adjFullMpAbs);
						}

						break;
					case 351:
						Int32 oldval_adjHit = adjHit;
						adjHit = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onAdjHitChanged(oldval_adjHit);
						}
						else
						{
							if(inWorld)
								onAdjHitChanged(oldval_adjHit);
						}

						break;
					case 304:
						float oldval_adjHp = adjHp;
						adjHp = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onAdjHpChanged(oldval_adjHp);
						}
						else
						{
							if(inWorld)
								onAdjHpChanged(oldval_adjHp);
						}

						break;
					case 565:
						float oldval_adjIgnoreArmor = adjIgnoreArmor;
						adjIgnoreArmor = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onAdjIgnoreArmorChanged(oldval_adjIgnoreArmor);
						}
						else
						{
							if(inWorld)
								onAdjIgnoreArmorChanged(oldval_adjIgnoreArmor);
						}

						break;
					case 334:
						Int32 oldval_adjKnockAnti = adjKnockAnti;
						adjKnockAnti = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onAdjKnockAntiChanged(oldval_adjKnockAnti);
						}
						else
						{
							if(inWorld)
								onAdjKnockAntiChanged(oldval_adjKnockAnti);
						}

						break;
					case 324:
						Int32 oldval_adjKnockEnh = adjKnockEnh;
						adjKnockEnh = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onAdjKnockEnhChanged(oldval_adjKnockEnh);
						}
						else
						{
							if(inWorld)
								onAdjKnockEnhChanged(oldval_adjKnockEnh);
						}

						break;
					case 343:
						float oldval_adjMortal = adjMortal;
						adjMortal = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onAdjMortalChanged(oldval_adjMortal);
						}
						else
						{
							if(inWorld)
								onAdjMortalChanged(oldval_adjMortal);
						}

						break;
					case 332:
						Int32 oldval_adjSilentAnti = adjSilentAnti;
						adjSilentAnti = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onAdjSilentAntiChanged(oldval_adjSilentAnti);
						}
						else
						{
							if(inWorld)
								onAdjSilentAntiChanged(oldval_adjSilentAnti);
						}

						break;
					case 322:
						Int32 oldval_adjSilentEnh = adjSilentEnh;
						adjSilentEnh = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onAdjSilentEnhChanged(oldval_adjSilentEnh);
						}
						else
						{
							if(inWorld)
								onAdjSilentEnhChanged(oldval_adjSilentEnh);
						}

						break;
					case 330:
						Int32 oldval_adjStunAnti = adjStunAnti;
						adjStunAnti = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onAdjStunAntiChanged(oldval_adjStunAnti);
						}
						else
						{
							if(inWorld)
								onAdjStunAntiChanged(oldval_adjStunAnti);
						}

						break;
					case 320:
						Int32 oldval_adjStunEnh = adjStunEnh;
						adjStunEnh = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onAdjStunEnhChanged(oldval_adjStunEnh);
						}
						else
						{
							if(inWorld)
								onAdjStunEnhChanged(oldval_adjStunEnh);
						}

						break;
					case 359:
						float oldval_antiFatal = antiFatal;
						antiFatal = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onAntiFatalChanged(oldval_antiFatal);
						}
						else
						{
							if(inWorld)
								onAntiFatalChanged(oldval_antiFatal);
						}

						break;
					case 345:
						float oldval_antiMortal = antiMortal;
						antiMortal = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onAntiMortalChanged(oldval_antiMortal);
						}
						else
						{
							if(inWorld)
								onAntiMortalChanged(oldval_antiMortal);
						}

						break;
					case 372:
						Int32 oldval_atkBless = atkBless;
						atkBless = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onAtkBlessChanged(oldval_atkBless);
						}
						else
						{
							if(inWorld)
								onAtkBlessChanged(oldval_atkBless);
						}

						break;
					case 567:
						Int32 oldval_baseDmgArmor = baseDmgArmor;
						baseDmgArmor = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onBaseDmgArmorChanged(oldval_baseDmgArmor);
						}
						else
						{
							if(inWorld)
								onBaseDmgArmorChanged(oldval_baseDmgArmor);
						}

						break;
					case 564:
						float oldval_baseIgnoreArmor = baseIgnoreArmor;
						baseIgnoreArmor = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onBaseIgnoreArmorChanged(oldval_baseIgnoreArmor);
						}
						else
						{
							if(inWorld)
								onBaseIgnoreArmorChanged(oldval_baseIgnoreArmor);
						}

						break;
					case 354:
						float oldval_bePushedSpeed = bePushedSpeed;
						bePushedSpeed = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onBePushedSpeedChanged(oldval_bePushedSpeed);
						}
						else
						{
							if(inWorld)
								onBePushedSpeedChanged(oldval_bePushedSpeed);
						}

						break;
					case 356:
						float oldval_bloodSuck = bloodSuck;
						bloodSuck = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onBloodSuckChanged(oldval_bloodSuck);
						}
						else
						{
							if(inWorld)
								onBloodSuckChanged(oldval_bloodSuck);
						}

						break;
					case 280:
						UInt64 oldval_casterTeamId = casterTeamId;
						casterTeamId = stream.readUint64();

						if(prop.isBase())
						{
							if(inited)
								onCasterTeamIdChanged(oldval_casterTeamId);
						}
						else
						{
							if(inWorld)
								onCasterTeamIdChanged(oldval_casterTeamId);
						}

						break;
					case 277:
						Int32 oldval_creationId = creationId;
						creationId = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onCreationIdChanged(oldval_creationId);
						}
						else
						{
							if(inWorld)
								onCreationIdChanged(oldval_creationId);
						}

						break;
					case 335:
						Int32 oldval_debilityAnti = debilityAnti;
						debilityAnti = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onDebilityAntiChanged(oldval_debilityAnti);
						}
						else
						{
							if(inWorld)
								onDebilityAntiChanged(oldval_debilityAnti);
						}

						break;
					case 325:
						Int32 oldval_debilityEnh = debilityEnh;
						debilityEnh = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onDebilityEnhChanged(oldval_debilityEnh);
						}
						else
						{
							if(inWorld)
								onDebilityEnhChanged(oldval_debilityEnh);
						}

						break;
					case 40001:
						Vector3 oldval_direction = direction;
						direction = stream.readVector3();

						if(prop.isBase())
						{
							if(inited)
								onDirectionChanged(oldval_direction);
						}
						else
						{
							if(inWorld)
								onDirectionChanged(oldval_direction);
						}

						break;
					case 566:
						Int32 oldval_dmgArmor = dmgArmor;
						dmgArmor = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onDmgArmorChanged(oldval_dmgArmor);
						}
						else
						{
							if(inWorld)
								onDmgArmorChanged(oldval_dmgArmor);
						}

						break;
					case 308:
						Int32 oldval_dodge = dodge;
						dodge = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onDodgeChanged(oldval_dodge);
						}
						else
						{
							if(inWorld)
								onDodgeChanged(oldval_dodge);
						}

						break;
					case 412:
						Byte oldval_dunTimeFreezeFlag = dunTimeFreezeFlag;
						dunTimeFreezeFlag = stream.readUint8();

						if(prop.isBase())
						{
							if(inited)
								onDunTimeFreezeFlagChanged(oldval_dunTimeFreezeFlag);
						}
						else
						{
							if(inWorld)
								onDunTimeFreezeFlagChanged(oldval_dunTimeFreezeFlag);
						}

						break;
					case 600:
						float oldval_extraDmg = extraDmg;
						extraDmg = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onExtraDmgChanged(oldval_extraDmg);
						}
						else
						{
							if(inWorld)
								onExtraDmgChanged(oldval_extraDmg);
						}

						break;
					case 601:
						float oldval_extraDmgDef = extraDmgDef;
						extraDmgDef = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onExtraDmgDefChanged(oldval_extraDmgDef);
						}
						else
						{
							if(inWorld)
								onExtraDmgDefChanged(oldval_extraDmgDef);
						}

						break;
					case 291:
						float oldval_fatal = fatal;
						fatal = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onFatalChanged(oldval_fatal);
						}
						else
						{
							if(inWorld)
								onFatalChanged(oldval_fatal);
						}

						break;
					case 606:
						float oldval_finalDmg = finalDmg;
						finalDmg = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onFinalDmgChanged(oldval_finalDmg);
						}
						else
						{
							if(inWorld)
								onFinalDmgChanged(oldval_finalDmg);
						}

						break;
					case 619:
						float oldval_finalDmgAnti = finalDmgAnti;
						finalDmgAnti = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onFinalDmgAntiChanged(oldval_finalDmgAnti);
						}
						else
						{
							if(inWorld)
								onFinalDmgAntiChanged(oldval_finalDmgAnti);
						}

						break;
					case 410:
						Int32 oldval_force = force;
						force = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onForceChanged(oldval_force);
						}
						else
						{
							if(inWorld)
								onForceChanged(oldval_force);
						}

						break;
					case 381:
						Int32 oldval_frozenAnti = frozenAnti;
						frozenAnti = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onFrozenAntiChanged(oldval_frozenAnti);
						}
						else
						{
							if(inWorld)
								onFrozenAntiChanged(oldval_frozenAnti);
						}

						break;
					case 380:
						Int32 oldval_frozenEnh = frozenEnh;
						frozenEnh = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onFrozenEnhChanged(oldval_frozenEnh);
						}
						else
						{
							if(inWorld)
								onFrozenEnhChanged(oldval_frozenEnh);
						}

						break;
					case 295:
						Int32 oldval_fullHp = fullHp;
						fullHp = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onFullHpChanged(oldval_fullHp);
						}
						else
						{
							if(inWorld)
								onFullHpChanged(oldval_fullHp);
						}

						break;
					case 311:
						Int32 oldval_fullMp = fullMp;
						fullMp = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onFullMpChanged(oldval_fullMp);
						}
						else
						{
							if(inWorld)
								onFullMpChanged(oldval_fullMp);
						}

						break;
					case 411:
						Int64 oldval_gameEntityId = gameEntityId;
						gameEntityId = stream.readInt64();

						if(prop.isBase())
						{
							if(inited)
								onGameEntityIdChanged(oldval_gameEntityId);
						}
						else
						{
							if(inWorld)
								onGameEntityIdChanged(oldval_gameEntityId);
						}

						break;
					case 293:
						Int32 oldval_hit = hit;
						hit = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onHitChanged(oldval_hit);
						}
						else
						{
							if(inWorld)
								onHitChanged(oldval_hit);
						}

						break;
					case 364:
						float oldval_hitRate = hitRate;
						hitRate = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onHitRateChanged(oldval_hitRate);
						}
						else
						{
							if(inWorld)
								onHitRateChanged(oldval_hitRate);
						}

						break;
					case 278:
						Int32 oldval_hostId = hostId;
						hostId = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onHostIdChanged(oldval_hostId);
						}
						else
						{
							if(inWorld)
								onHostIdChanged(oldval_hostId);
						}

						break;
					case 279:
						Byte oldval_hostType = hostType;
						hostType = stream.readUint8();

						if(prop.isBase())
						{
							if(inited)
								onHostTypeChanged(oldval_hostType);
						}
						else
						{
							if(inWorld)
								onHostTypeChanged(oldval_hostType);
						}

						break;
					case 302:
						Int32 oldval_hp = hp;
						hp = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onHpChanged(oldval_hp);
						}
						else
						{
							if(inWorld)
								onHpChanged(oldval_hp);
						}

						break;
					case 563:
						float oldval_ignoreArmor = ignoreArmor;
						ignoreArmor = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onIgnoreArmorChanged(oldval_ignoreArmor);
						}
						else
						{
							if(inWorld)
								onIgnoreArmorChanged(oldval_ignoreArmor);
						}

						break;
					case 287:
						Byte oldval_isWitnessComplete = isWitnessComplete;
						isWitnessComplete = stream.readUint8();

						if(prop.isBase())
						{
							if(inited)
								onIsWitnessCompleteChanged(oldval_isWitnessComplete);
						}
						else
						{
							if(inWorld)
								onIsWitnessCompleteChanged(oldval_isWitnessComplete);
						}

						break;
					case 333:
						Int32 oldval_knockAnti = knockAnti;
						knockAnti = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onKnockAntiChanged(oldval_knockAnti);
						}
						else
						{
							if(inWorld)
								onKnockAntiChanged(oldval_knockAnti);
						}

						break;
					case 323:
						Int32 oldval_knockEnh = knockEnh;
						knockEnh = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onKnockEnhChanged(oldval_knockEnh);
						}
						else
						{
							if(inWorld)
								onKnockEnhChanged(oldval_knockEnh);
						}

						break;
					case 288:
						UInt32 oldval_level = level;
						level = stream.readUint32();

						if(prop.isBase())
						{
							if(inited)
								onLevelChanged(oldval_level);
						}
						else
						{
							if(inWorld)
								onLevelChanged(oldval_level);
						}

						break;
					case 582:
						Int32 oldval_magicArmor = magicArmor;
						magicArmor = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onMagicArmorChanged(oldval_magicArmor);
						}
						else
						{
							if(inWorld)
								onMagicArmorChanged(oldval_magicArmor);
						}

						break;
					case 371:
						Int32 oldval_maxMagicAtk = maxMagicAtk;
						maxMagicAtk = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onMaxMagicAtkChanged(oldval_maxMagicAtk);
						}
						else
						{
							if(inWorld)
								onMaxMagicAtkChanged(oldval_maxMagicAtk);
						}

						break;
					case 369:
						Int32 oldval_maxPhysicalAtk = maxPhysicalAtk;
						maxPhysicalAtk = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onMaxPhysicalAtkChanged(oldval_maxPhysicalAtk);
						}
						else
						{
							if(inWorld)
								onMaxPhysicalAtkChanged(oldval_maxPhysicalAtk);
						}

						break;
					case 370:
						Int32 oldval_minMagicAtk = minMagicAtk;
						minMagicAtk = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onMinMagicAtkChanged(oldval_minMagicAtk);
						}
						else
						{
							if(inWorld)
								onMinMagicAtkChanged(oldval_minMagicAtk);
						}

						break;
					case 368:
						Int32 oldval_minPhysicalAtk = minPhysicalAtk;
						minPhysicalAtk = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onMinPhysicalAtkChanged(oldval_minPhysicalAtk);
						}
						else
						{
							if(inWorld)
								onMinPhysicalAtkChanged(oldval_minPhysicalAtk);
						}

						break;
					case 604:
						float oldval_monsterDmg = monsterDmg;
						monsterDmg = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onMonsterDmgChanged(oldval_monsterDmg);
						}
						else
						{
							if(inWorld)
								onMonsterDmgChanged(oldval_monsterDmg);
						}

						break;
					case 605:
						float oldval_monsterDmgAnti = monsterDmgAnti;
						monsterDmgAnti = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onMonsterDmgAntiChanged(oldval_monsterDmgAnti);
						}
						else
						{
							if(inWorld)
								onMonsterDmgAntiChanged(oldval_monsterDmgAnti);
						}

						break;
					case 292:
						float oldval_mortal = mortal;
						mortal = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onMortalChanged(oldval_mortal);
						}
						else
						{
							if(inWorld)
								onMortalChanged(oldval_mortal);
						}

						break;
					case 318:
						float oldval_mpCostRatio = mpCostRatio;
						mpCostRatio = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onMpCostRatioChanged(oldval_mpCostRatio);
						}
						else
						{
							if(inWorld)
								onMpCostRatioChanged(oldval_mpCostRatio);
						}

						break;
					case 358:
						float oldval_mulBloodSuck = mulBloodSuck;
						mulBloodSuck = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onMulBloodSuckChanged(oldval_mulBloodSuck);
						}
						else
						{
							if(inWorld)
								onMulBloodSuckChanged(oldval_mulBloodSuck);
						}

						break;
					case 362:
						float oldval_mulBossDmg = mulBossDmg;
						mulBossDmg = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onMulBossDmgChanged(oldval_mulBossDmg);
						}
						else
						{
							if(inWorld)
								onMulBossDmgChanged(oldval_mulBossDmg);
						}

						break;
					case 353:
						float oldval_mulCD = mulCD;
						mulCD = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onMulCDChanged(oldval_mulCD);
						}
						else
						{
							if(inWorld)
								onMulCDChanged(oldval_mulCD);
						}

						break;
					case 339:
						float oldval_mulFullHp = mulFullHp;
						mulFullHp = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onMulFullHpChanged(oldval_mulFullHp);
						}
						else
						{
							if(inWorld)
								onMulFullHpChanged(oldval_mulFullHp);
						}

						break;
					case 341:
						float oldval_mulFullMp = mulFullMp;
						mulFullMp = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onMulFullMpChanged(oldval_mulFullMp);
						}
						else
						{
							if(inWorld)
								onMulFullMpChanged(oldval_mulFullMp);
						}

						break;
					case 306:
						float oldval_mulHp = mulHp;
						mulHp = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onMulHpChanged(oldval_mulHp);
						}
						else
						{
							if(inWorld)
								onMulHpChanged(oldval_mulHp);
						}

						break;
					case 283:
						string oldval_name = name;
						name = stream.readUnicode();

						if(prop.isBase())
						{
							if(inited)
								onNameChanged(oldval_name);
						}
						else
						{
							if(inWorld)
								onNameChanged(oldval_name);
						}

						break;
					case 581:
						Int32 oldval_physicalArmor = physicalArmor;
						physicalArmor = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onPhysicalArmorChanged(oldval_physicalArmor);
						}
						else
						{
							if(inWorld)
								onPhysicalArmorChanged(oldval_physicalArmor);
						}

						break;
					case 40000:
						Vector3 oldval_position = position;
						position = stream.readVector3();

						if(prop.isBase())
						{
							if(inited)
								onPositionChanged(oldval_position);
						}
						else
						{
							if(inWorld)
								onPositionChanged(oldval_position);
						}

						break;
					case 598:
						Int32 oldval_realDmg = realDmg;
						realDmg = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onRealDmgChanged(oldval_realDmg);
						}
						else
						{
							if(inWorld)
								onRealDmgChanged(oldval_realDmg);
						}

						break;
					case 599:
						Int32 oldval_realDmgDef = realDmgDef;
						realDmgDef = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onRealDmgDefChanged(oldval_realDmgDef);
						}
						else
						{
							if(inWorld)
								onRealDmgDefChanged(oldval_realDmgDef);
						}

						break;
					case 367:
						Int32 oldval_selectedTargetId = selectedTargetId;
						selectedTargetId = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onSelectedTargetIdChanged(oldval_selectedTargetId);
						}
						else
						{
							if(inWorld)
								onSelectedTargetIdChanged(oldval_selectedTargetId);
						}

						break;
					case 331:
						Int32 oldval_silentAnti = silentAnti;
						silentAnti = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onSilentAntiChanged(oldval_silentAnti);
						}
						else
						{
							if(inWorld)
								onSilentAntiChanged(oldval_silentAnti);
						}

						break;
					case 321:
						Int32 oldval_silentEnh = silentEnh;
						silentEnh = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onSilentEnhChanged(oldval_silentEnh);
						}
						else
						{
							if(inWorld)
								onSilentEnhChanged(oldval_silentEnh);
						}

						break;
					case 620:
						float oldval_skillCD = skillCD;
						skillCD = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onSkillCDChanged(oldval_skillCD);
						}
						else
						{
							if(inWorld)
								onSkillCDChanged(oldval_skillCD);
						}

						break;
					case 584:
						Int32 oldval_slowAnti = slowAnti;
						slowAnti = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onSlowAntiChanged(oldval_slowAnti);
						}
						else
						{
							if(inWorld)
								onSlowAntiChanged(oldval_slowAnti);
						}

						break;
					case 583:
						Int32 oldval_slowEnh = slowEnh;
						slowEnh = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onSlowEnhChanged(oldval_slowEnh);
						}
						else
						{
							if(inWorld)
								onSlowEnhChanged(oldval_slowEnh);
						}

						break;
					case 40002:
						stream.readUint32();
						break;
					case 409:
						UInt32 oldval_spaceNo = spaceNo;
						oldSpaceNo = oldval_spaceNo;
						spaceNo = stream.readUint32();

						if(prop.isBase())
						{
							if(inited)
								onSpaceNoChanged(oldval_spaceNo);
						}
						else
						{
							if(inWorld)
								onSpaceNoChanged(oldval_spaceNo);
						}

						break;
					case 355:
						float oldval_speed = speed;
						speed = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onSpeedChanged(oldval_speed);
						}
						else
						{
							if(inWorld)
								onSpeedChanged(oldval_speed);
						}

						break;
					case 585:
						Int32 oldval_spirit = spirit;
						spirit = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onSpiritChanged(oldval_spirit);
						}
						else
						{
							if(inWorld)
								onSpiritChanged(oldval_spirit);
						}

						break;
					case 289:
						Int64 oldval_state = state;
						state = stream.readInt64();

						if(prop.isBase())
						{
							if(inited)
								onStateChanged(oldval_state);
						}
						else
						{
							if(inWorld)
								onStateChanged(oldval_state);
						}

						break;
					case 290:
						Int64 oldval_state2 = state2;
						state2 = stream.readInt64();

						if(prop.isBase())
						{
							if(inited)
								onState2Changed(oldval_state2);
						}
						else
						{
							if(inWorld)
								onState2Changed(oldval_state2);
						}

						break;
					case 327:
						Int32 oldval_stunAnti = stunAnti;
						stunAnti = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onStunAntiChanged(oldval_stunAnti);
						}
						else
						{
							if(inWorld)
								onStunAntiChanged(oldval_stunAnti);
						}

						break;
					case 319:
						Int32 oldval_stunEnh = stunEnh;
						stunEnh = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onStunEnhChanged(oldval_stunEnh);
						}
						else
						{
							if(inWorld)
								onStunEnhChanged(oldval_stunEnh);
						}

						break;
					case 286:
						string oldval_type = type;
						type = stream.readString();

						if(prop.isBase())
						{
							if(inited)
								onTypeChanged(oldval_type);
						}
						else
						{
							if(inWorld)
								onTypeChanged(oldval_type);
						}

						break;
					default:
						break;
				};
			}
		}

		public override void callPropertysSetMethods()
		{
			ScriptModule sm = EntityDef.moduledefs["Creation"];
			Dictionary<UInt16, Property> pdatas = sm.idpropertys;

			float oldval_PVPDmg = PVPDmg;
			Property prop_PVPDmg = pdatas[88];
			if(prop_PVPDmg.isBase())
			{
				if(inited && !inWorld)
					onPVPDmgChanged(oldval_PVPDmg);
			}
			else
			{
				if(inWorld)
				{
					if(prop_PVPDmg.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onPVPDmgChanged(oldval_PVPDmg);
					}
				}
			}

			float oldval_PVPDmgAnti = PVPDmgAnti;
			Property prop_PVPDmgAnti = pdatas[89];
			if(prop_PVPDmgAnti.isBase())
			{
				if(inited && !inWorld)
					onPVPDmgAntiChanged(oldval_PVPDmgAnti);
			}
			else
			{
				if(inWorld)
				{
					if(prop_PVPDmgAnti.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onPVPDmgAntiChanged(oldval_PVPDmgAnti);
					}
				}
			}

			float oldval_adjAntiFatal = adjAntiFatal;
			Property prop_adjAntiFatal = pdatas[5];
			if(prop_adjAntiFatal.isBase())
			{
				if(inited && !inWorld)
					onAdjAntiFatalChanged(oldval_adjAntiFatal);
			}
			else
			{
				if(inWorld)
				{
					if(prop_adjAntiFatal.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onAdjAntiFatalChanged(oldval_adjAntiFatal);
					}
				}
			}

			float oldval_adjAntiMortal = adjAntiMortal;
			Property prop_adjAntiMortal = pdatas[6];
			if(prop_adjAntiMortal.isBase())
			{
				if(inited && !inWorld)
					onAdjAntiMortalChanged(oldval_adjAntiMortal);
			}
			else
			{
				if(inWorld)
				{
					if(prop_adjAntiMortal.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onAdjAntiMortalChanged(oldval_adjAntiMortal);
					}
				}
			}

			float oldval_adjBloodSuck = adjBloodSuck;
			Property prop_adjBloodSuck = pdatas[8];
			if(prop_adjBloodSuck.isBase())
			{
				if(inited && !inWorld)
					onAdjBloodSuckChanged(oldval_adjBloodSuck);
			}
			else
			{
				if(inWorld)
				{
					if(prop_adjBloodSuck.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onAdjBloodSuckChanged(oldval_adjBloodSuck);
					}
				}
			}

			float oldval_adjCD = adjCD;
			Property prop_adjCD = pdatas[9];
			if(prop_adjCD.isBase())
			{
				if(inited && !inWorld)
					onAdjCDChanged(oldval_adjCD);
			}
			else
			{
				if(inWorld)
				{
					if(prop_adjCD.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onAdjCDChanged(oldval_adjCD);
					}
				}
			}

			Int32 oldval_adjDebilityAnti = adjDebilityAnti;
			Property prop_adjDebilityAnti = pdatas[10];
			if(prop_adjDebilityAnti.isBase())
			{
				if(inited && !inWorld)
					onAdjDebilityAntiChanged(oldval_adjDebilityAnti);
			}
			else
			{
				if(inWorld)
				{
					if(prop_adjDebilityAnti.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onAdjDebilityAntiChanged(oldval_adjDebilityAnti);
					}
				}
			}

			Int32 oldval_adjDebilityEnh = adjDebilityEnh;
			Property prop_adjDebilityEnh = pdatas[11];
			if(prop_adjDebilityEnh.isBase())
			{
				if(inited && !inWorld)
					onAdjDebilityEnhChanged(oldval_adjDebilityEnh);
			}
			else
			{
				if(inWorld)
				{
					if(prop_adjDebilityEnh.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onAdjDebilityEnhChanged(oldval_adjDebilityEnh);
					}
				}
			}

			Int32 oldval_adjDmgArmor = adjDmgArmor;
			Property prop_adjDmgArmor = pdatas[90];
			if(prop_adjDmgArmor.isBase())
			{
				if(inited && !inWorld)
					onAdjDmgArmorChanged(oldval_adjDmgArmor);
			}
			else
			{
				if(inWorld)
				{
					if(prop_adjDmgArmor.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onAdjDmgArmorChanged(oldval_adjDmgArmor);
					}
				}
			}

			Int32 oldval_adjDodge = adjDodge;
			Property prop_adjDodge = pdatas[12];
			if(prop_adjDodge.isBase())
			{
				if(inited && !inWorld)
					onAdjDodgeChanged(oldval_adjDodge);
			}
			else
			{
				if(inWorld)
				{
					if(prop_adjDodge.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onAdjDodgeChanged(oldval_adjDodge);
					}
				}
			}

			float oldval_adjFatal = adjFatal;
			Property prop_adjFatal = pdatas[13];
			if(prop_adjFatal.isBase())
			{
				if(inited && !inWorld)
					onAdjFatalChanged(oldval_adjFatal);
			}
			else
			{
				if(inWorld)
				{
					if(prop_adjFatal.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onAdjFatalChanged(oldval_adjFatal);
					}
				}
			}

			Int32 oldval_adjFullHp = adjFullHp;
			Property prop_adjFullHp = pdatas[14];
			if(prop_adjFullHp.isBase())
			{
				if(inited && !inWorld)
					onAdjFullHpChanged(oldval_adjFullHp);
			}
			else
			{
				if(inWorld)
				{
					if(prop_adjFullHp.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onAdjFullHpChanged(oldval_adjFullHp);
					}
				}
			}

			Int32 oldval_adjFullHpAbs = adjFullHpAbs;
			Property prop_adjFullHpAbs = pdatas[15];
			if(prop_adjFullHpAbs.isBase())
			{
				if(inited && !inWorld)
					onAdjFullHpAbsChanged(oldval_adjFullHpAbs);
			}
			else
			{
				if(inWorld)
				{
					if(prop_adjFullHpAbs.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onAdjFullHpAbsChanged(oldval_adjFullHpAbs);
					}
				}
			}

			Int32 oldval_adjFullMp = adjFullMp;
			Property prop_adjFullMp = pdatas[16];
			if(prop_adjFullMp.isBase())
			{
				if(inited && !inWorld)
					onAdjFullMpChanged(oldval_adjFullMp);
			}
			else
			{
				if(inWorld)
				{
					if(prop_adjFullMp.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onAdjFullMpChanged(oldval_adjFullMp);
					}
				}
			}

			Int32 oldval_adjFullMpAbs = adjFullMpAbs;
			Property prop_adjFullMpAbs = pdatas[17];
			if(prop_adjFullMpAbs.isBase())
			{
				if(inited && !inWorld)
					onAdjFullMpAbsChanged(oldval_adjFullMpAbs);
			}
			else
			{
				if(inWorld)
				{
					if(prop_adjFullMpAbs.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onAdjFullMpAbsChanged(oldval_adjFullMpAbs);
					}
				}
			}

			Int32 oldval_adjHit = adjHit;
			Property prop_adjHit = pdatas[18];
			if(prop_adjHit.isBase())
			{
				if(inited && !inWorld)
					onAdjHitChanged(oldval_adjHit);
			}
			else
			{
				if(inWorld)
				{
					if(prop_adjHit.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onAdjHitChanged(oldval_adjHit);
					}
				}
			}

			float oldval_adjHp = adjHp;
			Property prop_adjHp = pdatas[19];
			if(prop_adjHp.isBase())
			{
				if(inited && !inWorld)
					onAdjHpChanged(oldval_adjHp);
			}
			else
			{
				if(inWorld)
				{
					if(prop_adjHp.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onAdjHpChanged(oldval_adjHp);
					}
				}
			}

			float oldval_adjIgnoreArmor = adjIgnoreArmor;
			Property prop_adjIgnoreArmor = pdatas[91];
			if(prop_adjIgnoreArmor.isBase())
			{
				if(inited && !inWorld)
					onAdjIgnoreArmorChanged(oldval_adjIgnoreArmor);
			}
			else
			{
				if(inWorld)
				{
					if(prop_adjIgnoreArmor.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onAdjIgnoreArmorChanged(oldval_adjIgnoreArmor);
					}
				}
			}

			Int32 oldval_adjKnockAnti = adjKnockAnti;
			Property prop_adjKnockAnti = pdatas[20];
			if(prop_adjKnockAnti.isBase())
			{
				if(inited && !inWorld)
					onAdjKnockAntiChanged(oldval_adjKnockAnti);
			}
			else
			{
				if(inWorld)
				{
					if(prop_adjKnockAnti.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onAdjKnockAntiChanged(oldval_adjKnockAnti);
					}
				}
			}

			Int32 oldval_adjKnockEnh = adjKnockEnh;
			Property prop_adjKnockEnh = pdatas[21];
			if(prop_adjKnockEnh.isBase())
			{
				if(inited && !inWorld)
					onAdjKnockEnhChanged(oldval_adjKnockEnh);
			}
			else
			{
				if(inWorld)
				{
					if(prop_adjKnockEnh.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onAdjKnockEnhChanged(oldval_adjKnockEnh);
					}
				}
			}

			float oldval_adjMortal = adjMortal;
			Property prop_adjMortal = pdatas[22];
			if(prop_adjMortal.isBase())
			{
				if(inited && !inWorld)
					onAdjMortalChanged(oldval_adjMortal);
			}
			else
			{
				if(inWorld)
				{
					if(prop_adjMortal.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onAdjMortalChanged(oldval_adjMortal);
					}
				}
			}

			Int32 oldval_adjSilentAnti = adjSilentAnti;
			Property prop_adjSilentAnti = pdatas[23];
			if(prop_adjSilentAnti.isBase())
			{
				if(inited && !inWorld)
					onAdjSilentAntiChanged(oldval_adjSilentAnti);
			}
			else
			{
				if(inWorld)
				{
					if(prop_adjSilentAnti.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onAdjSilentAntiChanged(oldval_adjSilentAnti);
					}
				}
			}

			Int32 oldval_adjSilentEnh = adjSilentEnh;
			Property prop_adjSilentEnh = pdatas[24];
			if(prop_adjSilentEnh.isBase())
			{
				if(inited && !inWorld)
					onAdjSilentEnhChanged(oldval_adjSilentEnh);
			}
			else
			{
				if(inWorld)
				{
					if(prop_adjSilentEnh.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onAdjSilentEnhChanged(oldval_adjSilentEnh);
					}
				}
			}

			Int32 oldval_adjStunAnti = adjStunAnti;
			Property prop_adjStunAnti = pdatas[25];
			if(prop_adjStunAnti.isBase())
			{
				if(inited && !inWorld)
					onAdjStunAntiChanged(oldval_adjStunAnti);
			}
			else
			{
				if(inWorld)
				{
					if(prop_adjStunAnti.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onAdjStunAntiChanged(oldval_adjStunAnti);
					}
				}
			}

			Int32 oldval_adjStunEnh = adjStunEnh;
			Property prop_adjStunEnh = pdatas[26];
			if(prop_adjStunEnh.isBase())
			{
				if(inited && !inWorld)
					onAdjStunEnhChanged(oldval_adjStunEnh);
			}
			else
			{
				if(inWorld)
				{
					if(prop_adjStunEnh.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onAdjStunEnhChanged(oldval_adjStunEnh);
					}
				}
			}

			float oldval_antiFatal = antiFatal;
			Property prop_antiFatal = pdatas[28];
			if(prop_antiFatal.isBase())
			{
				if(inited && !inWorld)
					onAntiFatalChanged(oldval_antiFatal);
			}
			else
			{
				if(inWorld)
				{
					if(prop_antiFatal.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onAntiFatalChanged(oldval_antiFatal);
					}
				}
			}

			float oldval_antiMortal = antiMortal;
			Property prop_antiMortal = pdatas[29];
			if(prop_antiMortal.isBase())
			{
				if(inited && !inWorld)
					onAntiMortalChanged(oldval_antiMortal);
			}
			else
			{
				if(inWorld)
				{
					if(prop_antiMortal.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onAntiMortalChanged(oldval_antiMortal);
					}
				}
			}

			Int32 oldval_atkBless = atkBless;
			Property prop_atkBless = pdatas[31];
			if(prop_atkBless.isBase())
			{
				if(inited && !inWorld)
					onAtkBlessChanged(oldval_atkBless);
			}
			else
			{
				if(inWorld)
				{
					if(prop_atkBless.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onAtkBlessChanged(oldval_atkBless);
					}
				}
			}

			Int32 oldval_baseDmgArmor = baseDmgArmor;
			Property prop_baseDmgArmor = pdatas[92];
			if(prop_baseDmgArmor.isBase())
			{
				if(inited && !inWorld)
					onBaseDmgArmorChanged(oldval_baseDmgArmor);
			}
			else
			{
				if(inWorld)
				{
					if(prop_baseDmgArmor.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onBaseDmgArmorChanged(oldval_baseDmgArmor);
					}
				}
			}

			float oldval_baseIgnoreArmor = baseIgnoreArmor;
			Property prop_baseIgnoreArmor = pdatas[93];
			if(prop_baseIgnoreArmor.isBase())
			{
				if(inited && !inWorld)
					onBaseIgnoreArmorChanged(oldval_baseIgnoreArmor);
			}
			else
			{
				if(inWorld)
				{
					if(prop_baseIgnoreArmor.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onBaseIgnoreArmorChanged(oldval_baseIgnoreArmor);
					}
				}
			}

			float oldval_bePushedSpeed = bePushedSpeed;
			Property prop_bePushedSpeed = pdatas[33];
			if(prop_bePushedSpeed.isBase())
			{
				if(inited && !inWorld)
					onBePushedSpeedChanged(oldval_bePushedSpeed);
			}
			else
			{
				if(inWorld)
				{
					if(prop_bePushedSpeed.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onBePushedSpeedChanged(oldval_bePushedSpeed);
					}
				}
			}

			float oldval_bloodSuck = bloodSuck;
			Property prop_bloodSuck = pdatas[34];
			if(prop_bloodSuck.isBase())
			{
				if(inited && !inWorld)
					onBloodSuckChanged(oldval_bloodSuck);
			}
			else
			{
				if(inWorld)
				{
					if(prop_bloodSuck.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onBloodSuckChanged(oldval_bloodSuck);
					}
				}
			}

			UInt64 oldval_casterTeamId = casterTeamId;
			Property prop_casterTeamId = pdatas[39];
			if(prop_casterTeamId.isBase())
			{
				if(inited && !inWorld)
					onCasterTeamIdChanged(oldval_casterTeamId);
			}
			else
			{
				if(inWorld)
				{
					if(prop_casterTeamId.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onCasterTeamIdChanged(oldval_casterTeamId);
					}
				}
			}

			Int32 oldval_creationId = creationId;
			Property prop_creationId = pdatas[40];
			if(prop_creationId.isBase())
			{
				if(inited && !inWorld)
					onCreationIdChanged(oldval_creationId);
			}
			else
			{
				if(inWorld)
				{
					if(prop_creationId.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onCreationIdChanged(oldval_creationId);
					}
				}
			}

			Int32 oldval_debilityAnti = debilityAnti;
			Property prop_debilityAnti = pdatas[41];
			if(prop_debilityAnti.isBase())
			{
				if(inited && !inWorld)
					onDebilityAntiChanged(oldval_debilityAnti);
			}
			else
			{
				if(inWorld)
				{
					if(prop_debilityAnti.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onDebilityAntiChanged(oldval_debilityAnti);
					}
				}
			}

			Int32 oldval_debilityEnh = debilityEnh;
			Property prop_debilityEnh = pdatas[42];
			if(prop_debilityEnh.isBase())
			{
				if(inited && !inWorld)
					onDebilityEnhChanged(oldval_debilityEnh);
			}
			else
			{
				if(inWorld)
				{
					if(prop_debilityEnh.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onDebilityEnhChanged(oldval_debilityEnh);
					}
				}
			}

			Vector3 oldval_direction = direction;
			Property prop_direction = pdatas[2];
			if(prop_direction.isBase())
			{
				if(inited && !inWorld)
					onDirectionChanged(oldval_direction);
			}
			else
			{
				if(inWorld)
				{
					if(prop_direction.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onDirectionChanged(oldval_direction);
					}
				}
			}

			Int32 oldval_dmgArmor = dmgArmor;
			Property prop_dmgArmor = pdatas[94];
			if(prop_dmgArmor.isBase())
			{
				if(inited && !inWorld)
					onDmgArmorChanged(oldval_dmgArmor);
			}
			else
			{
				if(inWorld)
				{
					if(prop_dmgArmor.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onDmgArmorChanged(oldval_dmgArmor);
					}
				}
			}

			Int32 oldval_dodge = dodge;
			Property prop_dodge = pdatas[43];
			if(prop_dodge.isBase())
			{
				if(inited && !inWorld)
					onDodgeChanged(oldval_dodge);
			}
			else
			{
				if(inWorld)
				{
					if(prop_dodge.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onDodgeChanged(oldval_dodge);
					}
				}
			}

			Byte oldval_dunTimeFreezeFlag = dunTimeFreezeFlag;
			Property prop_dunTimeFreezeFlag = pdatas[44];
			if(prop_dunTimeFreezeFlag.isBase())
			{
				if(inited && !inWorld)
					onDunTimeFreezeFlagChanged(oldval_dunTimeFreezeFlag);
			}
			else
			{
				if(inWorld)
				{
					if(prop_dunTimeFreezeFlag.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onDunTimeFreezeFlagChanged(oldval_dunTimeFreezeFlag);
					}
				}
			}

			float oldval_extraDmg = extraDmg;
			Property prop_extraDmg = pdatas[95];
			if(prop_extraDmg.isBase())
			{
				if(inited && !inWorld)
					onExtraDmgChanged(oldval_extraDmg);
			}
			else
			{
				if(inWorld)
				{
					if(prop_extraDmg.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onExtraDmgChanged(oldval_extraDmg);
					}
				}
			}

			float oldval_extraDmgDef = extraDmgDef;
			Property prop_extraDmgDef = pdatas[96];
			if(prop_extraDmgDef.isBase())
			{
				if(inited && !inWorld)
					onExtraDmgDefChanged(oldval_extraDmgDef);
			}
			else
			{
				if(inWorld)
				{
					if(prop_extraDmgDef.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onExtraDmgDefChanged(oldval_extraDmgDef);
					}
				}
			}

			float oldval_fatal = fatal;
			Property prop_fatal = pdatas[45];
			if(prop_fatal.isBase())
			{
				if(inited && !inWorld)
					onFatalChanged(oldval_fatal);
			}
			else
			{
				if(inWorld)
				{
					if(prop_fatal.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onFatalChanged(oldval_fatal);
					}
				}
			}

			float oldval_finalDmg = finalDmg;
			Property prop_finalDmg = pdatas[97];
			if(prop_finalDmg.isBase())
			{
				if(inited && !inWorld)
					onFinalDmgChanged(oldval_finalDmg);
			}
			else
			{
				if(inWorld)
				{
					if(prop_finalDmg.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onFinalDmgChanged(oldval_finalDmg);
					}
				}
			}

			float oldval_finalDmgAnti = finalDmgAnti;
			Property prop_finalDmgAnti = pdatas[98];
			if(prop_finalDmgAnti.isBase())
			{
				if(inited && !inWorld)
					onFinalDmgAntiChanged(oldval_finalDmgAnti);
			}
			else
			{
				if(inWorld)
				{
					if(prop_finalDmgAnti.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onFinalDmgAntiChanged(oldval_finalDmgAnti);
					}
				}
			}

			Int32 oldval_force = force;
			Property prop_force = pdatas[46];
			if(prop_force.isBase())
			{
				if(inited && !inWorld)
					onForceChanged(oldval_force);
			}
			else
			{
				if(inWorld)
				{
					if(prop_force.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onForceChanged(oldval_force);
					}
				}
			}

			Int32 oldval_frozenAnti = frozenAnti;
			Property prop_frozenAnti = pdatas[47];
			if(prop_frozenAnti.isBase())
			{
				if(inited && !inWorld)
					onFrozenAntiChanged(oldval_frozenAnti);
			}
			else
			{
				if(inWorld)
				{
					if(prop_frozenAnti.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onFrozenAntiChanged(oldval_frozenAnti);
					}
				}
			}

			Int32 oldval_frozenEnh = frozenEnh;
			Property prop_frozenEnh = pdatas[48];
			if(prop_frozenEnh.isBase())
			{
				if(inited && !inWorld)
					onFrozenEnhChanged(oldval_frozenEnh);
			}
			else
			{
				if(inWorld)
				{
					if(prop_frozenEnh.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onFrozenEnhChanged(oldval_frozenEnh);
					}
				}
			}

			Int32 oldval_fullHp = fullHp;
			Property prop_fullHp = pdatas[49];
			if(prop_fullHp.isBase())
			{
				if(inited && !inWorld)
					onFullHpChanged(oldval_fullHp);
			}
			else
			{
				if(inWorld)
				{
					if(prop_fullHp.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onFullHpChanged(oldval_fullHp);
					}
				}
			}

			Int32 oldval_fullMp = fullMp;
			Property prop_fullMp = pdatas[50];
			if(prop_fullMp.isBase())
			{
				if(inited && !inWorld)
					onFullMpChanged(oldval_fullMp);
			}
			else
			{
				if(inWorld)
				{
					if(prop_fullMp.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onFullMpChanged(oldval_fullMp);
					}
				}
			}

			Int64 oldval_gameEntityId = gameEntityId;
			Property prop_gameEntityId = pdatas[51];
			if(prop_gameEntityId.isBase())
			{
				if(inited && !inWorld)
					onGameEntityIdChanged(oldval_gameEntityId);
			}
			else
			{
				if(inWorld)
				{
					if(prop_gameEntityId.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onGameEntityIdChanged(oldval_gameEntityId);
					}
				}
			}

			Int32 oldval_hit = hit;
			Property prop_hit = pdatas[52];
			if(prop_hit.isBase())
			{
				if(inited && !inWorld)
					onHitChanged(oldval_hit);
			}
			else
			{
				if(inWorld)
				{
					if(prop_hit.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onHitChanged(oldval_hit);
					}
				}
			}

			float oldval_hitRate = hitRate;
			Property prop_hitRate = pdatas[53];
			if(prop_hitRate.isBase())
			{
				if(inited && !inWorld)
					onHitRateChanged(oldval_hitRate);
			}
			else
			{
				if(inWorld)
				{
					if(prop_hitRate.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onHitRateChanged(oldval_hitRate);
					}
				}
			}

			Int32 oldval_hostId = hostId;
			Property prop_hostId = pdatas[54];
			if(prop_hostId.isBase())
			{
				if(inited && !inWorld)
					onHostIdChanged(oldval_hostId);
			}
			else
			{
				if(inWorld)
				{
					if(prop_hostId.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onHostIdChanged(oldval_hostId);
					}
				}
			}

			Byte oldval_hostType = hostType;
			Property prop_hostType = pdatas[55];
			if(prop_hostType.isBase())
			{
				if(inited && !inWorld)
					onHostTypeChanged(oldval_hostType);
			}
			else
			{
				if(inWorld)
				{
					if(prop_hostType.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onHostTypeChanged(oldval_hostType);
					}
				}
			}

			Int32 oldval_hp = hp;
			Property prop_hp = pdatas[56];
			if(prop_hp.isBase())
			{
				if(inited && !inWorld)
					onHpChanged(oldval_hp);
			}
			else
			{
				if(inWorld)
				{
					if(prop_hp.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onHpChanged(oldval_hp);
					}
				}
			}

			float oldval_ignoreArmor = ignoreArmor;
			Property prop_ignoreArmor = pdatas[99];
			if(prop_ignoreArmor.isBase())
			{
				if(inited && !inWorld)
					onIgnoreArmorChanged(oldval_ignoreArmor);
			}
			else
			{
				if(inWorld)
				{
					if(prop_ignoreArmor.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onIgnoreArmorChanged(oldval_ignoreArmor);
					}
				}
			}

			Byte oldval_isWitnessComplete = isWitnessComplete;
			Property prop_isWitnessComplete = pdatas[57];
			if(prop_isWitnessComplete.isBase())
			{
				if(inited && !inWorld)
					onIsWitnessCompleteChanged(oldval_isWitnessComplete);
			}
			else
			{
				if(inWorld)
				{
					if(prop_isWitnessComplete.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onIsWitnessCompleteChanged(oldval_isWitnessComplete);
					}
				}
			}

			Int32 oldval_knockAnti = knockAnti;
			Property prop_knockAnti = pdatas[58];
			if(prop_knockAnti.isBase())
			{
				if(inited && !inWorld)
					onKnockAntiChanged(oldval_knockAnti);
			}
			else
			{
				if(inWorld)
				{
					if(prop_knockAnti.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onKnockAntiChanged(oldval_knockAnti);
					}
				}
			}

			Int32 oldval_knockEnh = knockEnh;
			Property prop_knockEnh = pdatas[59];
			if(prop_knockEnh.isBase())
			{
				if(inited && !inWorld)
					onKnockEnhChanged(oldval_knockEnh);
			}
			else
			{
				if(inWorld)
				{
					if(prop_knockEnh.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onKnockEnhChanged(oldval_knockEnh);
					}
				}
			}

			UInt32 oldval_level = level;
			Property prop_level = pdatas[60];
			if(prop_level.isBase())
			{
				if(inited && !inWorld)
					onLevelChanged(oldval_level);
			}
			else
			{
				if(inWorld)
				{
					if(prop_level.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onLevelChanged(oldval_level);
					}
				}
			}

			Int32 oldval_magicArmor = magicArmor;
			Property prop_magicArmor = pdatas[100];
			if(prop_magicArmor.isBase())
			{
				if(inited && !inWorld)
					onMagicArmorChanged(oldval_magicArmor);
			}
			else
			{
				if(inWorld)
				{
					if(prop_magicArmor.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onMagicArmorChanged(oldval_magicArmor);
					}
				}
			}

			Int32 oldval_maxMagicAtk = maxMagicAtk;
			Property prop_maxMagicAtk = pdatas[62];
			if(prop_maxMagicAtk.isBase())
			{
				if(inited && !inWorld)
					onMaxMagicAtkChanged(oldval_maxMagicAtk);
			}
			else
			{
				if(inWorld)
				{
					if(prop_maxMagicAtk.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onMaxMagicAtkChanged(oldval_maxMagicAtk);
					}
				}
			}

			Int32 oldval_maxPhysicalAtk = maxPhysicalAtk;
			Property prop_maxPhysicalAtk = pdatas[64];
			if(prop_maxPhysicalAtk.isBase())
			{
				if(inited && !inWorld)
					onMaxPhysicalAtkChanged(oldval_maxPhysicalAtk);
			}
			else
			{
				if(inWorld)
				{
					if(prop_maxPhysicalAtk.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onMaxPhysicalAtkChanged(oldval_maxPhysicalAtk);
					}
				}
			}

			Int32 oldval_minMagicAtk = minMagicAtk;
			Property prop_minMagicAtk = pdatas[66];
			if(prop_minMagicAtk.isBase())
			{
				if(inited && !inWorld)
					onMinMagicAtkChanged(oldval_minMagicAtk);
			}
			else
			{
				if(inWorld)
				{
					if(prop_minMagicAtk.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onMinMagicAtkChanged(oldval_minMagicAtk);
					}
				}
			}

			Int32 oldval_minPhysicalAtk = minPhysicalAtk;
			Property prop_minPhysicalAtk = pdatas[68];
			if(prop_minPhysicalAtk.isBase())
			{
				if(inited && !inWorld)
					onMinPhysicalAtkChanged(oldval_minPhysicalAtk);
			}
			else
			{
				if(inWorld)
				{
					if(prop_minPhysicalAtk.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onMinPhysicalAtkChanged(oldval_minPhysicalAtk);
					}
				}
			}

			float oldval_monsterDmg = monsterDmg;
			Property prop_monsterDmg = pdatas[101];
			if(prop_monsterDmg.isBase())
			{
				if(inited && !inWorld)
					onMonsterDmgChanged(oldval_monsterDmg);
			}
			else
			{
				if(inWorld)
				{
					if(prop_monsterDmg.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onMonsterDmgChanged(oldval_monsterDmg);
					}
				}
			}

			float oldval_monsterDmgAnti = monsterDmgAnti;
			Property prop_monsterDmgAnti = pdatas[102];
			if(prop_monsterDmgAnti.isBase())
			{
				if(inited && !inWorld)
					onMonsterDmgAntiChanged(oldval_monsterDmgAnti);
			}
			else
			{
				if(inWorld)
				{
					if(prop_monsterDmgAnti.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onMonsterDmgAntiChanged(oldval_monsterDmgAnti);
					}
				}
			}

			float oldval_mortal = mortal;
			Property prop_mortal = pdatas[69];
			if(prop_mortal.isBase())
			{
				if(inited && !inWorld)
					onMortalChanged(oldval_mortal);
			}
			else
			{
				if(inWorld)
				{
					if(prop_mortal.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onMortalChanged(oldval_mortal);
					}
				}
			}

			float oldval_mpCostRatio = mpCostRatio;
			Property prop_mpCostRatio = pdatas[70];
			if(prop_mpCostRatio.isBase())
			{
				if(inited && !inWorld)
					onMpCostRatioChanged(oldval_mpCostRatio);
			}
			else
			{
				if(inWorld)
				{
					if(prop_mpCostRatio.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onMpCostRatioChanged(oldval_mpCostRatio);
					}
				}
			}

			float oldval_mulBloodSuck = mulBloodSuck;
			Property prop_mulBloodSuck = pdatas[71];
			if(prop_mulBloodSuck.isBase())
			{
				if(inited && !inWorld)
					onMulBloodSuckChanged(oldval_mulBloodSuck);
			}
			else
			{
				if(inWorld)
				{
					if(prop_mulBloodSuck.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onMulBloodSuckChanged(oldval_mulBloodSuck);
					}
				}
			}

			float oldval_mulBossDmg = mulBossDmg;
			Property prop_mulBossDmg = pdatas[72];
			if(prop_mulBossDmg.isBase())
			{
				if(inited && !inWorld)
					onMulBossDmgChanged(oldval_mulBossDmg);
			}
			else
			{
				if(inWorld)
				{
					if(prop_mulBossDmg.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onMulBossDmgChanged(oldval_mulBossDmg);
					}
				}
			}

			float oldval_mulCD = mulCD;
			Property prop_mulCD = pdatas[73];
			if(prop_mulCD.isBase())
			{
				if(inited && !inWorld)
					onMulCDChanged(oldval_mulCD);
			}
			else
			{
				if(inWorld)
				{
					if(prop_mulCD.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onMulCDChanged(oldval_mulCD);
					}
				}
			}

			float oldval_mulFullHp = mulFullHp;
			Property prop_mulFullHp = pdatas[74];
			if(prop_mulFullHp.isBase())
			{
				if(inited && !inWorld)
					onMulFullHpChanged(oldval_mulFullHp);
			}
			else
			{
				if(inWorld)
				{
					if(prop_mulFullHp.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onMulFullHpChanged(oldval_mulFullHp);
					}
				}
			}

			float oldval_mulFullMp = mulFullMp;
			Property prop_mulFullMp = pdatas[75];
			if(prop_mulFullMp.isBase())
			{
				if(inited && !inWorld)
					onMulFullMpChanged(oldval_mulFullMp);
			}
			else
			{
				if(inWorld)
				{
					if(prop_mulFullMp.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onMulFullMpChanged(oldval_mulFullMp);
					}
				}
			}

			float oldval_mulHp = mulHp;
			Property prop_mulHp = pdatas[76];
			if(prop_mulHp.isBase())
			{
				if(inited && !inWorld)
					onMulHpChanged(oldval_mulHp);
			}
			else
			{
				if(inWorld)
				{
					if(prop_mulHp.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onMulHpChanged(oldval_mulHp);
					}
				}
			}

			string oldval_name = name;
			Property prop_name = pdatas[77];
			if(prop_name.isBase())
			{
				if(inited && !inWorld)
					onNameChanged(oldval_name);
			}
			else
			{
				if(inWorld)
				{
					if(prop_name.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onNameChanged(oldval_name);
					}
				}
			}

			Int32 oldval_physicalArmor = physicalArmor;
			Property prop_physicalArmor = pdatas[103];
			if(prop_physicalArmor.isBase())
			{
				if(inited && !inWorld)
					onPhysicalArmorChanged(oldval_physicalArmor);
			}
			else
			{
				if(inWorld)
				{
					if(prop_physicalArmor.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onPhysicalArmorChanged(oldval_physicalArmor);
					}
				}
			}

			Vector3 oldval_position = position;
			Property prop_position = pdatas[1];
			if(prop_position.isBase())
			{
				if(inited && !inWorld)
					onPositionChanged(oldval_position);
			}
			else
			{
				if(inWorld)
				{
					if(prop_position.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onPositionChanged(oldval_position);
					}
				}
			}

			Int32 oldval_realDmg = realDmg;
			Property prop_realDmg = pdatas[104];
			if(prop_realDmg.isBase())
			{
				if(inited && !inWorld)
					onRealDmgChanged(oldval_realDmg);
			}
			else
			{
				if(inWorld)
				{
					if(prop_realDmg.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onRealDmgChanged(oldval_realDmg);
					}
				}
			}

			Int32 oldval_realDmgDef = realDmgDef;
			Property prop_realDmgDef = pdatas[105];
			if(prop_realDmgDef.isBase())
			{
				if(inited && !inWorld)
					onRealDmgDefChanged(oldval_realDmgDef);
			}
			else
			{
				if(inWorld)
				{
					if(prop_realDmgDef.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onRealDmgDefChanged(oldval_realDmgDef);
					}
				}
			}

			Int32 oldval_selectedTargetId = selectedTargetId;
			Property prop_selectedTargetId = pdatas[78];
			if(prop_selectedTargetId.isBase())
			{
				if(inited && !inWorld)
					onSelectedTargetIdChanged(oldval_selectedTargetId);
			}
			else
			{
				if(inWorld)
				{
					if(prop_selectedTargetId.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onSelectedTargetIdChanged(oldval_selectedTargetId);
					}
				}
			}

			Int32 oldval_silentAnti = silentAnti;
			Property prop_silentAnti = pdatas[79];
			if(prop_silentAnti.isBase())
			{
				if(inited && !inWorld)
					onSilentAntiChanged(oldval_silentAnti);
			}
			else
			{
				if(inWorld)
				{
					if(prop_silentAnti.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onSilentAntiChanged(oldval_silentAnti);
					}
				}
			}

			Int32 oldval_silentEnh = silentEnh;
			Property prop_silentEnh = pdatas[80];
			if(prop_silentEnh.isBase())
			{
				if(inited && !inWorld)
					onSilentEnhChanged(oldval_silentEnh);
			}
			else
			{
				if(inWorld)
				{
					if(prop_silentEnh.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onSilentEnhChanged(oldval_silentEnh);
					}
				}
			}

			float oldval_skillCD = skillCD;
			Property prop_skillCD = pdatas[106];
			if(prop_skillCD.isBase())
			{
				if(inited && !inWorld)
					onSkillCDChanged(oldval_skillCD);
			}
			else
			{
				if(inWorld)
				{
					if(prop_skillCD.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onSkillCDChanged(oldval_skillCD);
					}
				}
			}

			Int32 oldval_slowAnti = slowAnti;
			Property prop_slowAnti = pdatas[107];
			if(prop_slowAnti.isBase())
			{
				if(inited && !inWorld)
					onSlowAntiChanged(oldval_slowAnti);
			}
			else
			{
				if(inWorld)
				{
					if(prop_slowAnti.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onSlowAntiChanged(oldval_slowAnti);
					}
				}
			}

			Int32 oldval_slowEnh = slowEnh;
			Property prop_slowEnh = pdatas[108];
			if(prop_slowEnh.isBase())
			{
				if(inited && !inWorld)
					onSlowEnhChanged(oldval_slowEnh);
			}
			else
			{
				if(inWorld)
				{
					if(prop_slowEnh.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onSlowEnhChanged(oldval_slowEnh);
					}
				}
			}

			UInt32 oldval_spaceNo = spaceNo;
			Property prop_spaceNo = pdatas[81];
			if(prop_spaceNo.isBase())
			{
				if(inited && !inWorld)
					onSpaceNoChanged(oldval_spaceNo);
			}
			else
			{
				if(inWorld)
				{
					if(prop_spaceNo.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onSpaceNoChanged(oldval_spaceNo);
					}
				}
			}

			float oldval_speed = speed;
			Property prop_speed = pdatas[82];
			if(prop_speed.isBase())
			{
				if(inited && !inWorld)
					onSpeedChanged(oldval_speed);
			}
			else
			{
				if(inWorld)
				{
					if(prop_speed.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onSpeedChanged(oldval_speed);
					}
				}
			}

			Int32 oldval_spirit = spirit;
			Property prop_spirit = pdatas[109];
			if(prop_spirit.isBase())
			{
				if(inited && !inWorld)
					onSpiritChanged(oldval_spirit);
			}
			else
			{
				if(inWorld)
				{
					if(prop_spirit.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onSpiritChanged(oldval_spirit);
					}
				}
			}

			Int64 oldval_state = state;
			Property prop_state = pdatas[83];
			if(prop_state.isBase())
			{
				if(inited && !inWorld)
					onStateChanged(oldval_state);
			}
			else
			{
				if(inWorld)
				{
					if(prop_state.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onStateChanged(oldval_state);
					}
				}
			}

			Int64 oldval_state2 = state2;
			Property prop_state2 = pdatas[84];
			if(prop_state2.isBase())
			{
				if(inited && !inWorld)
					onState2Changed(oldval_state2);
			}
			else
			{
				if(inWorld)
				{
					if(prop_state2.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onState2Changed(oldval_state2);
					}
				}
			}

			Int32 oldval_stunAnti = stunAnti;
			Property prop_stunAnti = pdatas[85];
			if(prop_stunAnti.isBase())
			{
				if(inited && !inWorld)
					onStunAntiChanged(oldval_stunAnti);
			}
			else
			{
				if(inWorld)
				{
					if(prop_stunAnti.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onStunAntiChanged(oldval_stunAnti);
					}
				}
			}

			Int32 oldval_stunEnh = stunEnh;
			Property prop_stunEnh = pdatas[86];
			if(prop_stunEnh.isBase())
			{
				if(inited && !inWorld)
					onStunEnhChanged(oldval_stunEnh);
			}
			else
			{
				if(inWorld)
				{
					if(prop_stunEnh.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onStunEnhChanged(oldval_stunEnh);
					}
				}
			}

			string oldval_type = type;
			Property prop_type = pdatas[87];
			if(prop_type.isBase())
			{
				if(inited && !inWorld)
					onTypeChanged(oldval_type);
			}
			else
			{
				if(inWorld)
				{
					if(prop_type.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onTypeChanged(oldval_type);
					}
				}
			}

		}
	}
}