# coding: utf-8
# This file is auto-generated by tlogdef generate tool
# WARNING: Do not edit this file, your changes will get lost.
# ToolVersion: v1.0.3
# XMLdef
#   - tagsetversion: 1
#   - name: Log
#   - version: 2
from KBEDebug import *
import KBEngine

import time

import gameconfig
import gameconst


class StructBasic(object):

    @property
    def tlogname(self):
        return self.__class__.__name__

    def gen_tlogstr(self):
        _data = [self.tlogname, ]
        _data.extend([str(getattr(self, i)) for i in self.__slots__])
        return '|'.join(_data)

    def init(self):
        if hasattr(self, 'GameSvrId') and self.GameSvrId is None:
            setattr(self, 'GameSvrId', gameconfig.serverId())
        if hasattr(self, 'dtEventTime') and self.dtEventTime is None:
            setattr(self, 'dtEventTime', time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(time.time())))
        if hasattr(self, 'vGameAppid') and self.vGameAppid is None:
            setattr(self, 'vGameAppid', gameconst.XZJ_APP_ID)
        return self

    def commit(self):
        if not gameconfig.tlogFlag():
            return
        _msg = self.gen_tlogstr()
        INFO_MSG("tlog", _msg)


def build(logname, *args, **kwargs):
    tlogCls = structs_map[logname]
    return tlogCls(*args, **kwargs)


# -------------------------------------------------------------------
# MACROSGROUPS
class PlatID(object):
    """MACROSGROUP::PlatID: 不要随意修改，否则影响统计结果"""

    IOS = 0  # ios
    ANDROID = 1  # android


class vGender(object):
    """MACROSGROUP::vGender: 玩家角色性别"""

    MALE = 1  # 男
    FEMALE = 2  # 女


class ADDORREDUCE(object):
    """MACROSGROUP::ADDORREDUCE: """

    ADD = 0  # 加
    REDUCE = 1  # 减


class PlayerMailOpType(object):
    """MACROSGROUP::PlayerMailOpType: playerMial类型"""

    ReceiveMail = 0  # 收到邮件
    AttachReward = 1  # 领取邮件附件奖励
    DeleteMail = 2  # 领取邮件附件奖励


class OnlineState(object):
    """MACROSGROUP::OnlineState: 玩家在线状态"""

    Offline = 0  # 离线
    Online = 1  # 在线


class ReliveType(object):
    """MACROSGROUP::ReliveType: 玩家复活方式"""

    Directly = 1  # 原地复活
    Near = 2  # 就近复活


class RESULT(object):
    """MACROSGROUP::RESULT: 单局结果，不要随意修改，否则影响统计结果"""

    SUCCESS = 1  # 成功
    FAIL = 0  # 失败


class BATTLETYPE(object):
    """MACROSGROUP::BATTLETYPE: 玩法类型，根据游戏情况自定义"""

    ShanHaiFuShen = 0  # 山海历境


class SingleOrteam(object):
    """MACROSGROUP::SingleOrteam: 进入方式"""

    SINGLE = 1  # 单人
    TEAM = 2  # 组队
    RAID = 3  # 团队


class iTASKTYPE(object):
    """MACROSGROUP::iTASKTYPE: 根据游戏情况自定义"""

    TYPE_1 = 1  # 主线任务
    TYPE_2 = 2  # 支线任务
    TYPE_3 = 3  # 其他


class iSTATE(object):
    """MACROSGROUP::iSTATE: 根据游戏情况自定义"""

    CLAIM = 1  # 接取
    SUBMIT = 2  # 完成
    TARGET_REACH = 3  # 目标达成
    TARGET_FAILED = 4  # 目标失败
    QUIT = 5  # 放弃


class ResultFlag(object):
    """MACROSGROUP::ResultFlag: 检测结果"""

    normal = 0  # 合法
    evil = 1  # 非法
    dirty = 2  # 合法有敏感词


class AddOrReduceOrReset(object):
    """MACROSGROUP::AddOrReduceOrReset: 加/减/重置"""

    ADD = 0  # 加
    REDUCE = 1  # 减
    RESET = 2  # 重置


# -------------------------------------------------------------------


# -------------------------------------------------------------------
# STRUCTS
class GameSvrState(StructBasic):
    """STRUCT::GameSvrState: (必填)服务器状态流水，每5分钟一条日志"""

    __slots__ = ("GameSvrId", "dtEventTime", "vGameAppid", "vGameIP", "iZoneAreaID")

    def __init__(self, GameSvrId, dtEventTime, vGameAppid, vGameIP, iZoneAreaID):
        self.GameSvrId = GameSvrId  # (必填)登录服务ID，分区服场景使用，合服后上报合服后服务器ID。
        self.dtEventTime = dtEventTime  # (必填) 格式 YYYY-MM-DD HH:MM:SS
        self.vGameAppid = vGameAppid  # (必填)游戏APPID
        self.vGameIP = vGameIP  # (必填)服务器IP
        self.iZoneAreaID = iZoneAreaID  # (必填)针对分区分服的游戏填写分区id，用来唯一标示一个区；非分区分服游戏请填写0


class GameOpenFlow(StructBasic):
    """STRUCT::GameOpenFlow: (必填)开服流水表，每天一条"""

    __slots__ = ("GameSvrId", "dtEventTime", "vGameAppid", "iZoneAreaID", "GameOpenDay")

    def __init__(self, GameSvrId, dtEventTime, vGameAppid, iZoneAreaID, GameOpenDay):
        self.GameSvrId = GameSvrId  # (必填)登录服务ID，分区服场景使用，合服后上报合服后服务器ID。
        self.dtEventTime = dtEventTime  # (必填) 格式 YYYY-MM-DD HH:MM:SS
        self.vGameAppid = vGameAppid  # (必填)游戏APPID
        self.iZoneAreaID = iZoneAreaID  # (必填)针对分区分服的游戏填写分区id，用来唯一标示一个区；非分区分服游戏请填写0
        self.GameOpenDay = GameOpenDay  # (必填)开服天数


class OnlineCnt(StructBasic):
    """STRUCT::OnlineCnt: (必填)实时在线日志，每分钟一条"""

    __slots__ = ("GameSvrId", "dtEventTime", "vGameAppid", "TimeKey", "Country", "gsid", "iZoneAreaID", "OnlineCntIOS",
                 "OnlineCntAndroid", "RegisterCnt")

    def __init__(self, GameSvrId, dtEventTime, vGameAppid, TimeKey, Country, gsid, iZoneAreaID, OnlineCntIOS,
                 OnlineCntAndroid, RegisterCnt):
        self.GameSvrId = GameSvrId  # (必填)登录服务ID，分区服场景使用，合服后上报合服后服务器ID。
        self.dtEventTime = dtEventTime  # (必填) 格式 YYYY-MM-DD HH:MM:SS
        self.vGameAppid = vGameAppid  # (必填)游戏APPID
        self.TimeKey = TimeKey  # (必填)当前时间的时间戳，即当前的unixtime
        self.Country = Country  # (必填)国家名称，使用中文
        self.gsid = gsid  # (必填)游戏服务器编号
        self.iZoneAreaID = iZoneAreaID  # (必填)针对分区分服的游戏填写分区id，用来唯一标示一个区；非分区分服游戏请填写0
        self.OnlineCntIOS = OnlineCntIOS  # (必填)ios在线人数
        self.OnlineCntAndroid = OnlineCntAndroid  # (必填)android在线人数
        self.RegisterCnt = RegisterCnt  # (必填)注册人数


class PlayerRegister(StructBasic):
    """STRUCT::PlayerRegister: (必填)玩家创建角色"""

    __slots__ = ("GameSvrId", "dtEventTime", "vGameAppid", "PlatID", "iZoneAreaID", "vOpenID", "vRoleID", "vRoleName",
                 "ClientVersion", "SystemSoftware", "SystemHardware", "TelecomOper", "Network", "ScreenWidth",
                 "ScreenHight", "Density", "RegChannel", "CpuHardware", "Memory", "GLRender", "GLVersion", "DeviceId",
                 "vClientIP", "vClientIPV6", "vGender", "iProfessionID", "CharacterNum", "OAID", "CAID", "UA")

    def __init__(self, GameSvrId, dtEventTime, vGameAppid, PlatID, iZoneAreaID, vOpenID, vRoleID, vRoleName,
                 ClientVersion, SystemSoftware, SystemHardware, TelecomOper, Network, ScreenWidth, ScreenHight, Density,
                 RegChannel, CpuHardware, Memory, GLRender, GLVersion, DeviceId, vClientIP, vClientIPV6, vGender,
                 iProfessionID, CharacterNum, OAID, CAID, UA):
        self.GameSvrId = GameSvrId  # (必填)登录服务ID，分区服场景使用，合服后上报合服后服务器ID。
        self.dtEventTime = dtEventTime  # (必填)游戏事件的时间, 格式 YYYY-MM-DD HH:MM:SS
        self.vGameAppid = vGameAppid  # (必填)游戏APPID
        self.PlatID = PlatID  # (必填)ios 0 /android 1
        self.iZoneAreaID = iZoneAreaID  # (必填)注册服ID，分区服场景使用。其他场景时填写0
        self.vOpenID = vOpenID  # (必填)用户OPENID号
        self.vRoleID = vRoleID  # (必填)玩家角色ID
        self.vRoleName = vRoleName  # (必填)玩家角色名
        self.ClientVersion = ClientVersion  # (可填)客户端版本
        self.SystemSoftware = SystemSoftware  # (可填)移动终端操作系统版本
        self.SystemHardware = SystemHardware  # (可填)移动终端机型
        self.TelecomOper = TelecomOper  # (必填)运营商
        self.Network = Network  # (可填)3G/WIFI/2G
        self.ScreenWidth = ScreenWidth  # (可填)显示屏宽度
        self.ScreenHight = ScreenHight  # (可填)显示屏高度
        self.Density = Density  # (可填)像素密度
        self.RegChannel = RegChannel  # (必填)注册渠道
        self.CpuHardware = CpuHardware  # (可填)cpu类型|频率|核数
        self.Memory = Memory  # (可填)内存信息单位M
        self.GLRender = GLRender  # (可填)opengl render信息
        self.GLVersion = GLVersion  # (可填)opengl版本信息
        self.DeviceId = DeviceId  # (必选)设备ID,安卓上报IMEI,IOS上报IDFA(报原始信息,不要加密)
        self.vClientIP = vClientIP  # (必填)客户端IP(后台服务器记录与玩家通信时的IP地址)
        self.vClientIPV6 = vClientIPV6  # (必填)客户端IPV6地址(若客户端使用IPV6通信则记录)
        self.vGender = vGender  # (可填)玩家角色性别
        self.iProfessionID = iProfessionID  # (可填)职业ID
        self.CharacterNum = CharacterNum  # (必填)玩家角色数量
        self.OAID = OAID  # 玩家OAID
        self.CAID = CAID  # 玩家CAID
        self.UA = UA  # 玩家UA


class PlayerLogin(StructBasic):
    """STRUCT::PlayerLogin: (必填)玩家登陆"""

    __slots__ = (
        "GameSvrId", "dtEventTime", "vGameAppid", "PlatID", "iZoneAreaID", "vOpenID", "vRoleID", "vRoleName", "iLevel",
        "iVipLevel", "iRoleCE", "PlayerFriendsNum", "ClientVersion", "SystemSoftware", "SystemHardware", "TelecomOper",
        "Network", "ScreenWidth", "ScreenHight", "Density", "LoginChannel", "vHeaderID", "CpuHardware", "Memory",
        "GLRender", "GLVersion", "DeviceId", "vClientIP", "vClientIPV6", "vGender", "iProfessionID", "roleCEDetails",
        "OAID", "CAID", "UA", "PlatformUserTag")

    def __init__(self, GameSvrId, dtEventTime, vGameAppid, PlatID, iZoneAreaID, vOpenID, vRoleID, vRoleName, iLevel,
                 iVipLevel, iRoleCE, PlayerFriendsNum, ClientVersion, SystemSoftware, SystemHardware, TelecomOper,
                 Network, ScreenWidth, ScreenHight, Density, LoginChannel, vHeaderID, CpuHardware, Memory, GLRender,
                 GLVersion, DeviceId, vClientIP, vClientIPV6, vGender, iProfessionID, roleCEDetails, OAID, CAID, UA,
                 PlatformUserTag):
        self.GameSvrId = GameSvrId  # (必填)登录服务ID，分区服场景使用，合服后上报合服后服务器ID。
        self.dtEventTime = dtEventTime  # (必填)游戏事件的时间, 格式 YYYY-MM-DD HH:MM:SS
        self.vGameAppid = vGameAppid  # (必填)游戏APPID
        self.PlatID = PlatID  # (必填)ios 0/android 1
        self.iZoneAreaID = iZoneAreaID  # (必填)注册服ID，分区服场景使用。其他场景时填写0
        self.vOpenID = vOpenID  # (必填)用户OPENID号
        self.vRoleID = vRoleID  # (必填)玩家角色ID
        self.vRoleName = vRoleName  # (必填)玩家角色名
        self.iLevel = iLevel  # (必填)等级
        self.iVipLevel = iVipLevel  # (可填)VIP等级
        self.iRoleCE = iRoleCE  # (可填)玩家角色战力Combat Effectiveness
        self.PlayerFriendsNum = PlayerFriendsNum  # (必填)玩家好友数量
        self.ClientVersion = ClientVersion  # (必填)客户端版本
        self.SystemSoftware = SystemSoftware  # (可填)移动终端操作系统版本
        self.SystemHardware = SystemHardware  # (必填)移动终端机型
        self.TelecomOper = TelecomOper  # (必填)运营商
        self.Network = Network  # (必填)3G/WIFI/2G
        self.ScreenWidth = ScreenWidth  # (可填)显示屏宽度
        self.ScreenHight = ScreenHight  # (可填)显示屏高度
        self.Density = Density  # (可填)像素密度
        self.LoginChannel = LoginChannel  # (必填)登录渠道
        self.vHeaderID = vHeaderID  # (必填)玩家角色头像ID
        self.CpuHardware = CpuHardware  # (可填)cpu类型-频率-核数
        self.Memory = Memory  # (可填)内存信息单位M
        self.GLRender = GLRender  # (可填)opengl render信息
        self.GLVersion = GLVersion  # (可填)opengl版本信息
        self.DeviceId = DeviceId  # (必选)设备ID,安卓上报IMEI,IOS上报IDFA(报原始信息,不要加密)
        self.vClientIP = vClientIP  # (必填)客户端IP(后台服务器记录与玩家通信时的IP地址)
        self.vClientIPV6 = vClientIPV6  # (必填)客户端IPV6地址(若客户端使用IPV6通信则记录)
        self.vGender = vGender  # (可填)玩家角色性别
        self.iProfessionID = iProfessionID  # (可填)职业ID
        self.roleCEDetails = roleCEDetails  # (必填)战力分布
        self.OAID = OAID  # 玩家OAID
        self.CAID = CAID  # 玩家CAID
        self.UA = UA  # 玩家UA
        self.PlatformUserTag = PlatformUserTag  # 玩家授权状态


class PlayerTimingOnline(StructBasic):
    """STRUCT::PlayerTimingOnline: (必填)玩家定时在线"""

    __slots__ = (
        "GameSvrId", "dtEventTime", "vGameAppid", "PlatID", "iZoneAreaID", "vOpenID", "vRoleID", "vRoleName", "iLevel",
        "vGender", "iProfessionID", "iBalance_MoneyType0", "iBalance_MoneyType1", "iBalance_MoneyType2",
        "iBalance_MoneyType3", "iBalance_MoneyType4", "roleCEDetails")

    def __init__(self, GameSvrId, dtEventTime, vGameAppid, PlatID, iZoneAreaID, vOpenID, vRoleID, vRoleName, iLevel,
                 vGender, iProfessionID, iBalance_MoneyType0, iBalance_MoneyType1, iBalance_MoneyType2,
                 iBalance_MoneyType3, iBalance_MoneyType4, roleCEDetails):
        self.GameSvrId = GameSvrId  # (必填)登录服务ID，分区服场景使用，合服后上报合服后服务器ID。
        self.dtEventTime = dtEventTime  # (必填)游戏事件的时间, 格式 YYYY-MM-DD HH:MM:SS
        self.vGameAppid = vGameAppid  # (必填)游戏APPID
        self.PlatID = PlatID  # (必填)ios 0/android 1
        self.iZoneAreaID = iZoneAreaID  # (必填)注册服ID，分区服场景使用。其他场景时填写0
        self.vOpenID = vOpenID  # (必填)用户OPENID号
        self.vRoleID = vRoleID  # (必填)玩家角色ID
        self.vRoleName = vRoleName  # (必填)玩家角色名
        self.iLevel = iLevel  # (必填)等级
        self.vGender = vGender  # (必填)玩家角色性别
        self.iProfessionID = iProfessionID  # (必填)职业ID
        self.iBalance_MoneyType0 = iBalance_MoneyType0  # (必填)货币余额，货币类型值0
        self.iBalance_MoneyType1 = iBalance_MoneyType1  # (必填)货币余额，货币类型值1
        self.iBalance_MoneyType2 = iBalance_MoneyType2  # (必填)货币余额，货币类型值2
        self.iBalance_MoneyType3 = iBalance_MoneyType3  # (必填)货币余额，货币类型值3
        self.iBalance_MoneyType4 = iBalance_MoneyType4  # (必填)货币余额，货币类型值4
        self.roleCEDetails = roleCEDetails  # (必填)战力分布


class PlayerLogout(StructBasic):
    """STRUCT::PlayerLogout: (必填)玩家登出"""

    __slots__ = (
        "GameSvrId", "dtEventTime", "vGameAppid", "PlatID", "iZoneAreaID", "vOpenID", "vRoleID", "vRoleName", "iLevel",
        "iVipLevel", "iRoleCE", "OnlineTime", "PlayerFriendsNum", "ClientVersion", "SystemSoftware", "SystemHardware",
        "TelecomOper", "Network", "ScreenWidth", "ScreenHight", "Density", "LoginChannel", "vHeaderID", "CpuHardware",
        "Memory", "GLRender", "GLVersion", "DeviceId", "vClientIP", "vClientIPV6", "dailyMaxRoleCE",
        "dailyMaxFenxinPoint",
        "roleCEDetails", "iProfessionID", "PlatformUserTag")

    def __init__(self, GameSvrId, dtEventTime, vGameAppid, PlatID, iZoneAreaID, vOpenID, vRoleID, vRoleName, iLevel,
                 iVipLevel, iRoleCE, OnlineTime, PlayerFriendsNum, ClientVersion, SystemSoftware, SystemHardware,
                 TelecomOper, Network, ScreenWidth, ScreenHight, Density, LoginChannel, vHeaderID, CpuHardware, Memory,
                 GLRender, GLVersion, DeviceId, vClientIP, vClientIPV6, dailyMaxRoleCE, roleCEDetails, iProfessionID,
                 PlatformUserTag):
        self.GameSvrId = GameSvrId  # (必填)登录服务ID，分区服场景使用，合服后上报合服后服务器ID。
        self.dtEventTime = dtEventTime  # (必填)游戏事件的时间, 格式 YYYY-MM-DD HH:MM:SS
        self.vGameAppid = vGameAppid  # (必填)游戏APPID
        self.PlatID = PlatID  # (必填)ios 0/android 1
        self.iZoneAreaID = iZoneAreaID  # (必填)注册服ID，分区服场景使用。其他场景时填写0
        self.vOpenID = vOpenID  # (必填)用户OPENID号
        self.vRoleID = vRoleID  # (必填)玩家角色ID
        self.vRoleName = vRoleName  # (必填)玩家角色名
        self.iLevel = iLevel  # (必填)等级
        self.iVipLevel = iVipLevel  # (可填)VIP等级
        self.iRoleCE = iRoleCE  # (可填)玩家角色战力Combat Effectiveness
        self.OnlineTime = OnlineTime  # (必填)本次登录在线时间(秒)
        self.PlayerFriendsNum = PlayerFriendsNum  # (必填)玩家好友数量
        self.ClientVersion = ClientVersion  # (必填)客户端版本
        self.SystemSoftware = SystemSoftware  # (可填)移动终端操作系统版本
        self.SystemHardware = SystemHardware  # (必填)移动终端机型
        self.TelecomOper = TelecomOper  # (必填)运营商
        self.Network = Network  # (必填)3G/WIFI/2G
        self.ScreenWidth = ScreenWidth  # (可填)显示屏宽度
        self.ScreenHight = ScreenHight  # (可填)显示高度
        self.Density = Density  # (可填)像素密度
        self.LoginChannel = LoginChannel  # (可填)登录渠道
        self.vHeaderID = vHeaderID  # (必填)玩家角色头像ID
        self.CpuHardware = CpuHardware  # (可填)cpu类型;频率;核数
        self.Memory = Memory  # (可填)内存信息单位M
        self.GLRender = GLRender  # (可填)opengl render信息
        self.GLVersion = GLVersion  # (可填)opengl版本信息
        self.DeviceId = DeviceId  # (必选)设备ID,安卓上报IMEI,IOS上报IDFA(报原始信息,不要加密)
        self.vClientIP = vClientIP  # (必填)客户端IP(后台服务器记录与玩家通信时的IP地址)
        self.vClientIPV6 = vClientIPV6  # (必填)客户端IPV6地址(若客户端使用IPV6通信则记录)
        self.roleCEDetails = roleCEDetails  # (必填)战力分布
        self.iProfessionID = iProfessionID  # (可填)职业ID
        self.PlatformUserTag = PlatformUserTag  # 玩家授权状态


class MoneyFlow(StructBasic):
    """STRUCT::MoneyFlow: (必填)货币流水"""

    __slots__ = (
        "GameSvrId", "dtEventTime", "vGameAppid", "PlatID", "iZoneAreaID", "vOpenID", "vRoleID", "vRoleName", "iLevel",
        "iVipLevel", "iRoleCE", "Sequence", "AfterMoney", "iMoney", "Reason", "SubReason", "Detail", "IDIPSource",
        "AddOrReduce", "iMoneyType")

    def __init__(self, GameSvrId, dtEventTime, vGameAppid, PlatID, iZoneAreaID, vOpenID, vRoleID, vRoleName, iLevel,
                 iVipLevel, iRoleCE, Sequence, AfterMoney, iMoney, Reason, SubReason, Detail, IDIPSource, AddOrReduce,
                 iMoneyType):
        self.GameSvrId = GameSvrId  # (必填)登录服务ID，分区服场景使用，合服后上报合服后服务器ID。
        self.dtEventTime = dtEventTime  # (必填)游戏事件的时间, 格式 YYYY-MM-DD HH:MM:SS
        self.vGameAppid = vGameAppid  # (必填)游戏APPID
        self.PlatID = PlatID  # (必填)ios 0/android 1
        self.iZoneAreaID = iZoneAreaID  # (必填)注册服ID，分区服场景使用。其他场景时填写0
        self.vOpenID = vOpenID  # (必填)用户OPENID号
        self.vRoleID = vRoleID  # (必填)玩家角色ID
        self.vRoleName = vRoleName  # (必填)玩家角色名
        self.iLevel = iLevel  # (必填)等级
        self.iVipLevel = iVipLevel  # (可填)VIP等级
        self.iRoleCE = iRoleCE  # (可填)玩家角色战力Combat Effectiveness
        self.Sequence = Sequence  # (可填)用于关联一次动作产生多条不同类型的货币流动日志
        self.AfterMoney = AfterMoney  # (可填)动作后的金钱数
        self.iMoney = iMoney  # (必填)动作涉及的金钱数
        self.Reason = Reason  # (必填)货币流动一级原因
        self.SubReason = SubReason  # (可填)货币流动二级原因
        self.Detail = Detail  # (必填)道货币流动描述，描述格式定义根据reason确定
        self.IDIPSource = IDIPSource  # (必填)idip渠道号
        self.AddOrReduce = AddOrReduce  # (必填)增加 0/减少 1
        self.iMoneyType = iMoneyType  # (必填)钱的类型MONEYTYPE,其它货币类型参考FAQ文档


class ResourceFlow(StructBasic):
    """STRUCT::ResourceFlow: (必填)货币流水"""

    __slots__ = (
        "GameSvrId", "dtEventTime", "vGameAppid", "PlatID", "iZoneAreaID", "vOpenID", "vRoleID", "vRoleName", "iLevel",
        "iVipLevel", "iRoleCE", "Sequence", "iResourceId", "AfterCount", "iCount", "Reason", "SubReason", "Detail",
        "IDIPSource", "AddOrReduce")

    def __init__(self, GameSvrId, dtEventTime, vGameAppid, PlatID, iZoneAreaID, vOpenID, vRoleID, vRoleName, iLevel,
                 iVipLevel, iRoleCE, Sequence, iResourceId, AfterCount, iCount, Reason, SubReason, Detail, IDIPSource,
                 AddOrReduce):
        self.GameSvrId = GameSvrId  # (必填)登录服务ID，分区服场景使用，合服后上报合服后服务器ID。
        self.dtEventTime = dtEventTime  # (必填)游戏事件的时间, 格式 YYYY-MM-DD HH:MM:SS
        self.vGameAppid = vGameAppid  # (必填)游戏APPID
        self.PlatID = PlatID  # (必填)ios 0/android 1
        self.iZoneAreaID = iZoneAreaID  # (必填)注册服ID，分区服场景使用。其他场景时填写0
        self.vOpenID = vOpenID  # (必填)用户OPENID号
        self.vRoleID = vRoleID  # (必填)玩家角色ID
        self.vRoleName = vRoleName  # (必填)玩家角色名
        self.iLevel = iLevel  # (必填)等级
        self.iVipLevel = iVipLevel  # (可填)VIP等级
        self.iRoleCE = iRoleCE  # (可填)玩家角色战力Combat Effectiveness
        self.Sequence = Sequence  # (可填)用于关联一次动作产生多条不同类型的货币流动日志
        self.iResourceId = iResourceId  # (必填)资源物品ID
        self.AfterCount = AfterCount  # (可填)动作后的资源数
        self.iCount = iCount  # (必填)动作涉及的资源数
        self.Reason = Reason  # (必填)资源流动一级原因
        self.SubReason = SubReason  # (可填)资源流动二级原因
        self.Detail = Detail  # (必填)资源流动描述，描述格式定义根据reason确定
        self.IDIPSource = IDIPSource  # (必填)idip渠道号
        self.AddOrReduce = AddOrReduce  # (必填)增加 0/减少 1


class ItemFlow(StructBasic):
    """STRUCT::ItemFlow: (必填)道具流水"""

    __slots__ = (
        "GameSvrId", "dtEventTime", "vGameAppid", "PlatID", "iZoneAreaID", "vOpenID", "vRoleID", "vRoleName", "iLevel",
        "iVipLevel", "iRoleCE", "Sequence", "iGoodsType", "iGoodsSubType", "iGoodsId", "iCount", "iBindType",
        "AfterCount",
        "Reason", "SubReason", "Detail", "IDIPSource", "iMoney", "iMoneyType", "AddOrReduce", "Online")

    def __init__(self, GameSvrId, dtEventTime, vGameAppid, PlatID, iZoneAreaID, vOpenID, vRoleID, vRoleName, iLevel,
                 iVipLevel, iRoleCE, Sequence, iGoodsType, iGoodsSubType, iGoodsId, iCount, iBindType, AfterCount,
                 Reason, SubReason, Detail, IDIPSource, iMoney, iMoneyType, AddOrReduce, Online):
        self.GameSvrId = GameSvrId  # (必填)登录服务ID，分区服场景使用，合服后上报合服后服务器ID。
        self.dtEventTime = dtEventTime  # (必填)游戏事件的时间, 格式 YYYY-MM-DD HH:MM:SS
        self.vGameAppid = vGameAppid  # (必填)游戏APPID
        self.PlatID = PlatID  # (必填)ios 0/android 1
        self.iZoneAreaID = iZoneAreaID  # (必填)注册服ID，分区服场景使用。其他场景时填写0
        self.vOpenID = vOpenID  # (必填)用户OPENID号
        self.vRoleID = vRoleID  # (必填)玩家角色ID
        self.vRoleName = vRoleName  # (必填)玩家角色名
        self.iLevel = iLevel  # (必填)等级
        self.iVipLevel = iVipLevel  # (可填)VIP等级
        self.iRoleCE = iRoleCE  # (可填)玩家角色战力Combat Effectiveness
        self.Sequence = Sequence  # (可填)用于关联一次购买产生多条不同类型的货币日志
        self.iGoodsType = iGoodsType  # (必填)道具类型
        self.iGoodsSubType = iGoodsSubType  # (必填)道具子类型
        self.iGoodsId = iGoodsId  # (必填)道具ID
        self.iCount = iCount  # (必填)数量
        self.iBindType = iBindType  # (必填)道具绑定属性
        self.AfterCount = AfterCount  # (必填)动作后的物品存量
        self.Reason = Reason  # (必填)道具流动一级原因
        self.SubReason = SubReason  # (必填)道具流动二级原因
        self.Detail = Detail  # (必填)道具流动描述，描述格式定义根据reason确定
        self.IDIPSource = IDIPSource  # (必填)idip渠道号
        self.iMoney = iMoney  # (必填)花费代币或金币购买道具情况下输出消耗的钱数量，否则填0
        self.iMoneyType = iMoneyType  # (必填)钱的类型MONEYTYPE,其它货币类型参考FAQ文档
        self.AddOrReduce = AddOrReduce  # (必填)增加 0/减少 1
        self.Online = Online  # (必填)玩家是否在线


class PlayerExpFlow(StructBasic):
    """STRUCT::PlayerExpFlow: (必填)玩家经验流水"""

    __slots__ = (
        "GameSvrId", "dtEventTime", "vGameAppid", "PlatID", "iZoneAreaID", "vOpenID", "vRoleID", "vRoleName", "iLevel",
        "iVipLevel", "iRoleCE", "ExpChange", "BeforeLevel", "AfterLevel", "iTime", "Reason", "SubReason", "Detail",
        "IDIPSource", "Online")

    def __init__(self, GameSvrId, dtEventTime, vGameAppid, PlatID, iZoneAreaID, vOpenID, vRoleID, vRoleName, iLevel,
                 iVipLevel, iRoleCE, ExpChange, BeforeLevel, AfterLevel, iTime, Reason, SubReason, Detail, IDIPSource,
                 Online):
        self.GameSvrId = GameSvrId  # (必填)登录服务ID，分区服场景使用，合服后上报合服后服务器ID。
        self.dtEventTime = dtEventTime  # (必填)游戏事件的时间, 格式 YYYY-MM-DD HH:MM:SS
        self.vGameAppid = vGameAppid  # (必填)游戏APPID
        self.PlatID = PlatID  # (必填)ios 0/android 1
        self.iZoneAreaID = iZoneAreaID  # (必填)注册服ID，分区服场景使用。其他场景时填写0
        self.vOpenID = vOpenID  # (必填)用户OPENID号
        self.vRoleID = vRoleID  # (必填)玩家角色ID
        self.vRoleName = vRoleName  # (必填)玩家角色名
        self.iLevel = iLevel  # (必填)等级
        self.iVipLevel = iVipLevel  # (可填)VIP等级
        self.iRoleCE = iRoleCE  # (可填)玩家角色战力Combat Effectiveness
        self.ExpChange = ExpChange  # (必填)经验变化
        self.BeforeLevel = BeforeLevel  # (可填)动作前等级
        self.AfterLevel = AfterLevel  # (必填)动作后等级
        self.iTime = iTime  # (必填)升级所用时间(秒)
        self.Reason = Reason  # (必填)经验流动一级原因
        self.SubReason = SubReason  # (必填)经验流动二级原因
        self.Detail = Detail  # (必填)道货币流动描述，描述格式定义根据reason确定
        self.IDIPSource = IDIPSource  # (必填)idip渠道号
        self.Online = Online  # (必填)玩家是否在线


class PlayerLevelFlow(StructBasic):
    """STRUCT::PlayerLevelFlow: (必填)玩家等级变化流水"""

    __slots__ = (
        "GameSvrId", "dtEventTime", "vGameAppid", "PlatID", "iZoneAreaID", "vOpenID", "vRoleID", "vRoleName", "iLevel",
        "iVipLevel", "iRoleCE", "BeforeLevel", "AfterLevel", "iTime")

    def __init__(self, GameSvrId, dtEventTime, vGameAppid, PlatID, iZoneAreaID, vOpenID, vRoleID, vRoleName, iLevel,
                 iVipLevel, iRoleCE, BeforeLevel, AfterLevel, iTime):
        self.GameSvrId = GameSvrId  # (必填)登录服务ID，分区服场景使用，合服后上报合服后服务器ID。
        self.dtEventTime = dtEventTime  # (必填)游戏事件的时间, 格式 YYYY-MM-DD HH:MM:SS
        self.vGameAppid = vGameAppid  # (必填)游戏APPID
        self.PlatID = PlatID  # (必填)ios 0/android 1
        self.iZoneAreaID = iZoneAreaID  # (必填)注册服ID，分区服场景使用。其他场景时填写0
        self.vOpenID = vOpenID  # (必填)用户OPENID号
        self.vRoleID = vRoleID  # (必填)玩家角色ID
        self.vRoleName = vRoleName  # (必填)玩家角色名
        self.iLevel = iLevel  # (必填)等级
        self.iVipLevel = iVipLevel  # (可填)VIP等级
        self.iRoleCE = iRoleCE  # (可填)玩家角色战力Combat Effectiveness
        self.BeforeLevel = BeforeLevel  # (可填)动作前等级
        self.AfterLevel = AfterLevel  # (必填)动作后等级
        self.iTime = iTime  # (必填)升级所用时间(秒)


class PlayerDead(StructBasic):
    """STRUCT::PlayerDead: 玩家死亡流水"""

    __slots__ = (
        "GameSvrId", "dtEventTime", "vGameAppid", "PlatID", "iZoneAreaID", "vOpenID", "vRoleID", "vRoleName", "iLevel",
        "iVipLevel", "iRoleCE", "MapId", "AreaId", "KillerId", "IsTianQian")

    def __init__(self, GameSvrId, dtEventTime, vGameAppid, PlatID, iZoneAreaID, vOpenID, vRoleID, vRoleName, iLevel,
                 iVipLevel, iRoleCE, MapId, AreaId, KillerId, IsTianQian):
        self.GameSvrId = GameSvrId  # (必填)登录服务ID，分区服场景使用，合服后上报合服后服务器ID。
        self.dtEventTime = dtEventTime  # (必填)游戏事件的时间, 格式 YYYY-MM-DD HH:MM:SS
        self.vGameAppid = vGameAppid  # (必填)游戏APPID
        self.PlatID = PlatID  # (必填)ios 0/android 1
        self.iZoneAreaID = iZoneAreaID  # (必填)注册服ID，分区服场景使用。其他场景时填写0
        self.vOpenID = vOpenID  # (必填)用户OPENID号
        self.vRoleID = vRoleID  # (必填)玩家角色ID
        self.vRoleName = vRoleName  # (必填)玩家角色名
        self.iLevel = iLevel  # (必填)等级
        self.iVipLevel = iVipLevel  # (可填)VIP等级
        self.iRoleCE = iRoleCE  # (可填)玩家角色战力Combat Effectiveness
        self.MapId = MapId  # (必填)角色所在地图
        self.AreaId = AreaId  # (可填)角色所在区域ID
        self.KillerId = KillerId  # (必填)凶手实体ID
        self.IsTianQian = IsTianQian  # (必填)是否天谴死亡 0-否, 1-是


class PlayerRelive(StructBasic):
    """STRUCT::PlayerRelive: 玩家复活流水"""

    __slots__ = (
        "GameSvrId", "dtEventTime", "vGameAppid", "PlatID", "iZoneAreaID", "vOpenID", "vRoleID", "vRoleName", "iLevel",
        "iVipLevel", "iRoleCE", "MapId", "AreaId", "ReliveType", "ItemId", "ItemNum", "RestReliveNum")

    def __init__(self, GameSvrId, dtEventTime, vGameAppid, PlatID, iZoneAreaID, vOpenID, vRoleID, vRoleName, iLevel,
                 iVipLevel, iRoleCE, MapId, AreaId, ReliveType, ItemId, ItemNum, RestReliveNum):
        self.GameSvrId = GameSvrId  # (必填)登录服务ID，分区服场景使用，合服后上报合服后服务器ID。
        self.dtEventTime = dtEventTime  # (必填)游戏事件的时间, 格式 YYYY-MM-DD HH:MM:SS
        self.vGameAppid = vGameAppid  # (必填)游戏APPID
        self.PlatID = PlatID  # (必填)ios 0/android 1
        self.iZoneAreaID = iZoneAreaID  # (必填)注册服ID，分区服场景使用。其他场景时填写0
        self.vOpenID = vOpenID  # (必填)用户OPENID号
        self.vRoleID = vRoleID  # (必填)玩家角色ID
        self.vRoleName = vRoleName  # (必填)玩家角色名
        self.iLevel = iLevel  # (必填)等级
        self.iVipLevel = iVipLevel  # (可填)VIP等级
        self.iRoleCE = iRoleCE  # (可填)玩家角色战力Combat Effectiveness
        self.MapId = MapId  # (必填)角色所在地图
        self.AreaId = AreaId  # (可填)角色所在区域ID
        self.ReliveType = ReliveType  # (必填)复活方式
        self.ItemId = ItemId  # (必填)复活消耗道具ID
        self.ItemNum = ItemNum  # (必填)复活消耗道具数量
        self.RestReliveNum = RestReliveNum  # (必填)剩余复活次数


class test(StructBasic):
    """STRUCT::test: test"""

    __slots__ = ("dtEventTime", "test1")

    def __init__(self, dtEventTime, test1):
        self.dtEventTime = dtEventTime  # (必填)游戏事件的时间, 格式 YYYY-MM-DD HH:MM:SS
        self.test1 = test1  # test


# -------------------------------------------------------------------


macrosgroups_map = {
    "PlatID": PlatID,  # 不要随意修改，否则影响统计结果
    "vGender": vGender,  # 玩家角色性别
    "ADDORREDUCE": ADDORREDUCE,  # 
    "PlayerMailOpType": PlayerMailOpType,  # playerMial类型
    "OnlineState": OnlineState,  # 玩家在线状态
    "ReliveType": ReliveType,  # 玩家复活方式
    "RESULT": RESULT,  # 单局结果，不要随意修改，否则影响统计结果
    "BATTLETYPE": BATTLETYPE,  # 玩法类型，根据游戏情况自定义
    "SingleOrteam": SingleOrteam,  # 进入方式
    "iTASKTYPE": iTASKTYPE,  # 根据游戏情况自定义
    "iSTATE": iSTATE,  # 根据游戏情况自定义
    "ResultFlag": ResultFlag,  # 检测结果
    "AddOrReduceOrReset": AddOrReduceOrReset,  # 加/减/重置
}

structs_map = {
    "GameSvrState": GameSvrState,  # (必填)服务器状态流水，每5分钟一条日志
    "GameOpenFlow": GameOpenFlow,  # (必填)开服流水表，每天一条
    "OnlineCnt": OnlineCnt,  # (必填)实时在线日志，每分钟一条
    "PlayerRegister": PlayerRegister,  # (必填)玩家创建角色
    "PlayerLogin": PlayerLogin,  # (必填)玩家登陆
    "PlayerTimingOnline": PlayerTimingOnline,  # (必填)玩家定时在线
    "PlayerLogout": PlayerLogout,  # (必填)玩家登出
    "MoneyFlow": MoneyFlow,  # (必填)货币流水
    "ResourceFlow": ResourceFlow,  # (必填)货币流水
    "ItemFlow": ItemFlow,  # (必填)道具流水
    "PlayerExpFlow": PlayerExpFlow,  # (必填)玩家经验流水
    "PlayerLevelFlow": PlayerLevelFlow,  # (必填)玩家等级变化流水
    "PlayerDead": PlayerDead,  # 玩家死亡流水
    "PlayerRelive": PlayerRelive,  # 玩家复活流水
    "test": test,  # test
}
