// Generated by protobuf plugin.  DO NOT EDIT!

package gameServerService

import (
    prpc "centralService/src/trpc"
)

func QueueServer_RegisterServer_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(GameServerInfo)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IQueueServerInterface).RegisterServer(in)
}
func QueueServer_UpdateServerInfo_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(GameServerInfo)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IQueueServerInterface).UpdateServerInfo(in)
}
func QueueServer_ActiveTick_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(Void)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IQueueServerInterface).ActiveTick(in)
}
var QueueServerServiceDesc = prpc.ServiceDesc{
    ServiceName: "QueueGameServer.QueueServer",
    Methods: []prpc.MethodDesc{
        {
            MethodName:  "RegisterServer",
            MethodIndex: 0,
            Handler:     QueueServer_RegisterServer_Handler,
        },
        {
            MethodName:  "UpdateServerInfo",
            MethodIndex: 1,
            Handler:     QueueServer_UpdateServerInfo_Handler,
        },
        {
            MethodName:  "ActiveTick",
            MethodIndex: 2,
            Handler:     QueueServer_ActiveTick_Handler,
        },
    },
}

func NewQueueServerService(client prpc.IEndPoint) *prpc.ServerEndPoint {
    return &prpc.ServerEndPoint{&QueueServerServiceDesc, client}
}

func NewQueueServerClient(channel *prpc.RpcChannel) *QueueServerClient {
    return &QueueServerClient{prpc.ClientEndPoint{channel}}
}

type QueueServerClient struct {
	prpc.ClientEndPoint
}
func (self *QueueServerClient) RegisterServer(in *GameServerInfo) (*Void, error) {
    err := self.Channel.CallMethod(&QueueServerServiceDesc.Methods[0], in)
    return &Void{}, err
}
func (self *QueueServerClient) UpdateServerInfo(in *GameServerInfo) (*Void, error) {
    err := self.Channel.CallMethod(&QueueServerServiceDesc.Methods[1], in)
    return &Void{}, err
}
func (self *QueueServerClient) ActiveTick(in *Void) (*Void, error) {
    err := self.Channel.CallMethod(&QueueServerServiceDesc.Methods[2], in)
    return &Void{}, err
}
type IQueueServerInterface interface {
    RegisterServer(*GameServerInfo) (*Void, error)
    UpdateServerInfo(*GameServerInfo) (*Void, error)
    ActiveTick(*Void) (*Void, error)
}

func GameServer_ActiveTickCallback_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(Void)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).ActiveTickCallback(in)
}
var GameServerServiceDesc = prpc.ServiceDesc{
    ServiceName: "QueueGameServer.GameServer",
    Methods: []prpc.MethodDesc{
        {
            MethodName:  "ActiveTickCallback",
            MethodIndex: 0,
            Handler:     GameServer_ActiveTickCallback_Handler,
        },
    },
}

func NewGameServerService(client prpc.IEndPoint) *prpc.ServerEndPoint {
    return &prpc.ServerEndPoint{&GameServerServiceDesc, client}
}

func NewGameServerClient(channel *prpc.RpcChannel) *GameServerClient {
    return &GameServerClient{prpc.ClientEndPoint{channel}}
}

type GameServerClient struct {
	prpc.ClientEndPoint
}
func (self *GameServerClient) ActiveTickCallback(in *Void) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[0], in)
    return &Void{}, err
}
type IGameServerInterface interface {
    ActiveTickCallback(*Void) (*Void, error)
}

