# coding: utf-8
# auto generated by export_navmesh.go
# sceneRes: field_hundunhuilang_08
# sceneId: 3223

datas = {31178006: 1, 31178007: 2, 31238006: 3, 31238007: 4, 31238008: 5, 32238006: 6, 32238007: 7, 32238008: 8, 33238006: 9, 33238007: 10, 33238008: 11}
