// Generated by protobuf plugin.  DO NOT EDIT!

package gameServerService

import (
    prpc "centralService/src/trpc"
)

func AuctionServer_RegisterServer_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(ServerInfoMessage)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IAuctionServerInterface).RegisterServer(in)
}
func AuctionServer_ActiveTick_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(Void)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IAuctionServerInterface).ActiveTick(in)
}
func AuctionServer_SaleItem_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(SaleItemReq)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IAuctionServerInterface).SaleItem(in)
}
func AuctionServer_DoSaleItem_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(DoSaleItemReq)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IAuctionServerInterface).DoSaleItem(in)
}
func AuctionServer_BuyItem_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(BuyItemReq)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IAuctionServerInterface).BuyItem(in)
}
func AuctionServer_DoBuyItem_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(DoBuyItemReq)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IAuctionServerInterface).DoBuyItem(in)
}
func AuctionServer_CancelSaleItem_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(CancelSaleItemReq)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IAuctionServerInterface).CancelSaleItem(in)
}
func AuctionServer_DoCancelSaleItem_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(DoCancelSaleItemReq)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IAuctionServerInterface).DoCancelSaleItem(in)
}
func AuctionServer_SearchItemsByItemId_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(SearchItemsByItemIdReq)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IAuctionServerInterface).SearchItemsByItemId(in)
}
func AuctionServer_GetItemLastAndAvgPrice_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(GetItemLastAndAvgPriceReq)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IAuctionServerInterface).GetItemLastAndAvgPrice(in)
}
func AuctionServer_GetCurrentSaleItemInfo_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(GetCurrentSaleItemInfoReq)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IAuctionServerInterface).GetCurrentSaleItemInfo(in)
}
func AuctionServer_GetPlayerAuctionItems_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(GetPlayerAuctionItemsReq)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IAuctionServerInterface).GetPlayerAuctionItems(in)
}
func AuctionServer_LoadPlayerAuctionItem_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(LoadPlayerAuctionItemReq)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IAuctionServerInterface).LoadPlayerAuctionItem(in)
}
func AuctionServer_DoCommand_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(DoCommandReq)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IAuctionServerInterface).DoCommand(in)
}
func AuctionServer_GetAuctionItemNumByCategoryId_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(GetItemNumByCategoryIdReq)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IAuctionServerInterface).GetAuctionItemNumByCategoryId(in)
}
func AuctionServer_BuyItemByItemId_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(BuyItemByItemIdReq)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IAuctionServerInterface).BuyItemByItemId(in)
}
func AuctionServer_DoBuyItemByItemId_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(DoBuyItemByItemIdReq)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IAuctionServerInterface).DoBuyItemByItemId(in)
}
func AuctionServer_GetAuctionItemsByAuctionIds_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(GetAuctionItemByAuctionIdsReq)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IAuctionServerInterface).GetAuctionItemsByAuctionIds(in)
}
var AuctionServerServiceDesc = prpc.ServiceDesc{
    ServiceName: "AuctionGameServer.AuctionServer",
    Methods: []prpc.MethodDesc{
        {
            MethodName:  "RegisterServer",
            MethodIndex: 0,
            Handler:     AuctionServer_RegisterServer_Handler,
        },
        {
            MethodName:  "ActiveTick",
            MethodIndex: 1,
            Handler:     AuctionServer_ActiveTick_Handler,
        },
        {
            MethodName:  "SaleItem",
            MethodIndex: 2,
            Handler:     AuctionServer_SaleItem_Handler,
        },
        {
            MethodName:  "DoSaleItem",
            MethodIndex: 3,
            Handler:     AuctionServer_DoSaleItem_Handler,
        },
        {
            MethodName:  "BuyItem",
            MethodIndex: 4,
            Handler:     AuctionServer_BuyItem_Handler,
        },
        {
            MethodName:  "DoBuyItem",
            MethodIndex: 5,
            Handler:     AuctionServer_DoBuyItem_Handler,
        },
        {
            MethodName:  "CancelSaleItem",
            MethodIndex: 6,
            Handler:     AuctionServer_CancelSaleItem_Handler,
        },
        {
            MethodName:  "DoCancelSaleItem",
            MethodIndex: 7,
            Handler:     AuctionServer_DoCancelSaleItem_Handler,
        },
        {
            MethodName:  "SearchItemsByItemId",
            MethodIndex: 8,
            Handler:     AuctionServer_SearchItemsByItemId_Handler,
        },
        {
            MethodName:  "GetItemLastAndAvgPrice",
            MethodIndex: 9,
            Handler:     AuctionServer_GetItemLastAndAvgPrice_Handler,
        },
        {
            MethodName:  "GetCurrentSaleItemInfo",
            MethodIndex: 10,
            Handler:     AuctionServer_GetCurrentSaleItemInfo_Handler,
        },
        {
            MethodName:  "GetPlayerAuctionItems",
            MethodIndex: 11,
            Handler:     AuctionServer_GetPlayerAuctionItems_Handler,
        },
        {
            MethodName:  "LoadPlayerAuctionItem",
            MethodIndex: 12,
            Handler:     AuctionServer_LoadPlayerAuctionItem_Handler,
        },
        {
            MethodName:  "DoCommand",
            MethodIndex: 13,
            Handler:     AuctionServer_DoCommand_Handler,
        },
        {
            MethodName:  "GetAuctionItemNumByCategoryId",
            MethodIndex: 14,
            Handler:     AuctionServer_GetAuctionItemNumByCategoryId_Handler,
        },
        {
            MethodName:  "BuyItemByItemId",
            MethodIndex: 15,
            Handler:     AuctionServer_BuyItemByItemId_Handler,
        },
        {
            MethodName:  "DoBuyItemByItemId",
            MethodIndex: 16,
            Handler:     AuctionServer_DoBuyItemByItemId_Handler,
        },
        {
            MethodName:  "GetAuctionItemsByAuctionIds",
            MethodIndex: 17,
            Handler:     AuctionServer_GetAuctionItemsByAuctionIds_Handler,
        },
    },
}

func NewAuctionServerService(client prpc.IEndPoint) *prpc.ServerEndPoint {
    return &prpc.ServerEndPoint{&AuctionServerServiceDesc, client}
}

func NewAuctionServerClient(channel *prpc.RpcChannel) *AuctionServerClient {
    return &AuctionServerClient{prpc.ClientEndPoint{channel}}
}

type AuctionServerClient struct {
	prpc.ClientEndPoint
}
func (self *AuctionServerClient) RegisterServer(in *ServerInfoMessage) (*Void, error) {
    err := self.Channel.CallMethod(&AuctionServerServiceDesc.Methods[0], in)
    return &Void{}, err
}
func (self *AuctionServerClient) ActiveTick(in *Void) (*Void, error) {
    err := self.Channel.CallMethod(&AuctionServerServiceDesc.Methods[1], in)
    return &Void{}, err
}
func (self *AuctionServerClient) SaleItem(in *SaleItemReq) (*Void, error) {
    err := self.Channel.CallMethod(&AuctionServerServiceDesc.Methods[2], in)
    return &Void{}, err
}
func (self *AuctionServerClient) DoSaleItem(in *DoSaleItemReq) (*Void, error) {
    err := self.Channel.CallMethod(&AuctionServerServiceDesc.Methods[3], in)
    return &Void{}, err
}
func (self *AuctionServerClient) BuyItem(in *BuyItemReq) (*Void, error) {
    err := self.Channel.CallMethod(&AuctionServerServiceDesc.Methods[4], in)
    return &Void{}, err
}
func (self *AuctionServerClient) DoBuyItem(in *DoBuyItemReq) (*Void, error) {
    err := self.Channel.CallMethod(&AuctionServerServiceDesc.Methods[5], in)
    return &Void{}, err
}
func (self *AuctionServerClient) CancelSaleItem(in *CancelSaleItemReq) (*Void, error) {
    err := self.Channel.CallMethod(&AuctionServerServiceDesc.Methods[6], in)
    return &Void{}, err
}
func (self *AuctionServerClient) DoCancelSaleItem(in *DoCancelSaleItemReq) (*Void, error) {
    err := self.Channel.CallMethod(&AuctionServerServiceDesc.Methods[7], in)
    return &Void{}, err
}
func (self *AuctionServerClient) SearchItemsByItemId(in *SearchItemsByItemIdReq) (*Void, error) {
    err := self.Channel.CallMethod(&AuctionServerServiceDesc.Methods[8], in)
    return &Void{}, err
}
func (self *AuctionServerClient) GetItemLastAndAvgPrice(in *GetItemLastAndAvgPriceReq) (*Void, error) {
    err := self.Channel.CallMethod(&AuctionServerServiceDesc.Methods[9], in)
    return &Void{}, err
}
func (self *AuctionServerClient) GetCurrentSaleItemInfo(in *GetCurrentSaleItemInfoReq) (*Void, error) {
    err := self.Channel.CallMethod(&AuctionServerServiceDesc.Methods[10], in)
    return &Void{}, err
}
func (self *AuctionServerClient) GetPlayerAuctionItems(in *GetPlayerAuctionItemsReq) (*Void, error) {
    err := self.Channel.CallMethod(&AuctionServerServiceDesc.Methods[11], in)
    return &Void{}, err
}
func (self *AuctionServerClient) LoadPlayerAuctionItem(in *LoadPlayerAuctionItemReq) (*Void, error) {
    err := self.Channel.CallMethod(&AuctionServerServiceDesc.Methods[12], in)
    return &Void{}, err
}
func (self *AuctionServerClient) DoCommand(in *DoCommandReq) (*Void, error) {
    err := self.Channel.CallMethod(&AuctionServerServiceDesc.Methods[13], in)
    return &Void{}, err
}
func (self *AuctionServerClient) GetAuctionItemNumByCategoryId(in *GetItemNumByCategoryIdReq) (*Void, error) {
    err := self.Channel.CallMethod(&AuctionServerServiceDesc.Methods[14], in)
    return &Void{}, err
}
func (self *AuctionServerClient) BuyItemByItemId(in *BuyItemByItemIdReq) (*Void, error) {
    err := self.Channel.CallMethod(&AuctionServerServiceDesc.Methods[15], in)
    return &Void{}, err
}
func (self *AuctionServerClient) DoBuyItemByItemId(in *DoBuyItemByItemIdReq) (*Void, error) {
    err := self.Channel.CallMethod(&AuctionServerServiceDesc.Methods[16], in)
    return &Void{}, err
}
func (self *AuctionServerClient) GetAuctionItemsByAuctionIds(in *GetAuctionItemByAuctionIdsReq) (*Void, error) {
    err := self.Channel.CallMethod(&AuctionServerServiceDesc.Methods[17], in)
    return &Void{}, err
}
type IAuctionServerInterface interface {
    RegisterServer(*ServerInfoMessage) (*Void, error)
    ActiveTick(*Void) (*Void, error)
    SaleItem(*SaleItemReq) (*Void, error)
    DoSaleItem(*DoSaleItemReq) (*Void, error)
    BuyItem(*BuyItemReq) (*Void, error)
    DoBuyItem(*DoBuyItemReq) (*Void, error)
    CancelSaleItem(*CancelSaleItemReq) (*Void, error)
    DoCancelSaleItem(*DoCancelSaleItemReq) (*Void, error)
    SearchItemsByItemId(*SearchItemsByItemIdReq) (*Void, error)
    GetItemLastAndAvgPrice(*GetItemLastAndAvgPriceReq) (*Void, error)
    GetCurrentSaleItemInfo(*GetCurrentSaleItemInfoReq) (*Void, error)
    GetPlayerAuctionItems(*GetPlayerAuctionItemsReq) (*Void, error)
    LoadPlayerAuctionItem(*LoadPlayerAuctionItemReq) (*Void, error)
    DoCommand(*DoCommandReq) (*Void, error)
    GetAuctionItemNumByCategoryId(*GetItemNumByCategoryIdReq) (*Void, error)
    BuyItemByItemId(*BuyItemByItemIdReq) (*Void, error)
    DoBuyItemByItemId(*DoBuyItemByItemIdReq) (*Void, error)
    GetAuctionItemsByAuctionIds(*GetAuctionItemByAuctionIdsReq) (*Void, error)
}

func GameServer_ActiveTickCallback_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(Void)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).ActiveTickCallback(in)
}
func GameServer_ReplySaleItem_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(SaleItemResp)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).ReplySaleItem(in)
}
func GameServer_ReplyDoSaleItem_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(DoSaleItemResp)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).ReplyDoSaleItem(in)
}
func GameServer_ReplyBuyItem_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(BuyItemResp)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).ReplyBuyItem(in)
}
func GameServer_ReplyDoBuyItem_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(DoBuyItemResp)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).ReplyDoBuyItem(in)
}
func GameServer_ReplyCancelSaleItem_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(CancelSaleItemResp)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).ReplyCancelSaleItem(in)
}
func GameServer_ReplyDoCancelSaleItem_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(DoCancelSaleItemResp)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).ReplyDoCancelSaleItem(in)
}
func GameServer_ReplySearchItemsByItemId_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(SearchItemsByItemIdResp)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).ReplySearchItemsByItemId(in)
}
func GameServer_ReplyGetItemLastAndAvgPrice_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(GetItemLastAndAvgPriceResp)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).ReplyGetItemLastAndAvgPrice(in)
}
func GameServer_ReplyGetCurrentSaleItemInfo_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(GetCurrentSaleItemInfoResp)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).ReplyGetCurrentSaleItemInfo(in)
}
func GameServer_ReplyGetPlayerAuctionItems_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(GetPlayerAuctionItemsResp)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).ReplyGetPlayerAuctionItems(in)
}
func GameServer_ReplyLoadPlayerAuctionItem_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(LoadPlayerAuctionItemResp)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).ReplyLoadPlayerAuctionItem(in)
}
func GameServer_OnItemBeSaled_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(OnItemBeSaledInfo)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).OnItemBeSaled(in)
}
func GameServer_OnItemSaling_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(OnItemSalingInfo)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).OnItemSaling(in)
}
func GameServer_ReplyDoCommand_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(DoCommandResp)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).ReplyDoCommand(in)
}
func GameServer_ReplyGetAuctionItemNumByCategoryId_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(GetItemNumByCategoryIdResp)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).ReplyGetAuctionItemNumByCategoryId(in)
}
func GameServer_ReplyBuyItemByItemId_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(BuyItemByItemIdResp)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).ReplyBuyItemByItemId(in)
}
func GameServer_ReplyDoBuyItemByItemId_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(DoBuyItemByItemIdResp)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).ReplyDoBuyItemByItemId(in)
}
func GameServer_ReplyGetAuctionItemsByAuctionIds_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(GetAuctionItemByAuctionIdsResp)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).ReplyGetAuctionItemsByAuctionIds(in)
}
func GameServer_PushItemPriceInfoList_Handler(endPoint prpc.IEndPoint, dec func(interface{}) error) (interface{}, error) {
    in := new(ItemPriceInfoList)
    if err := dec(in); err != nil {
        return nil, err
    }
    return endPoint.(IGameServerInterface).PushItemPriceInfoList(in)
}
var GameServerServiceDesc = prpc.ServiceDesc{
    ServiceName: "AuctionGameServer.GameServer",
    Methods: []prpc.MethodDesc{
        {
            MethodName:  "ActiveTickCallback",
            MethodIndex: 0,
            Handler:     GameServer_ActiveTickCallback_Handler,
        },
        {
            MethodName:  "ReplySaleItem",
            MethodIndex: 1,
            Handler:     GameServer_ReplySaleItem_Handler,
        },
        {
            MethodName:  "ReplyDoSaleItem",
            MethodIndex: 2,
            Handler:     GameServer_ReplyDoSaleItem_Handler,
        },
        {
            MethodName:  "ReplyBuyItem",
            MethodIndex: 3,
            Handler:     GameServer_ReplyBuyItem_Handler,
        },
        {
            MethodName:  "ReplyDoBuyItem",
            MethodIndex: 4,
            Handler:     GameServer_ReplyDoBuyItem_Handler,
        },
        {
            MethodName:  "ReplyCancelSaleItem",
            MethodIndex: 5,
            Handler:     GameServer_ReplyCancelSaleItem_Handler,
        },
        {
            MethodName:  "ReplyDoCancelSaleItem",
            MethodIndex: 6,
            Handler:     GameServer_ReplyDoCancelSaleItem_Handler,
        },
        {
            MethodName:  "ReplySearchItemsByItemId",
            MethodIndex: 7,
            Handler:     GameServer_ReplySearchItemsByItemId_Handler,
        },
        {
            MethodName:  "ReplyGetItemLastAndAvgPrice",
            MethodIndex: 8,
            Handler:     GameServer_ReplyGetItemLastAndAvgPrice_Handler,
        },
        {
            MethodName:  "ReplyGetCurrentSaleItemInfo",
            MethodIndex: 9,
            Handler:     GameServer_ReplyGetCurrentSaleItemInfo_Handler,
        },
        {
            MethodName:  "ReplyGetPlayerAuctionItems",
            MethodIndex: 10,
            Handler:     GameServer_ReplyGetPlayerAuctionItems_Handler,
        },
        {
            MethodName:  "ReplyLoadPlayerAuctionItem",
            MethodIndex: 11,
            Handler:     GameServer_ReplyLoadPlayerAuctionItem_Handler,
        },
        {
            MethodName:  "OnItemBeSaled",
            MethodIndex: 12,
            Handler:     GameServer_OnItemBeSaled_Handler,
        },
        {
            MethodName:  "OnItemSaling",
            MethodIndex: 13,
            Handler:     GameServer_OnItemSaling_Handler,
        },
        {
            MethodName:  "ReplyDoCommand",
            MethodIndex: 14,
            Handler:     GameServer_ReplyDoCommand_Handler,
        },
        {
            MethodName:  "ReplyGetAuctionItemNumByCategoryId",
            MethodIndex: 15,
            Handler:     GameServer_ReplyGetAuctionItemNumByCategoryId_Handler,
        },
        {
            MethodName:  "ReplyBuyItemByItemId",
            MethodIndex: 16,
            Handler:     GameServer_ReplyBuyItemByItemId_Handler,
        },
        {
            MethodName:  "ReplyDoBuyItemByItemId",
            MethodIndex: 17,
            Handler:     GameServer_ReplyDoBuyItemByItemId_Handler,
        },
        {
            MethodName:  "ReplyGetAuctionItemsByAuctionIds",
            MethodIndex: 18,
            Handler:     GameServer_ReplyGetAuctionItemsByAuctionIds_Handler,
        },
        {
            MethodName:  "PushItemPriceInfoList",
            MethodIndex: 19,
            Handler:     GameServer_PushItemPriceInfoList_Handler,
        },
    },
}

func NewGameServerService(client prpc.IEndPoint) *prpc.ServerEndPoint {
    return &prpc.ServerEndPoint{&GameServerServiceDesc, client}
}

func NewGameServerClient(channel *prpc.RpcChannel) *GameServerClient {
    return &GameServerClient{prpc.ClientEndPoint{channel}}
}

type GameServerClient struct {
	prpc.ClientEndPoint
}
func (self *GameServerClient) ActiveTickCallback(in *Void) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[0], in)
    return &Void{}, err
}
func (self *GameServerClient) ReplySaleItem(in *SaleItemResp) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[1], in)
    return &Void{}, err
}
func (self *GameServerClient) ReplyDoSaleItem(in *DoSaleItemResp) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[2], in)
    return &Void{}, err
}
func (self *GameServerClient) ReplyBuyItem(in *BuyItemResp) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[3], in)
    return &Void{}, err
}
func (self *GameServerClient) ReplyDoBuyItem(in *DoBuyItemResp) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[4], in)
    return &Void{}, err
}
func (self *GameServerClient) ReplyCancelSaleItem(in *CancelSaleItemResp) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[5], in)
    return &Void{}, err
}
func (self *GameServerClient) ReplyDoCancelSaleItem(in *DoCancelSaleItemResp) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[6], in)
    return &Void{}, err
}
func (self *GameServerClient) ReplySearchItemsByItemId(in *SearchItemsByItemIdResp) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[7], in)
    return &Void{}, err
}
func (self *GameServerClient) ReplyGetItemLastAndAvgPrice(in *GetItemLastAndAvgPriceResp) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[8], in)
    return &Void{}, err
}
func (self *GameServerClient) ReplyGetCurrentSaleItemInfo(in *GetCurrentSaleItemInfoResp) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[9], in)
    return &Void{}, err
}
func (self *GameServerClient) ReplyGetPlayerAuctionItems(in *GetPlayerAuctionItemsResp) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[10], in)
    return &Void{}, err
}
func (self *GameServerClient) ReplyLoadPlayerAuctionItem(in *LoadPlayerAuctionItemResp) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[11], in)
    return &Void{}, err
}
func (self *GameServerClient) OnItemBeSaled(in *OnItemBeSaledInfo) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[12], in)
    return &Void{}, err
}
func (self *GameServerClient) OnItemSaling(in *OnItemSalingInfo) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[13], in)
    return &Void{}, err
}
func (self *GameServerClient) ReplyDoCommand(in *DoCommandResp) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[14], in)
    return &Void{}, err
}
func (self *GameServerClient) ReplyGetAuctionItemNumByCategoryId(in *GetItemNumByCategoryIdResp) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[15], in)
    return &Void{}, err
}
func (self *GameServerClient) ReplyBuyItemByItemId(in *BuyItemByItemIdResp) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[16], in)
    return &Void{}, err
}
func (self *GameServerClient) ReplyDoBuyItemByItemId(in *DoBuyItemByItemIdResp) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[17], in)
    return &Void{}, err
}
func (self *GameServerClient) ReplyGetAuctionItemsByAuctionIds(in *GetAuctionItemByAuctionIdsResp) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[18], in)
    return &Void{}, err
}
func (self *GameServerClient) PushItemPriceInfoList(in *ItemPriceInfoList) (*Void, error) {
    err := self.Channel.CallMethod(&GameServerServiceDesc.Methods[19], in)
    return &Void{}, err
}
type IGameServerInterface interface {
    ActiveTickCallback(*Void) (*Void, error)
    ReplySaleItem(*SaleItemResp) (*Void, error)
    ReplyDoSaleItem(*DoSaleItemResp) (*Void, error)
    ReplyBuyItem(*BuyItemResp) (*Void, error)
    ReplyDoBuyItem(*DoBuyItemResp) (*Void, error)
    ReplyCancelSaleItem(*CancelSaleItemResp) (*Void, error)
    ReplyDoCancelSaleItem(*DoCancelSaleItemResp) (*Void, error)
    ReplySearchItemsByItemId(*SearchItemsByItemIdResp) (*Void, error)
    ReplyGetItemLastAndAvgPrice(*GetItemLastAndAvgPriceResp) (*Void, error)
    ReplyGetCurrentSaleItemInfo(*GetCurrentSaleItemInfoResp) (*Void, error)
    ReplyGetPlayerAuctionItems(*GetPlayerAuctionItemsResp) (*Void, error)
    ReplyLoadPlayerAuctionItem(*LoadPlayerAuctionItemResp) (*Void, error)
    OnItemBeSaled(*OnItemBeSaledInfo) (*Void, error)
    OnItemSaling(*OnItemSalingInfo) (*Void, error)
    ReplyDoCommand(*DoCommandResp) (*Void, error)
    ReplyGetAuctionItemNumByCategoryId(*GetItemNumByCategoryIdResp) (*Void, error)
    ReplyBuyItemByItemId(*BuyItemByItemIdResp) (*Void, error)
    ReplyDoBuyItemByItemId(*DoBuyItemByItemIdResp) (*Void, error)
    ReplyGetAuctionItemsByAuctionIds(*GetAuctionItemByAuctionIdsResp) (*Void, error)
    PushItemPriceInfoList(*ItemPriceInfoList) (*Void, error)
}

